import {
  Heart,
  Building2,
  GraduationCap,
  Landmark,
  Droplets,
  Truck,
  Shield,
  Users,
  Scale,
  FileText,
  Banknote,
  HardHat,
  TreePine,
  Lightbulb,
  Building,
  UserCheck,
  type LucideIcon,
} from "lucide-react"

export interface Department {
  id: string
  name: string
  nameNepali: string
  description: string
  icon: LucideIcon
  color: string
  bgColor: string
  borderColor: string
  programs: number
  budget: string
  status: "active" | "inactive" 
  href: string
}

export const departments: Department[] = [
  {
    id: "health",
    name: "Health Department",
    nameNepali: "स्वास्थ्य विभाग",
    description: "Public health services, hospitals, clinics, and health programs",
    icon: Heart,
    color: "text-rose-600",
    bgColor: "bg-rose-50",
    borderColor: "border-rose-200",
    programs: 131,
    budget: "NPR 706,497,000",
    status: "active",
    href: "/departments/health",
  },
  {
    id: "city-development",
    name: "City Planning Commission",
    nameNepali: "सहरी योजना आयोग",
    description:
      "City planning, governance, digital innovation, disaster resilience, and economic development programs",
    icon: Building2,
    color: "text-blue-600",
    bgColor: "bg-blue-50",
    borderColor: "border-blue-200",
    programs: 44,
    budget: "NPR 115.7M",
    status: "active",
    href: "/departments/urban-development",
  },
  {
    id: "education",
    name: "Education Department",
    nameNepali: "शिक्षा विभाग",
    description: "Schools, libraries, scholarships, and educational programs",
    icon: GraduationCap,
    color: "text-amber-600",
    bgColor: "bg-amber-50",
    borderColor: "border-amber-200",
    programs: 136,
    budget: "NPR 1,049,098,000",
    status: "active",
    href: "/departments/education",
  },
{
    id: "disaster",
    name: "Disaster Department",
    nameNepali: "सुरक्षा तथा विपद् व्यवस्थापन",
    description: "Public safety, emergency response, and disaster management",
    icon: Shield,
    color: "text-red-600",
    bgColor: "bg-red-50",
    borderColor: "border-red-200",
    programs: 42,
    budget: "NPR 158,200,000",
    status: "active",
    href: "/departments/disaster",
  },


  {
    id: "administration",
    name: "Administration Deparment",
    nameNepali: "प्रशासन विभाग",
    description: "General administration, HR, and governance services",
    icon: Landmark,
    color: "text-slate-600",
    bgColor: "bg-slate-50",
    borderColor: "border-slate-200",
    programs: 88,
    budget: "NPR 792,730,000",
    status: "inactive",
    href: "/departments/administration",
  },
  {
    id: "revenue",
    name: "Revenue Department",
    nameNepali: "राजश्व विभाग",
    description: "Tax enforcement, revenue collection, and non-tax monitoring",
    icon: Droplets,
    color: "text-cyan-600",
    bgColor: "bg-cyan-50",
    borderColor: "border-cyan-200",
    programs: 14,
    budget: "NPR 106,100,000",
    status: "inactive",
    href: "/departments/water-sanitation",
  },
  
  {
    id: "public-work",
    name: "Public Work Department",
    nameNepali: "सार्वजनिक निर्माण विभाग",
    description: "Social programs, elderly care, disability services, and welfare",
    icon: Users,
    color: "text-pink-600",
    bgColor: "bg-pink-50",
    borderColor: "border-pink-200",
    programs: 81,
    budget: "NPR 10,850,156,000",
    status: "inactive",
    href: "/departments/social-welfare",
  },
  {
    id: "law",
    name: "Law and Human Right Department",
    nameNepali: "कानुन तथा मानव अधिकार विभाग",
    description: "Legal services, dispute resolution, and regulatory compliance",
    icon: Scale,
    color: "text-indigo-600",
    bgColor: "bg-indigo-50",
    borderColor: "border-indigo-200",
    programs: 24,
    budget: "NPR 64,500,000",
    status: "inactive",
    href: "/departments/law",
  },
  {
    id: "social-development", 
    name: "Social Development Department",
    nameNepali: "सामाजिक विकास विभाग",
    description: "Social welfare programs, community development, and support for vulnerable groups",
    icon: FileText,
    color: "text-teal-600",
    bgColor: "bg-teal-50",
    borderColor: "border-teal-200",
    programs: 164,
    budget: "NPR 2,355,403,000",
    status: "inactive",
    href: "/departments/planning",
  },
  {
    id: "finance",
    name: "Finance Department",
    nameNepali: "वित्त विभाग",
    description: "Budget planning, expenditure control, financial management, and reporting",
    icon: Banknote,
    color: "text-emerald-600",
    bgColor: "bg-emerald-50",
    borderColor: "border-emerald-200",
    programs: 8,
    budget: "NPR 315,600,000",
    status: "inactive",
    href: "/departments/revenue",
  },
  {
    id: "agriculture-livestock", 
    name: "Agriculture and Livestock Department",
    nameNepali: "कृषि तथा पशुपंक्षी विभाग",
    description: "Agriculture services, livestock management, food quality regulation, and monitoring",
    icon: HardHat,
    color: "text-yellow-600",
    bgColor: "bg-yellow-50",
    borderColor: "border-yellow-200",
    programs: 19,
    budget: "NPR 263,020,000",
    status: "inactive",
    href: "/departments/infrastructure",
  },
  {
    id: "environment",
    name: "Environment Management Department",
    nameNepali: "वातावरण व्यवस्थापन विभाग",
    description: "Environmental protection, parks, green spaces, and pollution control",
    icon: TreePine,
    color: "text-green-600",
    bgColor: "bg-green-50",
    borderColor: "border-green-200",
    programs: 149,
    budget: "NPR 1,344,970,000",
    status: "inactive",
    href: "/departments/environment",
  },
  {
    id: "it",
    name: "Information Technology Department",
    nameNepali: "सूचना प्रविधि विभाग",
    description: "Digital infrastructure, e-governance, and technology services",
    icon: Lightbulb,
    color: "text-violet-600",
    bgColor: "bg-violet-50",
    borderColor: "border-violet-200",
    programs: 60,
    budget: "NPR 172,500,000",
    status: "inactive",
    href: "/departments/it",
  },
  {
    id: "heritage",
    name: "Culture Heritage and Tourism Department",
    nameNepali: "सम्पदा तथा पर्यटन विभाग",
    description: "Cultural heritage preservation, tourism promotion, and sustainable development",
    icon: Building,
    color: "text-stone-600",
    bgColor: "bg-stone-50",
    borderColor: "border-stone-200",
    programs: 390,
    budget: "NPR 631,318,000",
    status: "inactive",
    href: "/departments/heritage",
  },
  {
    id: "cooperative",
    name: "Cooperative Department",
    nameNepali: "सहकारी विभाग",
    description: "Cooperative registration, promotion, regulation, and dispute resolution",
    icon: UserCheck,
    color: "text-sky-600",
    bgColor: "bg-sky-50",
    borderColor: "border-sky-200",
    programs: 17,
    budget: "NPR 117,950,000",
    status: "inactive",
    href: "/departments/human-resources",
  },
  {
    id: "park-greenery",
    name: "Park and Greenery Promotion Project",
    nameNepali: "पार्क तथा हरियाली प्रवर्द्धन आयोजना",
    description: "Park development, urban greenery management, and quality of life enhancement",
    icon: Truck,
    color: "text-orange-600",
    bgColor: "bg-orange-50",
    borderColor: "border-orange-200",
    programs: 59,
    budget: "NPR 54,500,000",
    status: "inactive",
    href: "/departments/transportation",
  },
]

export function getDepartmentById(id: string): Department | undefined {
  return departments.find((dept) => dept.id === id)
}
