import {
  Heart,
  Building2,
  GraduationCap,
  Landmark,
  Droplets,
  Truck,
  Shield,
  Users,
  Scale,
  FileText,
  Banknote,
  HardHat,
  TreePine,
  Lightbulb,
  Building,
  UserCheck,
  type LucideIcon,
} from "lucide-react"

export interface Department {
  id: string
  name: string
  nameNepali: string
  description: string
  icon: LucideIcon
  color: string
  bgColor: string
  borderColor: string
  programs: number
  budget: string
  status: "active" | "planning" | "review"
  href: string
}

export const departments: Department[] = [
  {
    id: "health",
    name: "Health Department",
    nameNepali: "स्वास्थ्य विभाग",
    description: "Public health services, hospitals, clinics, and health programs",
    icon: Heart,
    color: "text-rose-600",
    bgColor: "bg-rose-50",
    borderColor: "border-rose-200",
    programs: 42,
    budget: "NPR 850M",
    status: "active",
    href: "/departments/health",
  },
  {
    id: "urban-development",
    name: "City Planning Commission",
    nameNepali: "सहरी योजना आयोग",
    description:
      "City planning, governance, digital innovation, disaster resilience, and economic development programs",
    icon: Building2,
    color: "text-blue-600",
    bgColor: "bg-blue-50",
    borderColor: "border-blue-200",
    programs: 44,
    budget: "NPR 115.7M",
    status: "active",
    href: "/departments/urban-development",
  },
  {
    id: "education",
    name: "Education Department",
    nameNepali: "शिक्षा विभाग",
    description: "Schools, libraries, scholarships, and educational programs",
    icon: GraduationCap,
    color: "text-amber-600",
    bgColor: "bg-amber-50",
    borderColor: "border-amber-200",
    programs: 35,
    budget: "NPR 720M",
    status: "active",
    href: "/departments/education",
  },
  {
    id: "administration",
    name: "Administration",
    nameNepali: "प्रशासन विभाग",
    description: "General administration, HR, and governance services",
    icon: Landmark,
    color: "text-slate-600",
    bgColor: "bg-slate-50",
    borderColor: "border-slate-200",
    programs: 28,
    budget: "NPR 450M",
    status: "active",
    href: "/departments/administration",
  },
  {
    id: "water-sanitation",
    name: "Water & Sanitation",
    nameNepali: "खानेपानी तथा सरसफाई",
    description: "Water supply, sewage management, and sanitation programs",
    icon: Droplets,
    color: "text-cyan-600",
    bgColor: "bg-cyan-50",
    borderColor: "border-cyan-200",
    programs: 32,
    budget: "NPR 980M",
    status: "active",
    href: "/departments/water-sanitation",
  },
  {
    id: "transportation",
    name: "Transportation",
    nameNepali: "यातायात विभाग",
    description: "Roads, public transport, traffic management, and parking",
    icon: Truck,
    color: "text-orange-600",
    bgColor: "bg-orange-50",
    borderColor: "border-orange-200",
    programs: 25,
    budget: "NPR 1.5B",
    status: "active",
    href: "/departments/transportation",
  },
  {
    id: "security",
    name: "Security & Disaster",
    nameNepali: "सुरक्षा तथा विपद् व्यवस्थापन",
    description: "Public safety, emergency response, and disaster management",
    icon: Shield,
    color: "text-red-600",
    bgColor: "bg-red-50",
    borderColor: "border-red-200",
    programs: 18,
    budget: "NPR 380M",
    status: "active",
    href: "/departments/security",
  },
  {
    id: "social-welfare",
    name: "Social Welfare",
    nameNepali: "समाज कल्याण विभाग",
    description: "Social programs, elderly care, disability services, and welfare",
    icon: Users,
    color: "text-pink-600",
    bgColor: "bg-pink-50",
    borderColor: "border-pink-200",
    programs: 22,
    budget: "NPR 320M",
    status: "active",
    href: "/departments/social-welfare",
  },
  {
    id: "law",
    name: "Law & Justice",
    nameNepali: "कानून तथा न्याय",
    description: "Legal services, dispute resolution, and regulatory compliance",
    icon: Scale,
    color: "text-indigo-600",
    bgColor: "bg-indigo-50",
    borderColor: "border-indigo-200",
    programs: 15,
    budget: "NPR 180M",
    status: "review",
    href: "/departments/law",
  },
  {
    id: "planning",
    name: "Planning & Monitoring",
    nameNepali: "योजना तथा अनुगमन",
    description: "Strategic planning, project monitoring, and evaluation",
    icon: FileText,
    color: "text-teal-600",
    bgColor: "bg-teal-50",
    borderColor: "border-teal-200",
    programs: 20,
    budget: "NPR 250M",
    status: "active",
    href: "/departments/planning",
  },
  {
    id: "revenue",
    name: "Revenue & Finance",
    nameNepali: "राजस्व तथा वित्त",
    description: "Tax collection, budgeting, financial management, and auditing",
    icon: Banknote,
    color: "text-emerald-600",
    bgColor: "bg-emerald-50",
    borderColor: "border-emerald-200",
    programs: 16,
    budget: "NPR 420M",
    status: "active",
    href: "/departments/revenue",
  },
  {
    id: "infrastructure",
    name: "Infrastructure",
    nameNepali: "पूर्वाधार विभाग",
    description: "Public buildings, bridges, and major construction projects",
    icon: HardHat,
    color: "text-yellow-600",
    bgColor: "bg-yellow-50",
    borderColor: "border-yellow-200",
    programs: 30,
    budget: "NPR 2.1B",
    status: "active",
    href: "/departments/infrastructure",
  },
  {
    id: "environment",
    name: "Environment",
    nameNepali: "वातावरण विभाग",
    description: "Environmental protection, parks, green spaces, and pollution control",
    icon: TreePine,
    color: "text-green-600",
    bgColor: "bg-green-50",
    borderColor: "border-green-200",
    programs: 24,
    budget: "NPR 560M",
    status: "active",
    href: "/departments/environment",
  },
  {
    id: "it",
    name: "IT & Digital Services",
    nameNepali: "सूचना प्रविधि विभाग",
    description: "Digital infrastructure, e-governance, and technology services",
    icon: Lightbulb,
    color: "text-violet-600",
    bgColor: "bg-violet-50",
    borderColor: "border-violet-200",
    programs: 12,
    budget: "NPR 280M",
    status: "planning",
    href: "/departments/it",
  },
  {
    id: "heritage",
    name: "Heritage & Culture",
    nameNepali: "सम्पदा तथा संस्कृति",
    description: "Cultural preservation, heritage sites, and cultural programs",
    icon: Building,
    color: "text-stone-600",
    bgColor: "bg-stone-50",
    borderColor: "border-stone-200",
    programs: 19,
    budget: "NPR 340M",
    status: "active",
    href: "/departments/heritage",
  },
  {
    id: "human-resources",
    name: "Human Resources",
    nameNepali: "जनशक्ति विभाग",
    description: "Staff management, training, recruitment, and capacity building",
    icon: UserCheck,
    color: "text-sky-600",
    bgColor: "bg-sky-50",
    borderColor: "border-sky-200",
    programs: 14,
    budget: "NPR 220M",
    status: "active",
    href: "/departments/human-resources",
  },
]

export function getDepartmentById(id: string): Department | undefined {
  return departments.find((dept) => dept.id === id)
}
