// lib/disaster.ts

// --------------------
// Types
// --------------------
export interface KMCProgram {
  id: string
  department: string
  sector: string
  subSector: string
  thematicArea?: string
  mainProgram: string
  programName: string
  budget: number
  budgetCode: string
  sdg: {
    direct: string[]
    indirect: string[]
  }
  linkageScores: {
    sdgScore: number
    isoScore: number
    sciScore: number
    linkageType: string
  }
  projectPhase: {
    phase: string
    progress?: number
  }
}

export interface DisasterThematicArea {
  id: string
  name: string
  nameNp: string
  color: string
  programs: number
  standards: {
    sdg: string[]
    iso: string[]
    sci: string[]
  }
}

// --------------------
// Disaster Thematic Areas
// --------------------
export const disasterThematicAreas: DisasterThematicArea[] = [
  {
    id: "preparedness",
    name: "Preparedness",
    nameNp: "तयारी",
    color: "#3B82F6",
    programs: 8,
    standards: { sdg: ["11.5", "13.1"], iso: ["16.1"], sci: ["DM-1"] },
  },
  {
    id: "response",
    name: "Response",
    nameNp: "प्रतिक्रिया",
    color: "#F59E0B",
    programs: 10,
    standards: { sdg: ["3.d", "11.b"], iso: ["19.2"], sci: ["DM-2"] },
  },
  {
    id: "recovery",
    name: "Recovery",
    nameNp: "पुनःस्थापना",
    color: "#22C55E",
    programs: 6,
    standards: { sdg: ["11.5", "1.5"], iso: ["17.3"], sci: ["DM-3"] },
  },
  {
    id: "mitigation",
    name: "Mitigation",
    nameNp: "जोखिम न्यूनीकरण",
    color: "#8B5CF6",
    programs: 5,
    standards: { sdg: ["9.1", "13.2"], iso: ["14.1"], sci: ["DM-4"] },
  },
]

// --------------------
// Disaster Programs (1–42)
// --------------------
export const disasterPrograms: KMCProgram[] = [
  // -------- Preparedness (1–10)
  {
    id: "disaster-1",
    department: "बिपद व्यवस्थापन विभाग",
    sector: "Disaster Management",
    subSector: "Preparedness",
    thematicArea: "preparedness",
    mainProgram: "Disaster Preparedness Program",
    programName: "Emergency Planning",
    budget: 2000000,
    budgetCode: "DM-001",
    sdg: { direct: ["13.1"], indirect: ["11.5"] },
    linkageScores: { sdgScore: 4, isoScore: 3, sciScore: 4, linkageType: "concurrence" },
    projectPhase: { phase: "planning", progress: 20 },
  },
  {
    id: "disaster-2",
    department: "बिपद व्यवस्थापन विभाग",
    sector: "Disaster Management",
    subSector: "Preparedness",
    thematicArea: "preparedness",
    mainProgram: "Disaster Preparedness Program",
    programName: "Community Awareness Training",
    budget: 2150000,
    budgetCode: "DM-002",
    sdg: { direct: ["13.1"], indirect: ["11.5"] },
    linkageScores: { sdgScore: 4, isoScore: 3, sciScore: 4, linkageType: "concurrence" },
    projectPhase: { phase: "planning", progress: 25 },
  },
  {
    id: "disaster-3",
    department: "बिपद व्यवस्थापन विभाग",
    sector: "Disaster Management",
    subSector: "Preparedness",
    thematicArea: "preparedness",
    mainProgram: "Disaster Preparedness Program",
    programName: "Early Warning System",
    budget: 2300000,
    budgetCode: "DM-003",
    sdg: { direct: ["13.1"], indirect: ["11.5"] },
    linkageScores: { sdgScore: 4, isoScore: 3, sciScore: 4, linkageType: "concurrence" },
    projectPhase: { phase: "planning", progress: 30 },
  },
  {
    id: "disaster-4",
    department: "बिपद व्यवस्थापन विभाग",
    sector: "Disaster Management",
    subSector: "Preparedness",
    thematicArea: "preparedness",
    mainProgram: "Disaster Preparedness Program",
    programName: "Evacuation Route Mapping",
    budget: 2450000,
    budgetCode: "DM-004",
    sdg: { direct: ["13.1"], indirect: ["11.5"] },
    linkageScores: { sdgScore: 4, isoScore: 3, sciScore: 4, linkageType: "concurrence" },
    projectPhase: { phase: "planning", progress: 35 },
  },
  {
    id: "disaster-5",
    department: "बिपद व्यवस्थापन विभाग",
    sector: "Disaster Management",
    subSector: "Preparedness",
    thematicArea: "preparedness",
    mainProgram: "Disaster Preparedness Program",
    programName: "Mock Drill Exercises",
    budget: 2600000,
    budgetCode: "DM-005",
    sdg: { direct: ["13.1"], indirect: ["11.5"] },
    linkageScores: { sdgScore: 4, isoScore: 3, sciScore: 4, linkageType: "concurrence" },
    projectPhase: { phase: "planning", progress: 40 },
  },
  {
    id: "disaster-6",
    department: "बिपद व्यवस्थापन विभाग",
    sector: "Disaster Management",
    subSector: "Preparedness",
    thematicArea: "preparedness",
    mainProgram: "Disaster Preparedness Program",
    programName: "School Safety Program",
    budget: 2750000,
    budgetCode: "DM-006",
    sdg: { direct: ["13.1"], indirect: ["11.5"] },
    linkageScores: { sdgScore: 4, isoScore: 3, sciScore: 4, linkageType: "concurrence" },
    projectPhase: { phase: "planning", progress: 45 },
  },
  {
    id: "disaster-7",
    department: "बिपद व्यवस्थापन विभाग",
    sector: "Disaster Management",
    subSector: "Preparedness",
    thematicArea: "preparedness",
    mainProgram: "Disaster Preparedness Program",
    programName: "Hospital Preparedness",
    budget: 2900000,
    budgetCode: "DM-007",
    sdg: { direct: ["13.1"], indirect: ["11.5"] },
    linkageScores: { sdgScore: 4, isoScore: 3, sciScore: 4, linkageType: "concurrence" },
    projectPhase: { phase: "planning", progress: 50 },
  },
  {
    id: "disaster-8",
    department: "बिपद व्यवस्थापन विभाग",
    sector: "Disaster Management",
    subSector: "Preparedness",
    thematicArea: "preparedness",
    mainProgram: "Disaster Preparedness Program",
    programName: "Emergency Stockpiling",
    budget: 3050000,
    budgetCode: "DM-008",
    sdg: { direct: ["13.1"], indirect: ["11.5"] },
    linkageScores: { sdgScore: 4, isoScore: 3, sciScore: 4, linkageType: "concurrence" },
    projectPhase: { phase: "planning", progress: 55 },
  },
  {
    id: "disaster-9",
    department: "बिपद व्यवस्थापन विभाग",
    sector: "Disaster Management",
    subSector: "Preparedness",
    thematicArea: "preparedness",
    mainProgram: "Disaster Preparedness Program",
    programName: "Volunteer Training",
    budget: 3200000,
    budgetCode: "DM-009",
    sdg: { direct: ["13.1"], indirect: ["11.5"] },
    linkageScores: { sdgScore: 4, isoScore: 3, sciScore: 4, linkageType: "concurrence" },
    projectPhase: { phase: "planning", progress: 60 },
  },
  {
    id: "disaster-10",
    department: "बिपद व्यवस्थापन विभाग",
    sector: "Disaster Management",
    subSector: "Preparedness",
    thematicArea: "preparedness",
    mainProgram: "Disaster Preparedness Program",
    programName: "Ward Level Disaster Plans",
    budget: 3350000,
    budgetCode: "DM-010",
    sdg: { direct: ["13.1"], indirect: ["11.5"] },
    linkageScores: { sdgScore: 4, isoScore: 3, sciScore: 4, linkageType: "concurrence" },
    projectPhase: { phase: "planning", progress: 65 },
  },

  // -------- Response (11–20)
  {
    id: "disaster-11",
    department: "बिपद व्यवस्थापन विभाग",
    sector: "Disaster Management",
    subSector: "Emergency Response",
    thematicArea: "response",
    mainProgram: "Emergency Response Program",
    programName: "Rapid Response Team",
    budget: 3500000,
    budgetCode: "DM-011",
    sdg: { direct: ["11.5"], indirect: ["3.d"] },
    linkageScores: { sdgScore: 5, isoScore: 4, sciScore: 5, linkageType: "concurrence" },
    projectPhase: { phase: "response", progress: 40 },
  },
  {
    id: "disaster-12",
    department: "बिपद व्यवस्थापन विभाग",
    sector: "Disaster Management",
    subSector: "Emergency Response",
    thematicArea: "response",
    mainProgram: "Emergency Response Program",
    programName: "Search and Rescue",
    budget: 3700000,
    budgetCode: "DM-012",
    sdg: { direct: ["11.5"], indirect: ["3.d"] },
    linkageScores: { sdgScore: 5, isoScore: 4, sciScore: 5, linkageType: "concurrence" },
    projectPhase: { phase: "response", progress: 45 },
  },
  {
    id: "disaster-13",
    department: "बिपद व्यवस्थापन विभाग",
    sector: "Disaster Management",
    subSector: "Emergency Response",
    thematicArea: "response",
    mainProgram: "Emergency Response Program",
    programName: "Emergency Medical Support",
    budget: 3900000,
    budgetCode: "DM-013",
    sdg: { direct: ["11.5"], indirect: ["3.d"] },
    linkageScores: { sdgScore: 5, isoScore: 4, sciScore: 5, linkageType: "concurrence" },
    projectPhase: { phase: "response", progress: 50 },
  },
  {
    id: "disaster-14",
    department: "बिपद व्यवस्थापन विभाग",
    sector: "Disaster Management",
    subSector: "Emergency Response",
    thematicArea: "response",
    mainProgram: "Emergency Response Program",
    programName: "Fire & Rescue Services",
    budget: 4100000,
    budgetCode: "DM-014",
    sdg: { direct: ["11.5"], indirect: ["3.d"] },
    linkageScores: { sdgScore: 5, isoScore: 4, sciScore: 5, linkageType: "concurrence" },
    projectPhase: { phase: "response", progress: 55 },
  },
  {
    id: "disaster-15",
    department: "बिपद व्यवस्थापन विभाग",
    sector: "Disaster Management",
    subSector: "Emergency Response",
    thematicArea: "response",
    mainProgram: "Emergency Response Program",
    programName: "Relief Distribution",
    budget: 4300000,
    budgetCode: "DM-015",
    sdg: { direct: ["11.5"], indirect: ["3.d"] },
    linkageScores: { sdgScore: 5, isoScore: 4, sciScore: 5, linkageType: "concurrence" },
    projectPhase: { phase: "response", progress: 60 },
  },
  {
    id: "disaster-16",
    department: "बिपद व्यवस्थापन विभाग",
    sector: "Disaster Management",
    subSector: "Emergency Response",
    thematicArea: "response",
    mainProgram: "Emergency Response Program",
    programName: "Temporary Shelter Setup",
    budget: 4500000,
    budgetCode: "DM-016",
    sdg: { direct: ["11.5"], indirect: ["3.d"] },
    linkageScores: { sdgScore: 5, isoScore: 4, sciScore: 5, linkageType: "concurrence" },
    projectPhase: { phase: "response", progress: 65 },
  },
  {
    id: "disaster-17",
    department: "बिपद व्यवस्थापन विभाग",
    sector: "Disaster Management",
    subSector: "Emergency Response",
    thematicArea: "response",
    mainProgram: "Emergency Response Program",
    programName: "Damage Assessment",
    budget: 4700000,
    budgetCode: "DM-017",
    sdg: { direct: ["11.5"], indirect: ["3.d"] },
    linkageScores: { sdgScore: 5, isoScore: 4, sciScore: 5, linkageType: "concurrence" },
    projectPhase: { phase: "response", progress: 70 },
  },
  {
    id: "disaster-18",
    department: "बिपद व्यवस्थापन विभाग",
    sector: "Disaster Management",
    subSector: "Emergency Response",
    thematicArea: "response",
    mainProgram: "Emergency Response Program",
    programName: "Psychosocial Support",
    budget: 4900000,
    budgetCode: "DM-018",
    sdg: { direct: ["11.5"], indirect: ["3.d"] },
    linkageScores: { sdgScore: 5, isoScore: 4, sciScore: 5, linkageType: "concurrence" },
    projectPhase: { phase: "response", progress: 75 },
  },
  {
    id: "disaster-19",
    department: "बिपद व्यवस्थापन विभाग",
    sector: "Disaster Management",
    subSector: "Emergency Response",
    thematicArea: "response",
    mainProgram: "Emergency Response Program",
    programName: "Water & Sanitation Support",
    budget: 5100000,
    budgetCode: "DM-019",
    sdg: { direct: ["11.5"], indirect: ["3.d"] },
    linkageScores: { sdgScore: 5, isoScore: 4, sciScore: 5, linkageType: "concurrence" },
    projectPhase: { phase: "response", progress: 80 },
  },
  {
    id: "disaster-20",
    department: "बिपद व्यवस्थापन विभाग",
    sector: "Disaster Management",
    subSector: "Emergency Response",
    thematicArea: "response",
    mainProgram: "Emergency Response Program",
    programName: "Logistics & Coordination",
    budget: 5300000,
    budgetCode: "DM-020",
    sdg: { direct: ["11.5"], indirect: ["3.d"] },
    linkageScores: { sdgScore: 5, isoScore: 4, sciScore: 5, linkageType: "concurrence" },
    projectPhase: { phase: "response", progress: 85 },
  },

  // -------- Recovery (21–30)
  {
    id: "disaster-21",
    department: "बिपद व्यवस्थापन विभाग",
    sector: "Disaster Management",
    subSector: "Post Disaster Recovery",
    thematicArea: "recovery",
    mainProgram: "Recovery & Rehabilitation Program",
    programName: "Temporary Housing",
    budget: 5500000,
    budgetCode: "DM-021",
    sdg: { direct: ["11.5"], indirect: ["1.5"] },
    linkageScores: { sdgScore: 4, isoScore: 3, sciScore: 4, linkageType: "concurrence" },
    projectPhase: { phase: "recovery", progress: 35 },
  },
  {
    id: "disaster-22",
    department: "बिपद व्यवस्थापन विभाग",
    sector: "Disaster Management",
    subSector: "Post Disaster Recovery",
    thematicArea: "recovery",
    mainProgram: "Recovery & Rehabilitation Program",
    programName: "Housing Reconstruction",
    budget: 5700000,
    budgetCode: "DM-022",
    sdg: { direct: ["11.5"], indirect: ["1.5"] },
    linkageScores: { sdgScore: 4, isoScore: 3, sciScore: 4, linkageType: "concurrence" },
    projectPhase: { phase: "recovery", progress: 40 },
  },
  {
    id: "disaster-23",
    department: "बिपद व्यवस्थापन विभाग",
    sector: "Disaster Management",
    subSector: "Post Disaster Recovery",
    thematicArea: "recovery",
    mainProgram: "Recovery & Rehabilitation Program",
    programName: "Infrastructure Repair",
    budget: 5900000,
    budgetCode: "DM-023",
    sdg: { direct: ["11.5"], indirect: ["1.5"] },
    linkageScores: { sdgScore: 4, isoScore: 3, sciScore: 4, linkageType: "concurrence" },
    projectPhase: { phase: "recovery", progress: 45 },
  },
  {
    id: "disaster-24",
    department: "बिपद व्यवस्थापन विभाग",
    sector: "Disaster Management",
    subSector: "Post Disaster Recovery",
    thematicArea: "recovery",
    mainProgram: "Recovery & Rehabilitation Program",
    programName: "Livelihood Restoration",
    budget: 6100000,
    budgetCode: "DM-024",
    sdg: { direct: ["11.5"], indirect: ["1.5"] },
    linkageScores: { sdgScore: 4, isoScore: 3, sciScore: 4, linkageType: "concurrence" },
    projectPhase: { phase: "recovery", progress: 50 },
  },
  {
    id: "disaster-25",
    department: "बिपद व्यवस्थापन विभाग",
    sector: "Disaster Management",
    subSector: "Post Disaster Recovery",
    thematicArea: "recovery",
    mainProgram: "Recovery & Rehabilitation Program",
    programName: "School Reconstruction",
    budget: 6300000,
    budgetCode: "DM-025",
    sdg: { direct: ["11.5"], indirect: ["1.5"] },
    linkageScores: { sdgScore: 4, isoScore: 3, sciScore: 4, linkageType: "concurrence" },
    projectPhase: { phase: "recovery", progress: 55 },
  },
  {
    id: "disaster-26",
    department: "बिपद व्यवस्थापन विभाग",
    sector: "Disaster Management",
    subSector: "Post Disaster Recovery",
    thematicArea: "recovery",
    mainProgram: "Recovery & Rehabilitation Program",
    programName: "Health Facility Restoration",
    budget: 6500000,
    budgetCode: "DM-026",
    sdg: { direct: ["11.5"], indirect: ["1.5"] },
    linkageScores: { sdgScore: 4, isoScore: 3, sciScore: 4, linkageType: "concurrence" },
    projectPhase: { phase: "recovery", progress: 60 },
  },
  {
    id: "disaster-27",
    department: "बिपद व्यवस्थापन विभाग",
    sector: "Disaster Management",
    subSector: "Post Disaster Recovery",
    thematicArea: "recovery",
    mainProgram: "Recovery & Rehabilitation Program",
    programName: "Road & Bridge Repair",
    budget: 6700000,
    budgetCode: "DM-027",
    sdg: { direct: ["11.5"], indirect: ["1.5"] },
    linkageScores: { sdgScore: 4, isoScore: 3, sciScore: 4, linkageType: "concurrence" },
    projectPhase: { phase: "recovery", progress: 65 },
  },
  {
    id: "disaster-28",
    department: "बिपद व्यवस्थापन विभाग",
    sector: "Disaster Management",
    subSector: "Post Disaster Recovery",
    thematicArea: "recovery",
    mainProgram: "Recovery & Rehabilitation Program",
    programName: "Water Supply Restoration",
    budget: 6900000,
    budgetCode: "DM-028",
    sdg: { direct: ["11.5"], indirect: ["1.5"] },
    linkageScores: { sdgScore: 4, isoScore: 3, sciScore: 4, linkageType: "concurrence" },
    projectPhase: { phase: "recovery", progress: 70 },
  },
  {
    id: "disaster-29",
    department: "बिपद व्यवस्थापन विभाग",
    sector: "Disaster Management",
    subSector: "Post Disaster Recovery",
    thematicArea: "recovery",
    mainProgram: "Recovery & Rehabilitation Program",
    programName: "Public Building Repair",
    budget: 7100000,
    budgetCode: "DM-029",
    sdg: { direct: ["11.5"], indirect: ["1.5"] },
    linkageScores: { sdgScore: 4, isoScore: 3, sciScore: 4, linkageType: "concurrence" },
    projectPhase: { phase: "recovery", progress: 75 },
  },
  {
    id: "disaster-30",
    department: "बिपद व्यवस्थापन विभाग",
    sector: "Disaster Management",
    subSector: "Post Disaster Recovery",
    thematicArea: "recovery",
    mainProgram: "Recovery & Rehabilitation Program",
    programName: "Community Rehabilitation",
    budget: 7300000,
    budgetCode: "DM-030",
    sdg: { direct: ["11.5"], indirect: ["1.5"] },
    linkageScores: { sdgScore: 4, isoScore: 3, sciScore: 4, linkageType: "concurrence" },
    projectPhase: { phase: "recovery", progress: 80 },
  },

  // -------- Mitigation (31–42)
  {
    id: "disaster-31",
    department: "बिपद व्यवस्थापन विभाग",
    sector: "Disaster Management",
    subSector: "Risk Mitigation",
    thematicArea: "mitigation",
    mainProgram: "Risk Reduction Program",
    programName: "Flood Control Structures",
    budget: 3500000,
    budgetCode: "DM-031",
    sdg: { direct: ["13.2"], indirect: ["9.1"] },
    linkageScores: { sdgScore: 4, isoScore: 3, sciScore: 5, linkageType: "concurrence" },
    projectPhase: { phase: "implementation", progress: 30 },
  },
  {
    id: "disaster-32",
    department: "बिपद व्यवस्थापन विभाग",
    sector: "Disaster Management",
    subSector: "Risk Mitigation",
    thematicArea: "mitigation",
    mainProgram: "Risk Reduction Program",
    programName: "Landslide Prevention",
    budget: 3650000,
    budgetCode: "DM-032",
    sdg: { direct: ["13.2"], indirect: ["9.1"] },
    linkageScores: { sdgScore: 4, isoScore: 3, sciScore: 5, linkageType: "concurrence" },
    projectPhase: { phase: "implementation", progress: 35 },
  },
  {
    id: "disaster-33",
    department: "बिपद व्यवस्थापन विभाग",
    sector: "Disaster Management",
    subSector: "Risk Mitigation",
    thematicArea: "mitigation",
    mainProgram: "Risk Reduction Program",
    programName: "River Embankment",
    budget: 3800000,
    budgetCode: "DM-033",
    sdg: { direct: ["13.2"], indirect: ["9.1"] },
    linkageScores: { sdgScore: 4, isoScore: 3, sciScore: 5, linkageType: "concurrence" },
    projectPhase: { phase: "implementation", progress: 40 },
  },
  {
    id: "disaster-34",
    department: "बिपद व्यवस्थापन विभाग",
    sector: "Disaster Management",
    subSector: "Risk Mitigation",
    thematicArea: "mitigation",
    mainProgram: "Risk Reduction Program",
    programName: "Earthquake Resistant Design",
    budget: 3950000,
    budgetCode: "DM-034",
    sdg: { direct: ["13.2"], indirect: ["9.1"] },
    linkageScores: { sdgScore: 4, isoScore: 3, sciScore: 5, linkageType: "concurrence" },
    projectPhase: { phase: "implementation", progress: 45 },
  },
  {
    id: "disaster-35",
    department: "बिपद व्यवस्थापन विभाग",
    sector: "Disaster Management",
    subSector: "Risk Mitigation",
    thematicArea: "mitigation",
    mainProgram: "Risk Reduction Program",
    programName: "Urban Drainage Improvement",
    budget: 4100000,
    budgetCode: "DM-035",
    sdg: { direct: ["13.2"], indirect: ["9.1"] },
    linkageScores: { sdgScore: 4, isoScore: 3, sciScore: 5, linkageType: "concurrence" },
    projectPhase: { phase: "implementation", progress: 50 },
  },
  {
    id: "disaster-36",
    department: "बिपद व्यवस्थापन विभाग",
    sector: "Disaster Management",
    subSector: "Risk Mitigation",
    thematicArea: "mitigation",
    mainProgram: "Risk Reduction Program",
    programName: "Slope Stabilization",
    budget: 4250000,
    budgetCode: "DM-036",
    sdg: { direct: ["13.2"], indirect: ["9.1"] },
    linkageScores: { sdgScore: 4, isoScore: 3, sciScore: 5, linkageType: "concurrence" },
    projectPhase: { phase: "implementation", progress: 55 },
  },
  {
    id: "disaster-37",
    department: "बिपद व्यवस्थापन विभाग",
    sector: "Disaster Management",
    subSector: "Risk Mitigation",
    thematicArea: "mitigation",
    mainProgram: "Risk Reduction Program",
    programName: "Building Retrofitting",
    budget: 4400000,
    budgetCode: "DM-037",
    sdg: { direct: ["13.2"], indirect: ["9.1"] },
    linkageScores: { sdgScore: 4, isoScore: 3, sciScore: 5, linkageType: "concurrence" },
    projectPhase: { phase: "implementation", progress: 60 },
  },
  {
    id: "disaster-38",
    department: "बिपद व्यवस्थापन विभाग",
    sector: "Disaster Management",
    subSector: "Risk Mitigation",
    thematicArea: "mitigation",
    mainProgram: "Risk Reduction Program",
    programName: "Open Space Development",
    budget: 4550000,
    budgetCode: "DM-038",
    sdg: { direct: ["13.2"], indirect: ["9.1"] },
    linkageScores: { sdgScore: 4, isoScore: 3, sciScore: 5, linkageType: "concurrence" },
    projectPhase: { phase: "implementation", progress: 65 },
  },
  {
    id: "disaster-39",
    department: "बिपद व्यवस्थापन विभाग",
    sector: "Disaster Management",
    subSector: "Risk Mitigation",
    thematicArea: "mitigation",
    mainProgram: "Risk Reduction Program",
    programName: "Urban Green Buffer Zones",
    budget: 4700000,
    budgetCode: "DM-039",
    sdg: { direct: ["13.2"], indirect: ["9.1"] },
    linkageScores: { sdgScore: 4, isoScore: 3, sciScore: 5, linkageType: "concurrence" },
    projectPhase: { phase: "implementation", progress: 70 },
  },
  {
    id: "disaster-40",
    department: "बिपद व्यवस्थापन विभाग",
    sector: "Disaster Management",
    subSector: "Risk Mitigation",
    thematicArea: "mitigation",
    mainProgram: "Risk Reduction Program",
    programName: "Seismic Risk Mapping",
    budget: 4850000,
    budgetCode: "DM-040",
    sdg: { direct: ["13.2"], indirect: ["9.1"] },
    linkageScores: { sdgScore: 4, isoScore: 3, sciScore: 5, linkageType: "concurrence" },
    projectPhase: { phase: "implementation", progress: 75 },
  },
  {
    id: "disaster-41",
    department: "बिपद व्यवस्थापन विभाग",
    sector: "Disaster Management",
    subSector: "Risk Mitigation",
    thematicArea: "mitigation",
    mainProgram: "Risk Reduction Program",
    programName: "Climate Adaptation Measures",
    budget: 5000000,
    budgetCode: "DM-041",
    sdg: { direct: ["13.2"], indirect: ["9.1"] },
    linkageScores: { sdgScore: 4, isoScore: 3, sciScore: 5, linkageType: "concurrence" },
    projectPhase: { phase: "implementation", progress: 80 },
  },
  {
    id: "disaster-42",
    department: "बिपद व्यवस्थापन विभाग",
    sector: "Disaster Management",
    subSector: "Risk Mitigation",
    thematicArea: "mitigation",
    mainProgram: "Risk Reduction Program",
    programName: "Urban Resilience Strengthening",
    budget: 5200000,
    budgetCode: "DM-042",
    sdg: { direct: ["13.2"], indirect: ["9.1"] },
    linkageScores: { sdgScore: 4, isoScore: 3, sciScore: 5, linkageType: "concurrence" },
    projectPhase: { phase: "implementation", progress: 85 },
  },
]
