


export interface DisasterDepartment {
  id: string
  department: string
  sector: string
  subSector: string
  mainProgram: string
  programName: string
  budget: number
  budgetCode: string
  sdg: {
    direct: string
    indirect: string
  }
  iso37120: {
    direct: string
    indirect: string
  }
  sci2025: {
    direct: string
    indirect: string
  }
  thematicArea: string
  cycle: string
  linkageScores: {
    sdgScore: number
    isoScore: number
    sciScore: number
    linkageType: "research" | "discussion" | "concurrence" | "declaration"
  }
  projectPhase: {
    phase: "inception" | "approval" | "tender" | "award" | "completion"
    progress: number
  }
}

export const thematicAreas = [
    {
    id: "preparedness-risk-reduction",
    name: "Disaster Preparedness & Risk Reduction",
    nameNp: "विपद् तयारी तथा जोखिम न्यूनीकरण",
    color: "#EF4444",
    icon :" Heart",
    standards: {
      sdg: ["SDG 11.5", "SDG 13.1"],
      iso: ["ISO 37120:6.1"],
      sci: ["Pillar 1 - Disaster Risk Reduction"],
    },
  },
  {
    id: "emergency-response",
    name: "Emergency Response & Relief",
    nameNp: "आपतकालीन प्रतिकार्य तथा राहत",
    color: "#F97316",
    standards: {
      sdg: ["SDG 3.d", "SDG 11.b"],
      iso: ["ISO 37120:6.2"],
      sci: ["Pillar 2 - Emergency Management"],
    },
  },
  {
    id: "recovery-reconstruction",
    name: "Recovery & Reconstruction",
    nameNp: "पुनःस्थापना तथा पुनर्निर्माण",
    color: "#10B981",
    standards: {
      sdg: ["SDG 9.1", "SDG 11.c"],
      iso: ["ISO 37120:6.3"],
      sci: ["Pillar 3 - Resilient Infrastructure"],
    },
  },
  {
    id: "capacity-awareness",
    name: "Capacity Building & Awareness",
    nameNp: "क्षमता विकास तथा जनचेतना",
    color: "#3B82F6",
    standards:{
      sdg: ["SDG 11.b"],
      iso: ["ISO 37120:6.4"],
      sci: ["Pillar 4 - Human Capital Development"],
    },
  },
  {
    id: "governance-coordination",
    name: "Governance & Coordination",
    nameNp: "सुशासन तथा समन्वय",
    color: "#8B5CF6",
    standards: {
      sdg: ["SDG 16.6"],
      iso: ["ISO 37120:6.5"],
      sci: ["Pillar 2 - Smart Governance"],
    },
  },
]

// Define linkage types
export const linkageTypes = [
  { value: "declaration", label: "Declaration", score: 1, description: "Official policy declaration without verification" },
  { value: "discussion", label: "Discussion", score: 2, description: "Discussed in meetings/workshops" },
  { value: "concurrence", label: "Concurrence", score: 3, description: "Agreed upon by multiple stakeholders" },
  { value: "research", label: "Research", score: 4, description: "Backed by research and evidence" },
]

// Project phases
export const projectPhases = [
  { value: "inception", label: "Inception", rangeStart: 0, rangeEnd: 20 },
  { value: "approval", label: "Approval", rangeStart: 21, rangeEnd: 40 },
  { value: "tender", label: "Tender", rangeStart: 41, rangeEnd: 60 },
  { value: "award", label: "Award", rangeStart: 61, rangeEnd: 80 },
  { value: "completion", label: "Completion", rangeStart: 81, rangeEnd: 100 },
]

// Helper function to generate random phase progress
function generateProjectPhase(): { phase: "inception" | "approval" | "tender" | "award" | "completion"; progress: number } {
  const phases: ("inception" | "approval" | "tender" | "award" | "completion")[] = ["inception", "approval", "tender", "award", "completion"]
  const weights = [0.15, 0.2, 0.25, 0.25, 0.15]

  let random = Math.random()
  let phaseIndex = 0
  for (let i = 0; i < weights.length; i++) {
    random -= weights[i]
    if (random <= 0) {
      phaseIndex = i
      break
    }
  }

  const phase = phases[phaseIndex]
  const phaseRanges: Record<string, [number, number]> = {
    inception: [25, 20],
    approval: [25, 40],
    tender: [45, 60],
    award: [65, 80],
    completion: [70, 100],
  }

  const [min, max] = phaseRanges[phase]
  const progress = Math.floor(Math.random() * (max - min + 1)) + min
  return { phase, progress }
}

export const disasterPrograms: DisasterDepartment[] = [
  {
    id: "1",
    department: "बिपद व्यवस्थापन विभाग",
    sector: "सुशासन तथा अन्तरसम्बन्धित क्षेत्र",
    subSector: "विपद व्यवस्थापन",
    mainProgram: "विविध",
    programName: "विपद् व्यवस्थापन कार्यमा खटिने उत्कृष्ट कर्मचारी नगद पुरस्कार तथा सम्मानपत्र खर्च (५ जना)",
    budget: 300000,
    budgetCode: "21135",
    sdg: { direct: "11.b.1", indirect: "NO" },
    iso37120: { direct: "7.EM (Emergency Management)", indirect: "NO" },
    sci2025: { direct: "pillar no=3 componentno=3.2 I-042", indirect: "" },
    thematicArea: "capacity-awareness",
    cycle: "",
    linkageScores: { sdgScore: 4, isoScore: 3, sciScore: 4, linkageType: "concurrence" },
    projectPhase: generateProjectPhase(),
  },
  {
    id: "2",
    department: "बिपद व्यवस्थापन विभाग",
    sector: "सुशासन तथा अन्तरसम्बन्धित क्षेत्र",
    subSector: "विपद व्यवस्थापन",
    mainProgram: "विविध",
    programName: "विपद् व्यवस्थापन कार्यमा खटिने उत्कृष्ट नागरिक/महानगरवासी नगद पुरस्कार तथा सम्मान कार्यक्रम खर्च",
    budget: 500000,
    budgetCode: "21135",
    sdg: { direct: "11.b.1", indirect: "NO" },
    iso37120: { direct: "7.EM (Emergency Management)", indirect: "NO" },
    sci2025: { direct: "pillar no=3 componentno=3.2 I-042", indirect: "" },
    thematicArea: "capacity-awareness",
    cycle: "",
    linkageScores: { sdgScore: 4, isoScore: 3, sciScore: 4, linkageType: "research" },
    projectPhase: generateProjectPhase(),
  },
  {
    id: "3",
    department: "बिपद व्यवस्थापन विभाग",
    sector: "सुशासन तथा अन्तरसम्बन्धित क्षेत्र",
    subSector: "विपद व्यवस्थापन",
    mainProgram: "विविध",
    programName: "विपद् व्यवस्थापनमा खटिने कर्मचारीहरुको बिमा, औषधोपचार, जोखिम भत्ता",
    budget: 15000000,
    budgetCode: "21135",
    sdg: { direct: "11.5.1", indirect: "NO" },
    iso37120: { direct: "7.EM (Emergency Management)", indirect: "NO" },
    sci2025: { direct: "pillar no=3 componentno=3.1 I-040", indirect: "" },
    thematicArea: "preparedness-risk-reduction",
    cycle: "",
    linkageScores: { sdgScore: 4, isoScore: 3, sciScore: 4, linkageType: "research" },
    projectPhase: generateProjectPhase(),
  },
  {
    id: "4",
    department: "बिपद व्यवस्थापन विभाग",
    sector: "सुशासन तथा अन्तरसम्बन्धित क्षेत्र",
    subSector: "विपद व्यवस्थापन",
    mainProgram: "बारुण यन्त्र खरिद तथा मर्मत कार्यक्रम",
    programName: "Fire Extinguisher Refilling तथा मर्मत",
    budget: 1000000,
    budgetCode: "22113",
    sdg: { direct: "11.5.2", indirect: "NO" },
    iso37120: { direct: "7.EM (Emergency Management)", indirect: "NO" },
    sci2025: { direct: "pillar no=3 componentno=3.3 I-045", indirect: "" },
    thematicArea: "preparedness-risk-reduction",
    cycle: "",
    linkageScores: { sdgScore: 4, isoScore: 3, sciScore: 4, linkageType: "declaration"},
    projectPhase: generateProjectPhase(),
  },
  {
    id: "5",
    department: "बिपद व्यवस्थापन विभाग",
    sector: "सुशासन तथा अन्तरसम्बन्धित क्षेत्र",
    subSector: "विपद व्यवस्थापन",
    mainProgram: "बारुण यन्त्र खरिद तथा मर्मत कार्यक्रम",
    programName: "Dry Riser Pipe मर्मत",
    budget: 2500000,
    budgetCode: "22291",
    sdg: { direct: "11.5.2", indirect: "NO" },
    iso37120: { direct: "7.EM (Emergency Management)", indirect: "NO" },
    sci2025: { direct: "pillar no=3 componentno=3.3 I-045", indirect: "" },
    thematicArea: "preparedness-risk-reduction",
    cycle: "",
    linkageScores: { sdgScore: 4, isoScore: 3, sciScore: 4, linkageType: "discussion" },
    projectPhase: generateProjectPhase(),
  },
  {
    id: "6",
    department: "बिपद व्यवस्थापन विभाग",
    sector: "सुशासन तथा अन्तरसम्बन्धित क्षेत्र",
    subSector: "विपद व्यवस्थापन",
    mainProgram: "विविध",
    programName: "अन्तराष्ट्रियस्तरबाट प्राप्त विपद् व्यवस्थापन सामग्रीहरु प्राप्त गर्दा लाग्ने शुल्क, दस्तुर, कर, ढुवानी शुल्क लगायत खर्च",
    budget: 500000,
    budgetCode: "22419",
    sdg: { direct: "11.b.2", indirect: "NO" },
    iso37120: { direct: "7.EM (Emergency Management)", indirect: "NO" },
    sci2025: { direct: "pillar no=3 componentno=3.2 I-043", indirect: "" },
    thematicArea: "preparedness-risk-reduction",
    cycle: "",
    linkageScores: { sdgScore: 4, isoScore: 3, sciScore: 4, linkageType: "concurrence" },
    projectPhase: generateProjectPhase(),
  },
  {
    id: "7",
    department: "बिपद व्यवस्थापन विभाग",
    sector: "सुशासन तथा अन्तरसम्बन्धित क्षेत्र",
    subSector: "विपद व्यवस्थापन",
    mainProgram: "स्थानीय स्तर विपद् पूर्व तयारी तथा प्रतिकार्य कार्यक्रम",
    programName: "विपद् व्यवस्थापनका लागि तालिम",
    budget: 500000,
    budgetCode: "22512",
    sdg: { direct: "11.b.1", indirect: "NO" },
    iso37120: { direct: "7.EM (Emergency Management)", indirect: "NO" },
    sci2025: { direct: "pillar no=3 componentno=3.1 I-041", indirect: "" },
    thematicArea: "capacity-awareness",
    cycle: "",
    linkageScores: { sdgScore: 4, isoScore: 3, sciScore: 4, linkageType: "concurrence" },
    projectPhase: generateProjectPhase(),
  },
  {
    id: "8",
    department: "बिपद व्यवस्थापन विभाग",
    sector: "सुशासन तथा अन्तरसम्बन्धित क्षेत्र",
    subSector: "विपद व्यवस्थापन",
    mainProgram: "स्थानीय स्तर विपद् पूर्व तयारी तथा प्रतिकार्य कार्यक्रम",
    programName: "विपद् व्यवस्थापनका लागि कर्मचारी तालिम",
    budget: 500000,
    budgetCode: "22511",
    sdg: { direct: "11.b.1", indirect: "NO" },
    iso37120: { direct: "7.EM (Emergency Management)", indirect: "NO" },
    sci2025: { direct: "pillar no=3 componentno=3.1 I-041", indirect: "" },
    thematicArea: "capacity-awareness",
    cycle: "",
    linkageScores: { sdgScore: 4, isoScore: 3, sciScore: 4, linkageType: "concurrence" },
    projectPhase: generateProjectPhase(),
  },
  {
    id: "9",
    department: "बिपद व्यवस्थापन विभाग",
    sector: "सुशासन तथा अन्तरसम्बन्धित क्षेत्र",
    subSector: "विपद व्यवस्थापन",
    mainProgram: "विविध",
    programName: "भू-कम्प स्मृति सभा खर्च (माघ २ गते)",
    budget: 500000,
    budgetCode: "22522",
    sdg: { direct: "11.5.1", indirect: "NO" },
    iso37120: { direct: "7.EM (Emergency Management)", indirect: "NO" },
    sci2025: { direct: "pillar no=3 componentno=3.4 I-048", indirect: "" },
    thematicArea: "governance-coordination",
    cycle: "",
    linkageScores: { sdgScore: 4, isoScore: 3, sciScore: 4, linkageType: "concurrence" },
    projectPhase: generateProjectPhase(),
  },
  {
    id: "10",
    department: "बिपद व्यवस्थापन विभाग",
    sector: "सुशासन तथा अन्तरसम्बन्धित क्षेत्र",
    subSector: "विपद व्यवस्थापन",
    mainProgram: "विविध",
    programName: "भू-कम्प स्मृति दिवस खर्च (माघ २ र बैशाख १२ गते)",
    budget: 500000,
    budgetCode: "22522",
    sdg: { direct: "11.5.1", indirect: "NO" },
    iso37120: { direct: "7.EM (Emergency Management)", indirect: "NO" },
    sci2025: { direct: "pillar no=3 componentno=3.4 I-048", indirect: "" },
    thematicArea: "governance-coordination",
    cycle: "",
    linkageScores: { sdgScore: 4, isoScore: 3, sciScore: 4, linkageType: "concurrence" },
    projectPhase: generateProjectPhase(),
  },
  {
    id: "11",
    department: "बिपद व्यवस्थापन विभाग",
    sector: "सुशासन तथा अन्तरसम्बन्धित क्षेत्र",
    subSector: "विपद व्यवस्थापन",
    mainProgram: "स्थानीय स्तर विपद् पूर्व तयारी तथा प्रतिकार्य कार्यक्रम",
    programName: "विपद् सचेतना कार्यक्रम अन्तरक्रिया समेत",
    budget: 500000,
    budgetCode: "DM-011",
    sdg: { direct: "11.5", indirect: "3.d" },
    iso37120: { direct: "7.EM (Emergency Management)", indirect: "5.HEA (Health emergency preparedness)" },
    sci2025: { direct: "pillar no=3 componentno=3.1 I-041", indirect: "" },
    thematicArea: "capacity-awareness",
    cycle: "",
    linkageScores: { sdgScore: 5, isoScore: 4, sciScore: 5, linkageType: "concurrence" },
    projectPhase: generateProjectPhase(),
  },
  {
    id: "12",
    department: "बिपद व्यवस्थापन विभाग",
    sector: "सुशासन तथा अन्तरसम्बन्धित क्षेत्र",
    subSector: "विपद व्यवस्थापन",
    mainProgram: "विविध",
    programName: "विपद् व्यवस्थापन समितिका पदाधिकारी तथा कर्मचारीहरुको लागि अवलोकन भ्रमण कार्यक्रम",
    budget: 500000,
    budgetCode: "22522",
    sdg: { direct: "11.b.2", indirect: "NO" },
    iso37120: { direct: "7.EM (Emergency Management)", indirect: "NO" },
    sci2025: { direct: "pillar no=3 componentno=3.2 I-043", indirect: "" },
    thematicArea: "capacity-awareness",
    cycle: "",
    linkageScores: { sdgScore: 5, isoScore: 4, sciScore: 5, linkageType: "concurrence" },
    projectPhase: generateProjectPhase(),
  },
  {
    id: "13",
    department: "बिपद व्यवस्थापन विभाग",
    sector: "सुशासन तथा अन्तरसम्बन्धित क्षेत्र",
    subSector: "विपद व्यवस्थापन",
    mainProgram: "स्थानीय स्तर विपद् पूर्व तयारी तथा प्रतिकार्य कार्यक्रम",
    programName: "आगलागी नियन्त्रण सचेतना कार्यक्रम",
    budget: 500000,
    budgetCode: "22522",
    sdg: { direct: "11.b.2", indirect: "NO" },
    iso37120: { direct: "7.EM (Emergency Management)", indirect: "NO" },
    sci2025: { direct: "pillar no=3 componentno=3.3 I-045", indirect: "" },
    thematicArea: "emergency-response",
    cycle: "",
    linkageScores: { sdgScore: 5, isoScore: 4, sciScore: 5, linkageType: "concurrence" },
    projectPhase: generateProjectPhase(),
  },
  {
    id: "14",
    department: "बिपद व्यवस्थापन विभाग",
    sector: "सुशासन तथा अन्तरसम्बन्धित क्षेत्र",
    subSector: "विपद व्यवस्थापन",
    mainProgram: "विविध",
    programName: "विपद् व्यवस्थापन सम्बन्धी राष्ट्रिय तथा अन्तराष्ट्रिय निकायहरुसंग सहकार्य",
    budget: 500000,
    budgetCode: "22522",
    sdg: { direct: "11.b.2", indirect: "NO" },
    iso37120: { direct: "7.EM (Emergency Management)", indirect: "17.PPP (Partnerships)" },
    sci2025: { direct: "pillar no=4 componentno=4.2 I-060", indirect: "" },
    thematicArea: "governance-coordination",
    cycle: "",
    linkageScores: { sdgScore: 5, isoScore: 4, sciScore: 5, linkageType: "concurrence" },
    projectPhase: generateProjectPhase(),
  },
  {
    id: "15",
    department: "बिपद व्यवस्थापन विभाग",
    sector: "सुशासन तथा अन्तरसम्बन्धित क्षेत्र",
    subSector: "स्थानीय स्तर विपद् पूर्व तयारी तथा प्रतिकार्य कार्यक्रम",
    mainProgram: "विपद् पूर्व तयारी",
    programName: "वडा विपद् प्रतिकार्य तालीम तथा Simulation Drill सचालन खर्च",
    budget: 1000000,
    budgetCode: "22522",
    sdg: { direct: "11.b.1", indirect: "NO" },
    iso37120: { direct: "7.EM (Emergency drills & preparedness)", indirect: "NO" },
    sci2025: { direct: "pillar no=3 componentno=3.1 I-041", indirect: "" },
    thematicArea: "emergency-response",
    cycle: "",
    linkageScores: { sdgScore: 5, isoScore: 4, sciScore: 5, linkageType: "concurrence" },
    projectPhase: generateProjectPhase(),
  },
  {
    id: "16",
    department: "बिपद व्यवस्थापन विभाग",
    sector: "सुशासन तथा अन्तरसम्बन्धित क्षेत्र",
    subSector: "स्थानीय स्तर विपद् पूर्व तयारी तथा प्रतिकार्य कार्यक्रम",
    mainProgram: "विपद् पूर्व तयारी",
    programName: "विद्धार्थीहरुका लागि विपद् व्यवस्थापन सम्बन्धित स्रोत सामग्री तयारी खर्च",
    budget: 1000000,
    budgetCode: "22522",
    sdg: { direct: "11.b.2", indirect: "4.7" },
    iso37120: { direct: "7.EM (Emergency education & awareness)", indirect: "6.EDU" },
    sci2025: { direct: "pillar no=2 componentno=2.4 I-024", indirect: "" },
    thematicArea: "capacity-awareness",
    cycle: "",
    linkageScores: { sdgScore: 5, isoScore: 4, sciScore: 5, linkageType: "concurrence" },
    projectPhase: generateProjectPhase(),
  },
  {
    id: "17",
    department: "बिपद व्यवस्थापन विभाग",
    sector: "सुशासन तथा अन्तरसम्बन्धित क्षेत्र",
    subSector: "विपद व्यवस्थापन",
    mainProgram: "विविध",
    programName: "वडा दशैं र चैते दशैंमा मौलो पुजा तथा चाडपर्व खर्च",
    budget: 500000,
    budgetCode: "22711",
    sdg: { direct: "11.4.1", indirect: "NO" },
    iso37120: { direct: "1.CUL (Culture)", indirect: "NO" },
    sci2025: { direct: "pillar no=5 componentno=5.1 I-070", indirect: "" },
    thematicArea: "governance-coordination",
    cycle: "",
    linkageScores: { sdgScore: 5, isoScore: 4, sciScore: 5, linkageType: "concurrence" },
    projectPhase: generateProjectPhase(),
  },
  {
    id: "18",
    department: "बिपद व्यवस्थापन विभाग",
    sector: "सुशासन तथा अन्तरसम्बन्धित क्षेत्र",
    subSector: "विपद् पूर्व तयारी, खोज तथा उद्धार, राहत सामाग्रीको पूर्व भण्डारण कार्यक्रम",
    mainProgram: "विपद् पूर्व तयारी",
    programName: "त्रिपाल खरिद",
    budget: 1000000,
    budgetCode: "27212",
    sdg: { direct: "11.5.2", indirect: "NO" },
    iso37120: { direct: "7.EM (Relief stockpiling)", indirect: "NO" },
    sci2025: { direct: "pillar no=3 componentno=3.4 I-048", indirect: "" },
    thematicArea: "preparedness-risk-reduction",
    cycle: "",
    linkageScores: { sdgScore: 5, isoScore: 4, sciScore: 5, linkageType: "concurrence" },
    projectPhase: generateProjectPhase(),
  },
  {
    id: "19",
    department: "बिपद व्यवस्थापन विभाग",
    sector: "सुशासन तथा अन्तरसम्बन्धित क्षेत्र",
    subSector: "विपद् पूर्व तयारी, खोज तथा उद्धार, राहत सामाग्रीको पूर्व भण्डारण कार्यक्रम",
    mainProgram: "विपद् पूर्व तयारी",
    programName: "ब्ल्याङ्केट खरिद",
    budget: 1000000,
    budgetCode: "27212",
    sdg: { direct: "11.5.2", indirect: "NO" },
    iso37120: { direct: "7.EM (Relief stockpiling)", indirect: "NO" },
    sci2025: { direct: "pillar no=3 componentno=3.4 I-048", indirect: "" },
    thematicArea: "preparedness-risk-reduction",
    cycle: "",
    linkageScores: { sdgScore: 5, isoScore: 4, sciScore: 5, linkageType: "concurrence" },
    projectPhase: generateProjectPhase(),
  },
  {
    id: "20",
    department: "बिपद व्यवस्थापन विभाग",
    sector: "सुशासन तथा अन्तरसम्बन्धित क्षेत्र",
    subSector: "विपद् कोष स्थापना तथा सञ्चालन कार्यक्रम",
    mainProgram: "विपद् कोष",
    programName: "विपद् व्यवस्थापन कोष",
    budget: 20000000,
    budgetCode: "27212",
    sdg: { direct: "11.5.2", indirect: "1.5" },
    iso37120: { direct: "7.EM (Disaster financing & resilience)", indirect: "NO" },
    sci2025: { direct: "pillar no=3 componentno=3.5 I-050", indirect: "" },
    thematicArea: "preparedness-risk-reduction",
    cycle: "",
    linkageScores: { sdgScore: 5, isoScore: 4, sciScore: 5, linkageType: "concurrence" },
    projectPhase: generateProjectPhase(),
  },
  {
    id: "21",
    department: "बिपद व्यवस्थापन विभाग",
    sector: "सुशासन तथा अन्तरसम्बन्धित क्षेत्र",
    subSector: "बारुण यन्त्र खरिद तथा मर्मत कार्यक्रम",
    mainProgram: "बारुण यन्त्र खरिद",
    programName: "Search and Rescue (SR) सवारी साधन खरिद",
    budget: 6000000,
    budgetCode: "31121",
    sdg: { direct: "11.5.1", indirect: "NO" },
    iso37120: { direct: "7.EM (Emergency response vehicles)", indirect: "NO" },
    sci2025: { direct: "pillar no=3 componentno=3.3 I-045", indirect: "" },
    thematicArea: "recovery-reconstruction",
    cycle: "",
    linkageScores: { sdgScore: 4, isoScore: 3, sciScore: 4, linkageType: "concurrence" },
    projectPhase: generateProjectPhase(),
  },
  {
    id: "22",
    department: "बिपद व्यवस्थापन विभाग",
    sector: "सुशासन तथा अन्तरसम्बन्धित क्षेत्र",
    subSector: "बारुण यन्त्र खरिद तथा मर्मत कार्यक्रम",
    mainProgram: "बारुण यन्त्र खरिद",
    programName: "अग्नी नियन्त्रणको लागि ल्याडर खरिद",
    budget: 50000000,
    budgetCode: "31121",
    sdg: { direct: "11.5.2", indirect: "NO" },
    iso37120: { direct: "7.EM (Fire service infrastructure)", indirect: "NO" },
    sci2025: { direct: "pillar no=3 componentno=3.3 I-046", indirect: "" },
    thematicArea: "recovery-reconstruction",
    cycle: "",
    linkageScores: { sdgScore: 4, isoScore: 3, sciScore: 4, linkageType: "concurrence" },
    projectPhase: generateProjectPhase(),
  },
  {
    id: "23",
    department: "बिपद व्यवस्थापन विभाग",
    sector: "सुशासन तथा अन्तरसम्बन्धित क्षेत्र",
    subSector: "बारुण यन्त्र खरिद तथा मर्मत कार्यक्रम",
    mainProgram: "बारुण यन्त्र खरिद",
    programName: "बारुणयन्त्र (दमकल) खरिद",
    budget: 130000000,
    budgetCode: "31121",
    sdg: { direct: "11.5.2", indirect: "NO" },
    iso37120: { direct: "7.EM (Fire trucks & emergency fleet)", indirect: "NO" },
    sci2025: { direct: "pillar no=3 componentno=3.3 I-046", indirect: "" },
    thematicArea: "recovery-reconstruction",
    cycle: "",
    linkageScores: { sdgScore: 4, isoScore: 3, sciScore: 4, linkageType: "concurrence" },
    projectPhase: generateProjectPhase(),
  },
  {
    id: "24",
    department: "बिपद व्यवस्थापन विभाग",
    sector: "सुशासन तथा अन्तरसम्बन्धित क्षेत्र",
    subSector: "स्थानीय स्तर विपद् पूर्व तयारी तथा प्रतिकार्य कार्यक्रम",
    mainProgram: "विपद् पूर्व तयारी",
    programName: "बाढीवाट उद्धारको लागि प्रयोग हुने डुङ्गा खरिद",
    budget: 1000000,
    budgetCode: "31122",
    sdg: { direct: "11.5.1", indirect: "NO" },
    iso37120: { direct: "7.EM (Flood rescue equipment)", indirect: "NO" },
    sci2025: { direct: "pillar no=3 componentno=3.4 I-048", indirect: "" },
    thematicArea: "recovery-reconstruction",
    cycle: "",
    linkageScores: { sdgScore: 4, isoScore: 3, sciScore: 4, linkageType: "concurrence" },
    projectPhase: generateProjectPhase(),
  },
  {
    id: "25",
    department: "बिपद व्यवस्थापन विभाग",
    sector: "सुशासन तथा अन्तरसम्बन्धित क्षेत्र",
    subSector: "स्थानीय स्तर विपद् पूर्व तयारी तथा प्रतिकार्य कार्यक्रम",
    mainProgram: "विपद् पूर्व तयारी",
    programName: "Portable Light Tower",
    budget: 1000000,
    budgetCode: "31122",
    sdg: { direct: "11.5.2", indirect: "NO" },
    iso37120: { direct: "7.EM (Emergency lighting system)", indirect: "NO" },
    sci2025: { direct: "pillar no=3 componentno=3.3 I-047", indirect: "" },
    thematicArea: "recovery-reconstruction",
    cycle: "",
    linkageScores: { sdgScore: 4, isoScore: 3, sciScore: 4, linkageType: "concurrence" },
    projectPhase: generateProjectPhase(),
  },

{
  id: "26",
  department: "बिपद व्यवस्थापन विभाग",
  sector: "सुशासन तथा अन्तरसम्बन्धित क्षेत्र",
  subSector: "विपद व्यवस्थापन",
  mainProgram: "बारुण यन्त्र खरिद तथा मर्मत कार्यक्रम",
  programName: "Fire Extinguisher खरिद",
  budget: 1500000,
  budgetCode: "31122",
  sdg: { direct: "11.5.2", indirect: "NO" },
  iso37120: { direct: "7.EM (Fire safety equipment)", indirect: "NO" },
  sci2025: { direct: "pillar no=3 componentno=3.3 I-045", indirect: "" },
  thematicArea: "recovery-reconstruction",
  cycle: "",
  linkageScores: { sdgScore: 4, isoScore: 3, sciScore: 4, linkageType: "concurrence" },
  projectPhase: generateProjectPhase(),
},
  {
    id: "27",
    department: "बिपद व्यवस्थापन विभाग",
    sector: "सुशासन तथा अन्तरसम्बन्धित क्षेत्र",
    subSector: "विपद व्यवस्थापन",
    mainProgram: "स्थानीय स्तर विपद् पूर्व तयारी तथा प्रतिकार्य कार्यक्रम",
    programName: "Portable Generators",
    budget: 2000000,
    budgetCode: "31122",
    sdg: { direct: "11.5.2", indirect: "7.1" },
    iso37120: { direct: "7.EM (Backup power system)", indirect: "8.ENE" },
    sci2025: { direct: "pillar no=3 componentno=3.3 I-047", indirect: "" },
    thematicArea: "recovery-reconstruction",
    cycle: "",
    linkageScores: { sdgScore: 4, isoScore: 3, sciScore: 4, linkageType: "concurrence" },
    projectPhase: generateProjectPhase(),
  },
  {
    id: "28",
    department: "बिपद व्यवस्थापन विभाग",
    sector: "सुशासन तथा अन्तरसम्बन्धित क्षेत्र",
    subSector: "विपद व्यवस्थापन",
    mainProgram: "स्थानीय स्तर विपद् पूर्व तयारी तथा प्रतिकार्य कार्यक्रम",
    programName: "पानी तान्ने पम्प खरिद",
    budget: 2000000,
    budgetCode: "31122",
    sdg: { direct: "11.5.2", indirect: "6.5" },
    iso37120: { direct: "7.EM (Water pumping system)", indirect: "9.WAT" },
    sci2025: { direct: "pillar no=3 componentno=3.4 I-048", indirect: "" },
    thematicArea: "recovery-reconstruction",
    cycle: "",
    linkageScores: { sdgScore: 4, isoScore: 3, sciScore: 4, linkageType: "concurrence" },
    projectPhase: generateProjectPhase(),
  },
  {
    id: "29",
    department: "बिपद व्यवस्थापन विभाग",
    sector: "सुशासन तथा अन्तरसम्बन्धित क्षेत्र",
    subSector: "विपद व्यवस्थापन",
    mainProgram: "स्थानीय स्तर विपद् पूर्व तयारी तथा प्रतिकार्य कार्यक्रम",
    programName: "अग्नी नियन्त्रण पोशाक खरिद",
    budget: 3000000,
    budgetCode: "31122",
    sdg: { direct: "11.5.1", indirect: "8.8" },
    iso37120: { direct: "7.EM (Firefighter protective gear)", indirect: "NO" },
    sci2025: { direct: "pillar no=3 componentno=3.3 I-045", indirect: "" },
    thematicArea: "recovery-reconstruction",
    cycle: "",
    linkageScores: { sdgScore: 4, isoScore: 3, sciScore: 4, linkageType: "concurrence" },
    projectPhase: generateProjectPhase(),
  },
  {
    id: "30",
    department: "बिपद व्यवस्थापन विभाग",
    sector: "सुशासन तथा अन्तरसम्बन्धित क्षेत्र",
    subSector: "विपद व्यवस्थापन",
    mainProgram: "स्थानीय स्तर विपद् पूर्व तयारी तथा प्रतिकार्य कार्यक्रम",
    programName: "Search and Rescue (SR), Demolish Equipment खरिद",
    budget: 6000000,
    budgetCode: "31122",
    sdg: { direct: "11.5.1", indirect: "NO" },
    iso37120: { direct: "7.EM (Search & Rescue equipment)", indirect: "NO" },
    sci2025: { direct: "pillar no=3 componentno=3.3 I-046", indirect: "" },
    thematicArea: "recovery-reconstruction",
    cycle: "",
    linkageScores: { sdgScore: 4, isoScore: 3, sciScore: 4, linkageType: "concurrence" },
    projectPhase: generateProjectPhase(),
  },
  {
    id: "31",
    department: "बिपद व्यवस्थापन विभाग",
    sector: "सुशासन तथा अन्तरसम्बन्धित क्षेत्र",
    subSector: "विपद व्यवस्थापन",
    mainProgram: "बारुण यन्त्र सञ्चालन तथा सुदृढीकरण कार्यक्रम",
    programName: "दमकल भवनहरुमा पानी आपूर्ति",
    budget: 1000000,
    budgetCode: "31156",
    sdg: { direct: "Goal 11 / Target 11.c / Indicator 11.c.1", indirect: "No" },
    iso37120: { direct: "", indirect: "No" },
    sci2025: { direct: "", indirect: "" },
    thematicArea: "preparedness-risk-reduction",
    cycle: "",
    linkageScores: { sdgScore: 4, isoScore: 3, sciScore: 5, linkageType: "concurrence" },
    projectPhase: generateProjectPhase(),
  },
  {
    id: "32",
    department: "बिपद व्यवस्थापन विभाग",
    sector: "सुशासन तथा अन्तरसम्बन्धित क्षेत्र",
    subSector: "विपद व्यवस्थापन",
    mainProgram: "स्थानीय स्तर विपद् पूर्व तयारी तथा प्रतिकार्य कार्यक्रम",
    programName: "विपद जोखिमका लागि पूर्व सूचना प्रणाली",
    budget: 500000,
    budgetCode: "31159",
    sdg: { direct: "Goal 11 / Target 11.5 / Indicator 11.5.1", indirect: "No" },
    iso37120: { direct: "", indirect: "No" },
    sci2025: { direct: "", indirect: "" },
    thematicArea: "preparedness-risk-reduction",
    cycle: "",
    linkageScores: { sdgScore: 4, isoScore: 3, sciScore: 5, linkageType: "concurrence" },
    projectPhase: generateProjectPhase(),
  },
  {
    id: "33",
    department: "बिपद व्यवस्थापन विभाग",
    sector: "सुशासन तथा अन्तरसम्बन्धित क्षेत्र",
    subSector: "विपद व्यवस्थापन",
    mainProgram: "स्थानीय स्तर विपद् पूर्व तयारी तथा प्रतिकार्य कार्यक्रम",
    programName: "फायर ब्रिगेड पुग्न नसक्ने साँघुरो गल्लीहरूमा ओभर हेड ट्याङ्की Pilot Project",
    budget: 1000000,
    budgetCode: "31159",
    sdg: { direct: "Goal 11 / Target 11.c / Indicator 11.c.1", indirect: "No" },
    iso37120: { direct: "", indirect: "No" },
    sci2025: { direct: "", indirect: "" },
    thematicArea: "emergency-response",
    cycle: "",
    linkageScores: { sdgScore: 4, isoScore: 3, sciScore: 5, linkageType: "concurrence" },
    projectPhase: generateProjectPhase(),
  },
  {
    id: "34",
    department: "बिपद व्यवस्थापन विभाग",
    sector: "सुशासन तथा अन्तरसम्बन्धित क्षेत्र",
    subSector: "बारुण यन्त्र सञ्चालन तथा सुदृढीकरण कार्यक्रम",
    mainProgram: "दमकल भवन मर्मत कार्यक्रम",
    programName: "दमकल भवनहरुको मर्मत संभार खर्च",
    budget: 1000000,
    budgetCode: "31159",
    sdg: { direct: "Goal 11 / Target 11.c / Indicator 11.c.1", indirect: "No" },
    iso37120: { direct: "", indirect: "No" },
    sci2025: { direct: "", indirect: "" },
    thematicArea: "recovery-reconstruction",
    cycle: "",
    linkageScores: { sdgScore: 4, isoScore: 3, sciScore: 5, linkageType: "concurrence" },
    projectPhase: generateProjectPhase(),
  },
  {
    id: "35",
    department: "बिपद व्यवस्थापन विभाग",
    sector: "सुशासन तथा अन्तरसम्बन्धित क्षेत्र",
    subSector: "विविध",
    mainProgram: "स्थानीय विपद् तथा जलवायु उत्थानशील कार्यढाँचा",
    programName: "स्थानीय विपद् तथा जलवायु उत्थानशील कार्यढाँचा",
    budget: 500000,
    budgetCode: "22411",
    sdg: { direct: "Goal 11 / Target 11.b / Indicator 11.b.1", indirect: "No" },
    iso37120: { direct: "", indirect: "No" },
    sci2025: { direct: "", indirect: "" },
    thematicArea: "preparedness-risk-reduction",
    cycle: "",
    linkageScores: { sdgScore: 4, isoScore: 3, sciScore: 5, linkageType: "concurrence" },
    projectPhase: generateProjectPhase(),
  },
  {
    id: "36",
    department: "बिपद व्यवस्थापन विभाग",
    sector: "सुशासन तथा अन्तरसम्बन्धित क्षेत्र",
    subSector: "विविध",
    mainProgram: "विपद् व्यवस्थापन विशेष सरसफाई कार्यक्रम",
    programName: "जनशक्ति व्यवस्थापन",
    budget: 1000000,
    budgetCode: "22413",
    sdg: { direct: "Goal 11 / Target 11.6 / Indicator 11.6.1", indirect: "No" },
    iso37120: { direct: "", indirect: "No" },
    sci2025: { direct: "", indirect: "" },
    thematicArea: "governance-coordination",
    cycle: "",
    linkageScores: { sdgScore: 4, isoScore: 3, sciScore: 5, linkageType: "concurrence" },
    projectPhase: generateProjectPhase(),
  },
  {
    id: "37",
    department: "बिपद व्यवस्थापन विभाग",
    sector: "सुशासन तथा अन्तरसम्बन्धित क्षेत्र",
    subSector: "बारुण यन्त्र खरिद तथा मर्मत कार्यक्रम",
    mainProgram: "Fire Hydrant खरिद तथा मर्मत",
    programName: "Fire Hydrant खरिद तथा पाइप लाईन विस्तार तथा मर्मत (क्रमागत)",
    budget: 5000000,
    budgetCode: "31122",
    sdg: { direct: "Goal 11 / Target 11.c / Indicator 11.c.1", indirect: "No" },
    iso37120: { direct: "", indirect: "No" },
    sci2025: { direct: "", indirect: "" },
    thematicArea: "recovery-reconstruction",
    cycle: "",
    linkageScores: { sdgScore: 4, isoScore: 3, sciScore: 5, linkageType: "concurrence" },
    projectPhase: generateProjectPhase(),
  },
  {
    id: "38",
    department: "बिपद व्यवस्थापन विभाग",
    sector: "सुशासन तथा अन्तरसम्बन्धित क्षेत्र",
    subSector: "बारुण यन्त्र खरिद तथा मर्मत कार्यक्रम",
    mainProgram: "Dry Riser Pipe Installation",
    programName: "Dry Riser Pipe Installation तथा Accessories खरिद (क्रमागत)",
    budget: 12000000,
    budgetCode: "31122",
    sdg: { direct: "Goal 11 / Target 11.c / Indicator 11.c.1", indirect: "No" },
    iso37120: { direct: "", indirect: "No" },
    sci2025: { direct: "", indirect: "" },
    thematicArea: "preparedness-risk-reduction",
    cycle: "",
    linkageScores: { sdgScore: 4, isoScore: 3, sciScore: 5, linkageType: "concurrence" },
    projectPhase: generateProjectPhase(),
  },
  {
    id: "39",
    department: "बिपद व्यवस्थापन विभाग",
    sector: "सुशासन तथा अन्तरसम्बन्धित क्षेत्र",
    subSector: "विविध",
    mainProgram: "सरसफाई ढल मंगाल तथा संरचना सरसफाई",
    programName: "जनशक्ति समेत",
    budget: 10000000,
    budgetCode: "22413",
    sdg: { direct: "Goal 11 / Target 11.6 (urban environment) / Indicator 11.6.1", indirect: "No" },
    iso37120: { direct: "", indirect: "No" },
    sci2025: { direct: "", indirect: "" },
    thematicArea: "governance-coordination",
    cycle: "",
    linkageScores: { sdgScore: 4, isoScore: 3, sciScore: 5, linkageType: "concurrence" },
    projectPhase: generateProjectPhase(),
  },
  {
    id: "40",
    department: "बिपद व्यवस्थापन विभाग",
    sector: "सुशासन तथा अन्तरसम्बन्धित क्षेत्र",
    subSector: "विविध",
    mainProgram: "सरसफाई सामग्री खरिद",
    programName: "सरसफाई सामग्री खरिद",
    budget: 1000000,
    budgetCode: "22522",
    sdg: { direct: "Goal 11 / Target 11.6 (urban environment) / Indicator 11.6.1", indirect: "No" },
    iso37120: { direct: "", indirect: "No" },
    sci2025: { direct: "", indirect: "" },
    thematicArea: "preparedness-risk-reduction",
    cycle: "",
    linkageScores: { sdgScore: 4, isoScore: 3, sciScore: 5, linkageType: "concurrence" },
    projectPhase: generateProjectPhase(),
  },
  {
  id: "41",
  department: "बिपद व्यवस्थापन विभाग",
  sector: "सुशासन तथा अन्तरसम्बन्धित क्षेत्र",
  subSector: "विपद व्यवस्थापन",
  mainProgram: "विविध",
  programName: "सरोकारवालाहरुसंग छलफल कार्यक्रम",
  budget: 100000,
  budgetCode: "22522",
  sdg: { direct: "Goal 11 / Target 11.b / Indicator 11.b.2", indirect: "No" },
  iso37120: { direct: "", indirect: "No" },
  sci2025: { direct: "", indirect: "" },
  thematicArea: "governance-coordination",
  cycle: "",
  linkageScores: { sdgScore: 4, isoScore: 3, sciScore: 5, linkageType: "concurrence" },
  projectPhase: generateProjectPhase(),
},
{
  id: "42",
  department: "बिपद व्यवस्थापन विभाग",
  sector: "सुशासन तथा अन्तरसम्बन्धित क्षेत्र",
  subSector: "विपद व्यवस्थापन",
  mainProgram: "विविध",
  programName: "आकस्मिक डुबान समाधान कार्यक्रम",
  budget: 5000000,
  budgetCode: "31159",
  sdg: { direct: "Goal 11 / Target 11.5 / Indicator 11.5.2", indirect: "No" },
  iso37120: { direct: "", indirect: "No" },
  sci2025: { direct: "", indirect: "" },
  thematicArea: "capacity-awareness",
  cycle: "",
  linkageScores: { sdgScore: 4, isoScore: 3, sciScore: 5, linkageType: "concurrence" },
  projectPhase: generateProjectPhase(),
},
{
  id: "43",
  department: "बिपद व्यवस्थापन विभाग",
  sector: "सुशासन तथा अन्तरसम्बन्धित क्षेत्र",
  subSector: "विपद व्यवस्थापन",
  mainProgram: "विविध",
  programName: "डुबान समाधान को लागि औजार उपकरण खरिद",
  budget: 4000000,
  budgetCode: "31122",
  sdg: { direct: "Goal 11 / Target 11.5 / Indicator 11.5.2", indirect: "No" },
  iso37120: { direct: "", indirect: "No" },
  sci2025: { direct: "", indirect: "" },
  thematicArea: "preparedness-risk-reduction",
  cycle: "",
  linkageScores: { sdgScore: 4, isoScore: 3, sciScore: 5, linkageType: "concurrence" },
  projectPhase: generateProjectPhase(),
},
{
  id: "44",
  department: "बिपद व्यवस्थापन विभाग",
  sector: "सुशासन तथा अन्तरसम्बन्धित क्षेत्र",
  subSector: "विपद व्यवस्थापन",
  mainProgram: "विविध",
  programName: "डुबान प्रभावित क्षेत्रहरूको वैज्ञानिक नक्सांकन तथा डेटा संकलन",
  budget: 500000,
  budgetCode: "22411",
  sdg: { direct: "Goal 11 / Target 11.5 + 11.b, Indicator 11.5.1 / 11.b.2", indirect: "No" },
  iso37120: { direct: "", indirect: "No" },
  sci2025: { direct: "", indirect: "" },
  thematicArea: "governance-coordination",
  cycle: "",
  linkageScores: { sdgScore: 4, isoScore: 3, sciScore: 5, linkageType: "concurrence" },
  projectPhase: generateProjectPhase(),
},
]

export const keyIndicators = [
  {
    id: "sdg-11-b-1",
    standard: "SDG",
    code: "11.b.1",
    name: "Disaster Management Training",
    nameNp: "विपद् व्यवस्थापन तालिम",
    description: "Programs providing disaster management training to staff and citizens",
    relatedPrograms: 6, // e.g., Programs 1,2,7,8,11,12
  },
    {
    id: "sdg-11-5-1",
    standard: "SDG",
    code: "11.5.1",
    name: "Disaster Response & Recovery",
    nameNp: "विपद् प्रतिक्रिया तथा पुनःनिर्माण",
    description: "Programs focusing on emergency response, search & rescue, and recovery",
    relatedPrograms: 10, // e.g., Programs 3,9,10,15,21,24,30,42,43
  },
  {
    id: "sdg-11-5-2",
    standard: "SDG",
    code: "11.5.2",
    name: "Disaster Preparedness Infrastructure",
    nameNp: "विपद् पूर्व तयारी पूर्वाधार",
    description: "Programs providing equipment, stockpiling, and infrastructure for disaster mitigation",
    relatedPrograms: 9, // e.g., Programs 4,5,18,19,20,22,23,25,27
  },
  {
    id: "iso-7-em",
    standard: "ISO 37120",
    code: "7.EM",
    name: "Emergency Management Systems",
    nameNp: "आपतकालीन व्यवस्थापन प्रणाली",
    description: "Programs aligned with ISO 37120 emergency management indicators",
    relatedPrograms: 35, // most programs with iso37120 direct="7.EM..."
  },
  {
    id: "sci-3-3",
    standard: "SCI 2025",
    code: "Pillar 3.3",
    name: "Fire and Emergency Equipment",
    nameNp: "दमकल र आपतकालीन उपकरण",
    description: "Programs involving fire trucks, dry risers, hydrants, and emergency gear",
    relatedPrograms: 12, // Programs 4,5,22,23,26,29,30,31,33,37,38,39
  },
];

