// KMC Education Program Data with mappings to SDG, ISO 37120, and SCI 2025
// Path: components/education/data.ts

export interface EducationDepartment {
  id: string
  department: string
  sector: string
  subSector: string
  mainProgram: string
  programName: string
  budget: number
  budgetCode: string
  sdg: {
    direct: string
    indirect: string
  }
  iso37120: {
    direct: string
    indirect: string
  }
  sci2025: {
    direct: string
    indirect: string
  }
  thematicArea: string
  cycle: string
  linkageScores: {
    sdgScore: number
    isoScore: number
    sciScore: number
    linkageType: "research" | "discussion" | "concurrence" | "declaration"
  }
  projectPhase: {
    phase: "inception" | "approval" | "tender" | "award" | "completion"
    progress: number
  }
}

// Example thematic areas for education
export const thematicAreas = [
  {
    id: "literacy-basic",
    name: "Literacy & Basic Education",
    nameNp: "साक्षरता र आधारभूत शिक्षा",
    description: "Primary and secondary education programs, adult literacy initiatives",
    color: "#3B82F6",
    icon: "BookOpen",
    standards: {
      sdg: ["SDG 4.1", "SDG 4.2"],
      iso: ["ISO 37120:13.1"],
      sci: ["Pillar 4 - Human Capital Development"],
    },
  },
  {
    id: "teacher-training",
    name: "Teacher Training & Capacity Development",
    nameNp: "शिक्षक तालिम र क्षमता विकास",
    description: "Training and upskilling teachers and school staff",
    color: "#10B981",
    icon: "GraduationCap",
    standards: {
      sdg: ["SDG 4.c", "SDG 4.7"],
      iso: ["ISO 37120:13.2"],
      sci: ["Pillar 4 - Human Capital Development"],
    },
  },
  {
    id: "digital-education",
    name: "Digital Education & E-Learning",
    nameNp: "डिजिटल शिक्षा",
    description: "E-learning platforms, smart classrooms, digital libraries",
    color: "#8B5CF6",
    icon: "Laptop",
    standards: {
      sdg: ["SDG 4.4", "SDG 9.c"],
      iso: ["ISO 37120:7.5"],
      sci: ["Pillar 4 - Digital Infrastructure"],
    },
  },
  {
    id: "school-infra",
    name: "School Infrastructure & Facilities",
    nameNp: "विद्यालय पूर्वाधार",
    description: "Building, renovating and equipping schools",
    color: "#EF4444",
    icon: "Building2",
    standards: {
      sdg: ["SDG 4.a"],
      iso: ["ISO 37120:13.3"],
      sci: ["Pillar 3 - Infrastructure"],
    },
  },
  {
    id: "monitoring-regulation",
    name: "Monitoring & Regulation",
    nameNp: "अनुगमन तथा नियमन",
    description: "School inspections, student assessments and quality control",
    color: "#F97316",
    icon: "ClipboardCheck",
    standards: {
      sdg: ["SDG 4.1", "SDG 4.6"],
      iso: ["ISO 37120:13.4"],
      sci: ["Pillar 2 - Smart Governance"],
    },
  },
]

// Define linkage types
export const linkageTypes = [
  { value: "declaration", label: "Declaration", score: 1, description: "Official policy declaration without verification" },
  { value: "discussion", label: "Discussion", score: 2, description: "Discussed in meetings/workshops" },
  { value: "concurrence", label: "Concurrence", score: 3, description: "Agreed upon by multiple stakeholders" },
  { value: "research", label: "Research", score: 4, description: "Backed by research and evidence" },
]

// Project phases
export const projectPhases = [
  { value: "inception", label: "Inception", rangeStart: 0, rangeEnd: 20 },
  { value: "approval", label: "Approval", rangeStart: 21, rangeEnd: 40 },
  { value: "tender", label: "Tender", rangeStart: 41, rangeEnd: 60 },
  { value: "award", label: "Award", rangeStart: 61, rangeEnd: 80 },
  { value: "completion", label: "Completion", rangeStart: 81, rangeEnd: 100 },
]

// Helper function to generate random phase progress
function generateProjectPhase(): { phase: "inception" | "approval" | "tender" | "award" | "completion"; progress: number } {
  const phases: ("inception" | "approval" | "tender" | "award" | "completion")[] = ["inception", "approval", "tender", "award", "completion"]
  const weights = [0.15, 0.2, 0.25, 0.25, 0.15]

  let random = Math.random()
  let phaseIndex = 0
  for (let i = 0; i < weights.length; i++) {
    random -= weights[i]
    if (random <= 0) {
      phaseIndex = i
      break
    }
  }

  const phase = phases[phaseIndex]
  const phaseRanges: Record<string, [number, number]> = {
    inception: [25, 20],
    approval: [25, 40],
    tender: [45, 60],
    award: [65, 80],
    completion: [70, 100],
  }

  const [min, max] = phaseRanges[phase]
  const progress = Math.floor(Math.random() * (max - min + 1)) + min
  return { phase, progress }
}

// Example education programs
export const educationPrograms: EducationDepartment[] = [

{
  id: "1",
  department: "शिक्षा विभाग",
  sector: "सामाजिक विकास",
  subSector: "शिक्षा",
  mainProgram: "विविध",
  programName: "काठमाडौं महानगरपालिकाबाट कक्षा ९ र १० को अनुमति प्राप्त गरी सञ्चालनमा रहेको रानीदेवि माध्यमिक विद्यालयलाई विद्यालय सहायक (लेखापाल) तलब भत्ता अनुदान",
  budget: 6500,
  budgetCode: "21111",
  sdg: { direct: "8.5.1", indirect: "NO" },
  iso37120: { direct: "6.(EDUCATION)PRIMARY EDUCATION STUDENT-TEACHER RATIO", indirect: "" },
  sci2025: { direct: "pillar no=2 componentno=2.5 I-026", indirect: "" },
  thematicArea: "literacy-basic",
  cycle: "",
  linkageScores: { sdgScore: 3, isoScore: 2, sciScore: 2, linkageType: "discussion" },
  projectPhase: generateProjectPhase(),
},

{
  id: "2",
  department: "शिक्षा विभाग",
  sector: "सामाजिक विकास",
  subSector: "शिक्षा",
  mainProgram: "विविध",
  programName: "स्रोत शिक्षकको सट्टामा रहने शिक्षकको तलब भत्ता",
  budget: 35194,
  budgetCode: "21111",
  sdg: { direct: "8.5.1", indirect: "NO" },
  iso37120: { direct: "6.(EDUCATION)PRIMARY EDUCATION STUDENT-TEACHER RATIO", indirect: "" },
  sci2025: { direct: "pillar no=2 componentno=2.5 I-027", indirect: "" },
  thematicArea: "teacher-training",
  cycle: "",
  linkageScores: { sdgScore: 3, isoScore: 2, sciScore: 2, linkageType: "discussion" },
  projectPhase: generateProjectPhase(),
},

{
  id: "3",
  department: "शिक्षा विभाग",
  sector: "सामाजिक विकास",
  subSector: "शिक्षा",
  mainProgram: "विविध",
  programName: "प्रारम्भिक बालविकास सहजकर्ता, विद्यालय सहयोगी र विद्यालय सहायक पारिश्रमिकमा थप अनुदान",
  budget: 65193,
  budgetCode: "21111",
  sdg: { direct: "8.5.1", indirect: "NO" },
  iso37120: { 
      direct: "6.(EDUCATION) EXPENDITURE PER CAPITA",
      indirect: "Percentage of school-aged population enrolled in school"
  },
  sci2025: { direct: "pillar no=2 componentno=2.5 I-028", indirect: "" },
  thematicArea: "literacy-basic",
  cycle: "",
  linkageScores: { sdgScore: 4, isoScore: 3, sciScore: 3, linkageType: "research" },
  projectPhase: generateProjectPhase(),
},

{
  id: "4",
  department: "शिक्षा विभाग",
  sector: "सामाजिक विकास",
  subSector: "शिक्षा",
  mainProgram: "विविध",
  programName: "महानगरको आन्तरिक स्रोतबाट व्यवस्थापन हुने विद्यालय सहायक इसीडी शिक्षक तलब",
  budget: 200000,
  budgetCode: "21111",
  sdg: { direct: "8.5.1", indirect: "NO" },
  iso37120: { direct: "Number of teachers per 1000 students", indirect: "NO" },
  sci2025: { direct: "pillar no=2 componentno=2.5 I-029", indirect: "" },
  thematicArea: "teacher-training",
  cycle: "",
  linkageScores: { sdgScore: 3, isoScore: 3, sciScore: 2, linkageType: "concurrence" },
  projectPhase: generateProjectPhase(),
},

{
  id: "5",
  department: "शिक्षा विभाग",
  sector: "सामाजिक विकास",
  subSector: "शिक्षा",
  mainProgram: "विविध",
  programName: "सोधभर्ना आउने शिक्षकको तलव भत्ता",
  budget: 300,
  budgetCode: "21111",
  sdg: { direct: "8.5.1", indirect: "NO" },
  iso37120: { direct: "ECD शिक्षक तलब", indirect: "NO" },
  sci2025: { direct: "pillar no=2 componentno=2.5 I-030", indirect: "" },
  thematicArea: "teacher-training",
  cycle: "",
  linkageScores: { sdgScore: 2, isoScore: 2, sciScore: 2, linkageType: "discussion" },
  projectPhase: generateProjectPhase(),
},
{
  id: "6",
  department: "शिक्षा विभाग",
  sector: "सामाजिक विकास",
  subSector: "शिक्षा",
  mainProgram: "विविध",
  programName: "विद्यालय व्यवस्थापन तथा प्रशासनिक सुधार कार्यक्रम",
  budget: 500,
  budgetCode: "21112",
  sdg: { direct: "4.c.1", indirect: "8.5.1" },
  iso37120: { direct: "6.(EDUCATION) SECONDARY EDUCATION STUDENT-TEACHER RATIO", indirect: "" },
  sci2025: { direct: "pillar no=2 componentno=2.5 I-031", indirect: "" },
  thematicArea: "teacher-training",
  cycle: "",
  linkageScores: { sdgScore: 3, isoScore: 2, sciScore: 2, linkageType: "discussion" },
  projectPhase: generateProjectPhase(),
},

{
  id: "7",
  department: "शिक्षा विभाग",
  sector: "सामाजिक विकास",
  subSector: "शिक्षा",
  mainProgram: "विविध",
  programName: "डिजिटल कक्षा सञ्चालन तथा ई–लर्निङ प्रवर्द्धन",
  budget: 1920,
  budgetCode: "22522",
  sdg: { direct: "4.4.1", indirect: "9.c.1" },
  iso37120: { direct: "Internet access in schools", indirect: "" },
  sci2025: { direct: "pillar no=2 componentno=2.5 I-032", indirect: "" },
  thematicArea: "digital-education",
  cycle: "",
  linkageScores: { sdgScore: 4, isoScore: 3, sciScore: 3, linkageType: "research" },
  projectPhase: generateProjectPhase(),
},

{
  id: "8",
  department: "शिक्षा विभाग",
  sector: "सामाजिक विकास",
  subSector: "शिक्षा",
  mainProgram: "विविध",
  programName: "विद्यालय भौतिक पूर्वाधार मर्मत सुधार",
  budget: 300,
  budgetCode: "31159",
  sdg: { direct: "4.a.1", indirect: "" },
  iso37120: { direct: "Condition of school buildings", indirect: "" },
  sci2025: { direct: "pillar no=2 componentno=2.5 I-033", indirect: "" },
  thematicArea: "school-infrastructure",
  cycle: "",
  linkageScores: { sdgScore: 3, isoScore: 3, sciScore: 2, linkageType: "concurrence" },
  projectPhase: generateProjectPhase(),
},

{
  id: "9",
  department: "शिक्षा विभाग",
  sector: "सामाजिक विकास",
  subSector: "शिक्षा",
  mainProgram: "विविध",
  programName: "अनुगमन तथा मूल्याङ्कन प्रणाली सुदृढीकरण",
  budget: 500,
  budgetCode: "22529",
  sdg: { direct: "17.18.1", indirect: "4.1.1" },
  iso37120: { direct: "Education data management system", indirect: "" },
  sci2025: { direct: "pillar no=2 componentno=2.5 I-034", indirect: "" },
  thematicArea: "monitoring-regulation",
  cycle: "",
  linkageScores: { sdgScore: 3, isoScore: 2, sciScore: 3, linkageType: "discussion" },
  projectPhase: generateProjectPhase(),
},

{
  id: "10",
  department: "शिक्षा विभाग",
  sector: "सामाजिक विकास",
  subSector: "शिक्षा",
  mainProgram: "विविध",
  programName: "समुदाय–विद्यालय साझेदारी कार्यक्रम",
  budget: 300,
  budgetCode: "22512",
  sdg: { direct: "4.7.1", indirect: "11.3.2" },
  iso37120: { direct: "Community participation in schools", indirect: "" },
  sci2025: { direct: "pillar no=2 componentno=2.5 I-035", indirect: "" },
  thematicArea: "monitoring-regulation",
  cycle: "",
  linkageScores: { sdgScore: 3, isoScore: 2, sciScore: 2, linkageType: "declaration" },
  projectPhase: generateProjectPhase(),
},
{
  id: "11",
  department: "शिक्षा विभाग",
  sector: "सामाजिक विकास",
  subSector: "शिक्षा",
  mainProgram: "विविध",
  programName: "आपतकालीन शिक्षा सहयोग कार्यक्रम",
  budget: 500,
  budgetCode: "22601",
  sdg: { direct: "4.5.1", indirect: "13.1.3" },
  iso37120: { direct: "Continuity of education during emergencies", indirect: "" },
  sci2025: { direct: "pillar no=2 componentno=2.5 I-036", indirect: "" },
  thematicArea: "literacy-basic",
  cycle: "",
  linkageScores: { sdgScore: 3, isoScore: 2, sciScore: 2, linkageType: "discussion" },
  projectPhase: generateProjectPhase(),
},

{
  id: "12",
  department: "शिक्षा विभाग",
  sector: "सामाजिक विकास",
  subSector: "शिक्षा",
  mainProgram: "विविध",
  programName: "विद्यालय वातावरण तथा हरित शिक्षा प्रवर्द्धन",
  budget: 500,
  budgetCode: "22602",
  sdg: { direct: "4.7.1", indirect: "13.3.1" },
  iso37120: { direct: "Environmental education in curriculum", indirect: "" },
  sci2025: { direct: "pillar no=2 componentno=2.5 I-037", indirect: "" },
  thematicArea: "literacy-basic",
  cycle: "",
  linkageScores: { sdgScore: 4, isoScore: 3, sciScore: 3, linkageType: "research" },
  projectPhase: generateProjectPhase(),
},
{
  id: "13",
  department: "शिक्षा विभाग",
  sector: "सामाजिक विकास",
  subSector: "शिक्षा",
  mainProgram: "विविध",
  programName: "विद्यालय सूचना व्यवस्थापन प्रणाली (EMIS) सुदृढीकरण",
  budget: 500,
  budgetCode: "22530",
  sdg: { direct: "4.1.1", indirect: "16.6.2" },
  iso37120: { direct: "Education management information system", indirect: "" },
  sci2025: { direct: "pillar no=2 componentno=2.5 I-038", indirect: "" },
  thematicArea: "digital-education",
  cycle: "",
  linkageScores: { sdgScore: 3, isoScore: 3, sciScore: 4, linkageType: "research" },
  projectPhase: generateProjectPhase(),
},

{
  id: "14",
  department: "शिक्षा विभाग",
  sector: "सामाजिक विकास",
  subSector: "शिक्षा",
  mainProgram: "विविध",
  programName: "विद्यालय स्वास्थ्य तथा पोषण शिक्षा",
  budget: 1000,
  budgetCode: "22603",
  sdg: { direct: "4.7.1", indirect: "3.b.1" },
  iso37120: { direct: "Health education programs in schools", indirect: "" },
  sci2025: { direct: "pillar no=2 componentno=2.5 I-039", indirect: "" },
  thematicArea: "monitoring-regulation",
  cycle: "",
  linkageScores: { sdgScore: 2, isoScore: 2, sciScore: 2, linkageType: "declaration" },
  projectPhase: generateProjectPhase(),
},

{
  id: "15",
  department: "शिक्षा विभाग",
  sector: "सामाजिक विकास",
  subSector: "शिक्षा",
  mainProgram: "विविध",
  programName: "शिक्षक कार्यसम्पादन मूल्याङ्कन प्रणाली",
  budget: 5000,
  budgetCode: "22531",
  sdg: { direct: "4.c.1", indirect: "" },
  iso37120: { direct: "Teacher performance evaluation", indirect: "" },
  sci2025: { direct: "pillar no=2 componentno=2.5 I-040", indirect: "" },
  thematicArea: "teacher-training",
  cycle: "",
  linkageScores: { sdgScore: 3, isoScore: 2, sciScore: 3, linkageType: "concurrence" },
  projectPhase: generateProjectPhase(),
},
{
  id: "16",
  department: "शिक्षा विभाग",
  sector: "सामाजिक विकास",
  subSector: "पाठ्यक्रम र पाठ्यसामग्री वितरण कार्यक्रम",
  mainProgram: "विविध",
  programName: "नेपाल भाषाका पाठ्यपुस्तक छपाई तथा वितरण",
  budget: 500,
  budgetCode: "22315",
  sdg: { direct: "4.6", indirect: "" },
  iso37120: { direct: "Access to free or affordable education materials and services", indirect: "" },
  sci2025: { direct: "pillar no=1 componentno=1.2 I-005", indirect: "" },
  thematicArea: "literacy-basic",
  cycle: "",
  linkageScores: { sdgScore: 4, isoScore: 3, sciScore: 3, linkageType: "research" },
  projectPhase: generateProjectPhase(),
},

{
  id: "17",
  department: "शिक्षा विभाग",
  sector: "सामाजिक विकास",
  subSector: "शिक्षा",
  mainProgram: "विविध",
  programName: "इतिहास, योग, आयुर्वेद सहित छोटो अवधि पाठ्यक्रम निर्माण",
  budget: 800,
  budgetCode: "22411",
  sdg: { direct: "4.6", indirect: "" },
  iso37120: { direct: "Access to free or affordable education materials and services", indirect: "" },
  sci2025: { direct: "pillar no=3 componentno=3.9 I-062", indirect: "" },
  thematicArea: "literacy-basic",
  cycle: "",
  linkageScores: { sdgScore: 4, isoScore: 3, sciScore: 2, linkageType: "discussion" },
  projectPhase: generateProjectPhase(),
},

{
  id: "18",
  department: "शिक्षा विभाग",
  sector: "सामाजिक विकास",
  subSector: "शिक्षा",
  mainProgram: "विविध",
  programName: "नेपालभाषा तथा तामाङ भाषा प्रवर्धन अनुगमन",
  budget: 5000,
  budgetCode: "22411",
  sdg: { direct: "4.6", indirect: "" },
  iso37120: { direct: "Access to free or affordable education materials and services", indirect: "Indirect" },
  sci2025: { direct: "pillar no=1 componentno=1.2 I-005", indirect: "Indirect" },
  thematicArea: "literacy-basic",
  cycle: "",
  linkageScores: { sdgScore: 3, isoScore: 3, sciScore: 2, linkageType: "concurrence" },
  projectPhase: generateProjectPhase(),
},

{
  id: "19",
  department: "शिक्षा विभाग",
  sector: "सामाजिक विकास",
  subSector: "शिक्षा",
  mainProgram: "विविध",
  programName: "श्रोत विज्ञ व्यवस्थापन खर्च",
  budget: 87380,
  budgetCode: "22411",
  sdg: { direct: "8.5.1", indirect: "" },
  iso37120: { direct: "", indirect: "" },
  sci2025: { direct: "pillar no=1 componentno=1.2 I-007", indirect: "" },
  thematicArea: "teacher-training",
  cycle: "",
  linkageScores: { sdgScore: 2, isoScore: 0, sciScore: 2, linkageType: "declaration" },
  projectPhase: generateProjectPhase(),
},

{
  id: "20",
  department: "शिक्षा विभाग",
  sector: "सामाजिक विकास",
  subSector: "शिक्षा",
  mainProgram: "अनौपचारिक शिक्षा कार्यक्रम",
  programName: "नेपालभाषा तथा तामाङ भाषा प्रशिक्षक पारिश्रमिक",
  budget: 500,
  budgetCode: "22411",
  sdg: { direct: "8.5.1", indirect: "" },
  iso37120: { direct: "", indirect: "" },
  sci2025: { direct: "pillar no=1 componentno=1.2 I-007", indirect: "" },
  thematicArea: "teacher-training",
  cycle: "",
  linkageScores: { sdgScore: 3, isoScore: 0, sciScore: 2, linkageType: "research" },
  projectPhase: generateProjectPhase(),
},

{
  id: "21",
  department: "शिक्षा विभाग",
  sector: "सामाजिक विकास",
  subSector: "शिक्षा",
  mainProgram: "विविध",
  programName: "IEMIS Update कार्यशाला ०८२/०८३",
  budget: 300,
  budgetCode: "22412",
  sdg: { direct: "4.5.1", indirect: "" },
  iso37120: { direct: "Number of teachers per 1000 students", indirect: "" },
  sci2025: { direct: "pillar no=2 componentno=2.5 I-026", indirect: "" },
  thematicArea: "digital-education",
  cycle: "",
  linkageScores: { sdgScore: 4, isoScore: 3, sciScore: 3, linkageType: "research" },
  projectPhase: generateProjectPhase(),
},

{
  id: "22",
  department: "शिक्षा विभाग",
  sector: "सामाजिक विकास",
  subSector: "शिक्षा",
  mainProgram: "विविध",
  programName: "सामुदायिक शिक्षकहरूका लागि योग तालिम",
  budget: 300,
  budgetCode: "22511",
  sdg: { direct: "3.B", indirect: "" },
  iso37120: { direct: "", indirect: "Education policy and planning" },
  sci2025: { direct: "pillar no=2 componentno=2.5 I-027", indirect: "" },
  thematicArea: "monitoring-regulation",
  cycle: "",
  linkageScores: { sdgScore: 3, isoScore: 2, sciScore: 3, linkageType: "discussion" },
  projectPhase: generateProjectPhase(),
},

{
  id: "23",
  department: "शिक्षा विभाग",
  sector: "सामाजिक विकास",
  subSector: "शिक्षा",
  mainProgram: "विविध",
  programName: "लेखा व्यवस्थापन तालिम",
  budget: 500,
  budgetCode: "22511",
  sdg: { direct: "1.1", indirect: "" },
  iso37120: { direct: "Access to free or affordable education materials and services", indirect: "" },
  sci2025: { direct: "pillar no=3 componentno=3.9 I-062", indirect: "" },
  thematicArea: "teacher-training",
  cycle: "",
  linkageScores: { sdgScore: 2, isoScore: 3, sciScore: 3, linkageType: "research" },
  projectPhase: generateProjectPhase(),
},

{
  id: "24",
  department: "शिक्षा विभाग",
  sector: "सामाजिक विकास",
  subSector: "शिक्षा",
  mainProgram: "विविध",
  programName: "पाठ्यक्रम कार्यान्वयन कार्यशाला",
  budget: 900,
  budgetCode: "22511",
  sdg: { direct: "2.2", indirect: "" },
  iso37120: { direct: "", indirect: "Education policy and planning" },
  sci2025: { direct: "pillar no=1 componentno=1.2 I-007", indirect: "" },
  thematicArea: "literacy-basic",
  cycle: "",
  linkageScores: { sdgScore: 2, isoScore: 2, sciScore: 3, linkageType: "concurrence" },
  projectPhase: generateProjectPhase(),
},

{
  id: "25",
  department: "शिक्षा विभाग",
  sector: "सामाजिक विकास",
  subSector: "शिक्षा",
  mainProgram: "विविध",
  programName: "ECD क्षमता विकास तालिम",
  budget: 1000,
  budgetCode: "22511",
  sdg: { direct: "4.2", indirect: "" },
  iso37120: { direct: "Number of teachers per 1000 students", indirect: "" },
  sci2025: { direct: "pillar no=1 componentno=1.2 I-007", indirect: "" },
  thematicArea: "teacher-training",
  cycle: "",
  linkageScores: { sdgScore: 4, isoScore: 3, sciScore: 3, linkageType: "research" },
  projectPhase: generateProjectPhase(),
},
{
  id: "26",
  department: "शिक्षा विभाग",
  sector: "सामाजिक विकास",
  subSector: "शिक्षा",
  mainProgram: "विविध",
  programName: "मनोसामाजिक परामर्श तालिम",
  budget: 2500,
  budgetCode: "22511",
  sdg: { direct: "3.4", indirect: "" },
  iso37120: { direct: "Number of teachers per 1000 students", indirect: "" },
  sci2025: { direct: "pillar no=1 componentno=1.2 I-008", indirect: "" },
  thematicArea: "teacher-training",
  cycle: "",
  linkageScores: { sdgScore: 3, isoScore: 3, sciScore: 3, linkageType: "discussion" },
  projectPhase: generateProjectPhase(),
},

{
  id: "27",
  department: "शिक्षा विभाग",
  sector: "सामाजिक विकास",
  subSector: "शिक्षा",
  mainProgram: "विविध",
  programName: "नेपालभाषा प्रशिक्षक पुनर्ताजगी तालिम",
  budget: 3500,
  budgetCode: "22511",
  sdg: { direct: "4.6", indirect: "" },
  iso37120: { direct: "Number of teachers per 1000 students", indirect: "" },
  sci2025: { direct: "pillar no=1 componentno=1.2 I-009", indirect: "" },
  thematicArea: "teacher-training",
  cycle: "",
  linkageScores: { sdgScore: 4, isoScore: 3, sciScore: 3, linkageType: "research" },
  projectPhase: generateProjectPhase(),
},

{
  id: "28",
  department: "शिक्षा विभाग",
  sector: "सामाजिक विकास",
  subSector: "शिक्षा",
  mainProgram: "विविध",
  programName: "विद्यालय अनुगमन तथा मूल्याङ्कन",
  budget: 500,
  budgetCode: "22612",
  sdg: { direct: "4.1", indirect: "" },
  iso37120: { direct: "Education quality monitoring", indirect: "" },
  sci2025: { direct: "pillar no=2 componentno=2.5 I-032", indirect: "" },
  thematicArea: "monitoring-regulation",
  cycle: "",
  linkageScores: { sdgScore: 3, isoScore: 3, sciScore: 3, linkageType: "concurrence" },
  projectPhase: generateProjectPhase(),
},

{
  id: "29",
  department: "शिक्षा विभाग",
  sector: "सामाजिक विकास",
  subSector: "शिक्षा",
  mainProgram: "विविध",
  programName: "समुदाय–विद्यालय सहकार्य कार्यक्रम",
  budget: 200,
  budgetCode: "22613",
  sdg: { direct: "4.7", indirect: "" },
  iso37120: { direct: "Community participation in education", indirect: "" },
  sci2025: { direct: "pillar no=2 componentno=2.5 I-033", indirect: "" },
  thematicArea: "literacy-basic",
  cycle: "",
  linkageScores: { sdgScore: 3, isoScore: 3, sciScore: 3, linkageType: "research" },
  projectPhase: generateProjectPhase(),
},

{
  id: "30",
  department: "शिक्षा विभाग",
  sector: "सामाजिक विकास",
  subSector: "शिक्षा",
  mainProgram: "विविध",
  programName: "शिक्षा नीति समीक्षा तथा योजना तर्जुमा",
  budget: 300,
  budgetCode: "22614",
  sdg: { direct: "4.1", indirect: "" },
  iso37120: { direct: "Education policy and planning", indirect: "" },
  sci2025: { direct: "pillar no=2 componentno=2.5 I-034", indirect: "" },
  thematicArea: "monitoring-regulation",
  cycle: "",
  linkageScores: { sdgScore: 3, isoScore: 3, sciScore: 3, linkageType: "discussion" },
  projectPhase: generateProjectPhase(),
},

{
  id: "31",
  department: "शिक्षा विभाग",
  sector: "सामाजिक विकास",
  subSector: "शिक्षा",
  mainProgram: "विविध",
  programName: "सामुदायिक विद्यालयका विद्यार्थीहरूलाई नेतृत्व क्षमता तथा राष्ट्रिय एकताको भावना विकासका लागि राष्ट्रिय सेवा दलसँग G2G तालिम",
  budget: 500,
  budgetCode: "",
  sdg: { direct: "4.6", indirect: "" },
  iso37120: { direct: "Education policy and planning", indirect: "" },
  sci2025: { direct: "pillar no=1 componentno=1.2 I-010", indirect: "" },
  thematicArea: "teacher-training",
  cycle: "",
  linkageScores: { sdgScore: 3, isoScore: 3, sciScore: 2, linkageType: "discussion" },
  projectPhase: generateProjectPhase(),
},

{
  id: "32",
  department: "शिक्षा विभाग",
  sector: "सामाजिक विकास",
  subSector: "शिक्षा",
  mainProgram: "विविध",
  programName: "शिक्षकहरूका लागि वार्षिक कार्यक्रम कार्यान्वयन अभिमुखीकरण कार्यक्रम",
  budget: 200,
  budgetCode: "",
  sdg: { direct: "4.c", indirect: "" },
  iso37120: { direct: "Number of teachers per 1,000 students", indirect: "" },
  sci2025: { direct: "pillar no=1 componentno=1.2 I-011", indirect: "" },
  thematicArea: "teacher-training",
  cycle: "",
  linkageScores: { sdgScore: 4, isoScore: 3, sciScore: 2, linkageType: "research" },
  projectPhase: generateProjectPhase(),
},

{
  id: "33",
  department: "शिक्षा विभाग",
  sector: "सामाजिक विकास",
  subSector: "शिक्षा",
  mainProgram: "विविध",
  programName: "महानगर स्तरीय स्काउट परिषद बैठक तथा स्काउट क्रियाकलाप सञ्चालन",
  budget: 300,
  budgetCode: "",
  sdg: { direct: "4.6", indirect: "" },
  iso37120: { direct: "Education policy and planning", indirect: "" },
  sci2025: { direct: "pillar no=1 componentno=1.5 I-013", indirect: "" },
  thematicArea: "literacy-basic",
  cycle: "",
  linkageScores: { sdgScore: 3, isoScore: 3, sciScore: 3, linkageType: "declaration" },
  projectPhase: generateProjectPhase(),
},

{
  id: "34",
  department: "शिक्षा विभाग",
  sector: "सामाजिक विकास",
  subSector: "शिक्षा",
  mainProgram: "विविध",
  programName: "महानगरीयस्तर प्रधानाध्यापकहरूको बैठक सञ्चालन तथा व्यवस्थापन",
  budget: 500,
  budgetCode: "",
  sdg: { direct: "4.c", indirect: "" },
  iso37120: { direct: "Education policy and planning", indirect: "" },
  sci2025: { direct: "pillar no=1 componentno=1.2 I-007", indirect: "" },
  thematicArea: "monitoring-regulation",
  cycle: "",
  linkageScores: { sdgScore: 3, isoScore: 3, sciScore: 2, linkageType: "discussion" },
  projectPhase: generateProjectPhase(),
},

{
  id: "35",
  department: "शिक्षा विभाग",
  sector: "सामाजिक विकास",
  subSector: "शिक्षा",
  mainProgram: "विविध",
  programName: "विद्यालयमा लैङ्गिक हिंसा तथा अपराध नियन्त्रणसम्बन्धी चेतनामूलक कार्यक्रम",
  budget: 500,
  budgetCode: "",
  sdg: { direct: "4.c", indirect: "5.2" },
  iso37120: { direct: "Education policy and planning", indirect: "" },
  sci2025: { direct: "pillar no=2 componentno=2.5 I-026", indirect: "" },
  thematicArea: "monitoring-regulation",
  cycle: "",
  linkageScores: { sdgScore: 4, isoScore: 3, sciScore: 3, linkageType: "concurrence" },
  projectPhase: generateProjectPhase(),
},

{
  id: "36",
  department: "शिक्षा विभाग",
  sector: "सामाजिक विकास",
  subSector: "शिक्षा",
  mainProgram: "विविध",
  programName: "विषयगत शिक्षकहरूको गोष्ठी",
  budget: 522,
  budgetCode: "",
  sdg: { direct: "4.c", indirect: "" },
  iso37120: { direct: "Number of teachers per 1,000 students", indirect: "" },
  sci2025: { direct: "pillar no=2 componentno=2.5 I-026", indirect: "" },
  thematicArea: "teacher-training",
  cycle: "",
  linkageScores: { sdgScore: 4, isoScore: 3, sciScore: 3, linkageType: "research" },
  projectPhase: generateProjectPhase(),
},

{
  id: "37",
  department: "शिक्षा विभाग",
  sector: "सामाजिक विकास",
  subSector: "शिक्षा",
  mainProgram: "विविध",
  programName: "विद्यालय तहका विषयगत समितिहरू (६ वटा) बीच अन्तरक्रिया बैठक सञ्चालन तथा व्यवस्थापन",
  budget: 550,
  budgetCode: "",
  sdg: { direct: "4.c", indirect: "" },
  iso37120: { direct: "Education policy and planning", indirect: "" },
  sci2025: { direct: "pillar no=1 componentno=1.4 I-012", indirect: "" },
  thematicArea: "monitoring-regulation",
  cycle: "",
  linkageScores: { sdgScore: 3, isoScore: 3, sciScore: 2, linkageType: "discussion" },
  projectPhase: generateProjectPhase(),
},

{
  id: "38",
  department: "शिक्षा विभाग",
  sector: "सामाजिक विकास",
  subSector: "शिक्षा",
  mainProgram: "विविध",
  programName: "स्रोत केन्द्र स्तरमा प्रधानाध्यापक तथा विषयगत बैठक सञ्चालन",
  budget: 800,
  budgetCode: "",
  sdg: { direct: "4.c", indirect: "" },
  iso37120: { direct: "Access to free or affordable education materials and services", indirect: "" },
  sci2025: { direct: "pillar no=1 componentno=1.2 I-007", indirect: "" },
  thematicArea: "teacher-training",
  cycle: "",
  linkageScores: { sdgScore: 3, isoScore: 3, sciScore: 2, linkageType: "concurrence" },
  projectPhase: generateProjectPhase(),
},

{
  id: "39",
  department: "शिक्षा विभाग",
  sector: "सामाजिक विकास",
  subSector: "शिक्षा",
  mainProgram: "विविध",
  programName: "नेपाल भाषाको पाठ्यपुस्तक परिमार्जन/पुनर्लेखन कार्य (विषयविज्ञ पारिश्रमिक सहित)",
  budget: 1000,
  budgetCode: "",
  sdg: { direct: "4.1", indirect: "4.c" },
  iso37120: { direct: "Access to free or affordable education materials and services", indirect: "" },
  sci2025: { direct: "pillar no=2 componentno=2.5 I-026", indirect: "" },
  thematicArea: "literacy-basic",
  cycle: "",
  linkageScores: { sdgScore: 4, isoScore: 3, sciScore: 3, linkageType: "research" },
  projectPhase: generateProjectPhase(),
},

{
  id: "40",
  department: "शिक्षा विभाग",
  sector: "सामाजिक विकास",
  subSector: "शिक्षा",
  mainProgram: "विविध",
  programName: "पाठ्यक्रमअनुसार कक्षागत तथा विषयगत प्रश्नपत्र निर्माण एवं मूल्याङ्कन तालिम",
  budget: 1000,
  budgetCode: "",
  sdg: { direct: "4.c", indirect: "" },
  iso37120: { direct: "Access to free or affordable education materials and services", indirect: "" },
  sci2025: { direct: "pillar no=2 componentno=2.5 I-026", indirect: "" },
  thematicArea: "monitoring-regulation",
  cycle: "",
  linkageScores: { sdgScore: 4, isoScore: 3, sciScore: 3, linkageType: "research" },
  projectPhase: generateProjectPhase(),
},
{
  id: "41",
  department: "शिक्षा विभाग",
  sector: "सामाजिक विकास",
  subSector: "शिक्षा",
  mainProgram: "विविध",
  programName: "निजी विद्यालय वर्गीकरण तथा अडिट कार्यक्रम",
  budget: 1000,
  budgetCode: "",
  sdg: { direct: "4.c", indirect: "" },
  iso37120: { direct: "Education policy and planning", indirect: "" },
  sci2025: { direct: "pillar no=2 componentno=2.5 I-026", indirect: "" },
  thematicArea: "monitoring-regulation",
  cycle: "",
  linkageScores: { sdgScore: 3, isoScore: 3, sciScore: 3, linkageType: "concurrence" },
  projectPhase: generateProjectPhase(),
},

{
  id: "42",
  department: "शिक्षा विभाग",
  sector: "सामाजिक विकास",
  subSector: "शिक्षा",
  mainProgram: "विविध",
  programName: "Global Student Exchange Program",
  budget: 1000,
  budgetCode: "",
  sdg: { direct: "4.7", indirect: "" },
  iso37120: { direct: "Education policy and planning", indirect: "" },
  sci2025: { direct: "pillar no=1 componentno=1.2 I-007", indirect: "" },
  thematicArea: "teacher-training",
  cycle: "",
  linkageScores: { sdgScore: 3, isoScore: 2, sciScore: 2, linkageType: "discussion" },
  projectPhase: generateProjectPhase(),
},

{
  id: "43",
  department: "शिक्षा विभाग",
  sector: "सामाजिक विकास",
  subSector: "शिक्षा",
  mainProgram: "विविध",
  programName: "को–लिभिङ / होस्टेल प्रवर्द्धन तथा नियमन कार्यक्रम",
  budget: 1500,
  budgetCode: "",
  sdg: { direct: "4.1", indirect: "" },
  iso37120: { direct: "Education policy and planning", indirect: "" },
  sci2025: { direct: "pillar no=2 componentno=2.5 I-026", indirect: "" },
  thematicArea: "school-infra",
  cycle: "",
  linkageScores: { sdgScore: 3, isoScore: 3, sciScore: 3, linkageType: "discussion" },
  projectPhase: generateProjectPhase(),
},

{
  id: "44",
  department: "शिक्षा विभाग",
  sector: "सामाजिक विकास",
  subSector: "शिक्षा",
  mainProgram: "विविध",
  programName: "स्थानीय पाठ्यक्रममा आधारित विशिष्टिकरण तालिका, नमुना प्रश्नपत्र विकास तथा छपाई",
  budget: 1500,
  budgetCode: "",
  sdg: { direct: "4.c", indirect: "" },
  iso37120: { direct: "Access to free or affordable education materials and services", indirect: "" },
  sci2025: { direct: "pillar no=1 componentno=1.2 I-007", indirect: "" },
  thematicArea: "literacy-basic",
  cycle: "",
  linkageScores: { sdgScore: 4, isoScore: 3, sciScore: 2, linkageType: "research" },
  projectPhase: generateProjectPhase(),
},

{
  id: "edu-045",
  department: "शिक्षा विभाग",
  sector: "सामाजिक विकास",
  subSector: "शिक्षा",
  mainProgram: "विविध",
  programName: "महानगरिय स्थानीय स्काउट सञ्चालन, व्यवस्थापन तथा परिचालन",
  budget: 1500,
  budgetCode: "",
  sdg: { direct: "4.7", indirect: "" },
  iso37120: { direct: "Education policy and planning", indirect: "" },
  sci2025: { direct: "pillar no=3 componentno=3.9 I-061", indirect: "" },
  thematicArea: "teacher-training",
  cycle: "",
  linkageScores: { sdgScore: 3, isoScore: 3, sciScore: 3, linkageType: "declaration" },
  projectPhase: generateProjectPhase(),
},

{
  id: "edu-046",
  department: "शिक्षा विभाग",
  sector: "सामाजिक विकास",
  subSector: "शिक्षा",
  mainProgram: "विविध",
  programName: "\"हेरिटेज इन स्कूल\" अभियान",
  budget: 1800,
  budgetCode: "",
  sdg: { direct: "4.7", indirect: "" },
  iso37120: { direct: "Education policy and planning", indirect: "" },
  sci2025: { direct: "pillar no=1 componentno=1.2 I-007", indirect: "" },
  thematicArea: "literacy-basic",
  cycle: "",
  linkageScores: { sdgScore: 3, isoScore: 3, sciScore: 2, linkageType: "discussion" },
  projectPhase: generateProjectPhase(),
},

{
  id: "edu-047",
  department: "शिक्षा विभाग",
  sector: "सामाजिक विकास",
  subSector: "शिक्षा",
  mainProgram: "विविध",
  programName: "बाल–अभिभावक सहभागिता कार्यक्रम (प्रति विद्यालय रु २०,००० का दरले)",
  budget: 2000,
  budgetCode: "",
  sdg: { direct: "8.5.1", indirect: "" },
  iso37120: { direct: "Education policy and planning", indirect: "" },
  sci2025: { direct: "pillar no=2 componentno=2.5 I-026", indirect: "" },
  thematicArea: "teacher-training",
  cycle: "",
  linkageScores: { sdgScore: 2, isoScore: 2, sciScore: 3, linkageType: "declaration" },
  projectPhase: generateProjectPhase(),
},

{
  id: "edu-048",
  department: "शिक्षा विभाग",
  sector: "सामाजिक विकास",
  subSector: "शिक्षा",
  mainProgram: "विविध",
  programName: "ERP सफ्टवेयर खरिद",
  budget: 2100,
  budgetCode: "",
  sdg: { direct: "4.a", indirect: "" },
  iso37120: { direct: "Education policy and planning", indirect: "" },
  sci2025: { direct: "pillar no=1 componentno=1.2 I-006", indirect: "" },
  thematicArea: "digital-education",
  cycle: "",
  linkageScores: { sdgScore: 3, isoScore: 3, sciScore: 3, linkageType: "research" },
  projectPhase: generateProjectPhase(),
},

{
  id: "edu-049",
  department: "शिक्षा विभाग",
  sector: "सामाजिक विकास",
  subSector: "शिक्षा",
  mainProgram: "विविध",
  programName: "\"मेरो पहिलो शिक्षक\" अभिभावक सशक्तिकरण कार्यक्रम (ECD अभिभावकका लागि)",
  budget: 2200,
  budgetCode: "",
  sdg: { direct: "4.2", indirect: "3.4" },
  iso37120: { direct: "Education policy and planning", indirect: "" },
  sci2025: { direct: "pillar no=1 componentno=1.2 I-005", indirect: "" },
  thematicArea: "literacy-basic",
  cycle: "",
  linkageScores: { sdgScore: 4, isoScore: 3, sciScore: 3, linkageType: "discussion" },
  projectPhase: generateProjectPhase(),
},

{
  id: "edu-050",
  department: "शिक्षा विभाग",
  sector: "सामाजिक विकास",
  subSector: "शिक्षा",
  mainProgram: "विविध",
  programName: "स्रोत केन्द्र स्तरमा विद्यार्थी अतिरिक्त क्रियाकलाप (प्रतियोगिता) सञ्चालन",
  budget: 2500,
  budgetCode: "",
  sdg: { direct: "4.7", indirect: "" },
  iso37120: { direct: "Education policy and planning", indirect: "" },
  sci2025: { direct: "pillar no=3 componentno=3.9 I-062", indirect: "" },
  thematicArea: "literacy-basic",
  cycle: "",
  linkageScores: { sdgScore: 3, isoScore: 3, sciScore: 3, linkageType: "declaration" },
  projectPhase: generateProjectPhase(),
},

{
  id: "edu-051",
  department: "शिक्षा विभाग",
  sector: "सामाजिक विकास",
  subSector: "शिक्षा",
  mainProgram: "विविध",
  programName: "विद्यालयहरूका लागि सूचना प्रविधि सपोर्ट युनिट सञ्चालन (जनशक्ति सहित)",
  budget: 3500,
  budgetCode: "",
  sdg: { direct: "4.a", indirect: "" },
  iso37120: { direct: "Education policy and planning", indirect: "" },
  sci2025: { direct: "pillar no=1 componentno=1.2 I-005", indirect: "" },
  thematicArea: "digital-education",
  cycle: "",
  linkageScores: { sdgScore: 3, isoScore: 3, sciScore: 4, linkageType: "research" },
  projectPhase: generateProjectPhase(),
},

{
  id: "edu-052",
  department: "शिक्षा विभाग",
  sector: "सामाजिक विकास",
  subSector: "शिक्षा",
  mainProgram: "अनौपचारिक शिक्षा कार्यक्रम",
  programName: "स्काउट अन्तर्गतका विद्यार्थी लक्षित कार्यक्रम सञ्चालन",
  budget: 5000,
  budgetCode: "",
  sdg: { direct: "4.7", indirect: "" },
  iso37120: { direct: "Education policy and planning", indirect: "" },
  sci2025: { direct: "pillar no=1 componentno=1.2 I-006", indirect: "" },
  thematicArea: "teacher-training",
  cycle: "",
  linkageScores: { sdgScore: 3, isoScore: 2, sciScore: 3, linkageType: "discussion" },
  projectPhase: generateProjectPhase(),
},

{
  id: "edu-053",
  department: "शिक्षा विभाग",
  sector: "सामाजिक विकास",
  subSector: "शिक्षा",
  mainProgram: "विविध",
  programName: "कक्षा ४–८ का विद्यार्थीका लागि शैक्षिक अवलोकन भ्रमण (चिडियाखाना, म्युजियम, पुस्तकालय आदि)",
  budget: 81000,
  budgetCode: "",
  sdg: { direct: "4.7", indirect: "" },
  iso37120: { direct: "Education policy and planning", indirect: "" },
  sci2025: { direct: "pillar no=3 componentno=3.9 I-062", indirect: "" },
  thematicArea: "literacy-basic",
  cycle: "",
  linkageScores: { sdgScore: 3, isoScore: 3, sciScore: 3, linkageType: "declaration" },
  projectPhase: generateProjectPhase(),
},

{
  id: "edu-054",
  department: "शिक्षा विभाग",
  sector: "सामाजिक विकास",
  subSector: "शिक्षा",
  mainProgram: "विद्धार्थी प्रोत्साहन तथा छात्रवृत्ति कार्यक्रम",
  programName: "ECD–कक्षा ५ का विद्यार्थीका लागि दिवा खाजा थप अनुदान (प्रतिदिन रु १५)",
  budget: 135000,
  budgetCode: "",
  sdg: { direct: "2.1", indirect: "" },
  iso37120: { direct: "Education policy and planning", indirect: "" },
  sci2025: { direct: "pillar no=2 componentno=2.5 I-026", indirect: "" },
  thematicArea: "school-infra",
  cycle: "",
  linkageScores: { sdgScore: 4, isoScore: 2, sciScore: 3, linkageType: "declaration" },
  projectPhase: generateProjectPhase(),
},

{
  id: "edu-055",
  department: "शिक्षा विभाग",
  sector: "सामाजिक विकास",
  subSector: "शिक्षा",
  mainProgram: "विद्धार्थी प्रोत्साहन तथा छात्रवृत्ति कार्यक्रम",
  programName: "कक्षा ६–१० का विद्यार्थीका लागि दिवा खाजा अनुदान (प्रतिदिन रु ३०)",
  budget: 500,
  budgetCode: "",
  sdg: { direct: "2.1", indirect: "" },
  iso37120: { direct: "Education policy and planning", indirect: "" },
  sci2025: { direct: "pillar no=1 componentno=1.2 I-006", indirect: "" },
  thematicArea: "school-infra",
  cycle: "",
  linkageScores: { sdgScore: 3, isoScore: 2, sciScore: 2, linkageType: "declaration" },
  projectPhase: generateProjectPhase(),
},

{
  id: "edu-056",
  department: "शिक्षा विभाग",
  sector: "सामाजिक विकास",
  subSector: "शिक्षा",
  mainProgram: "विविध",
  programName: "होस्टेलहरूको अनुगमन तथा प्रतिवेदन",
  budget: 15000,
  budgetCode: "",
  sdg: { direct: "4.a", indirect: "" },
  iso37120: { direct: "Education policy and planning", indirect: "" },
  sci2025: { direct: "pillar no=2 componentno=2.5 I-026", indirect: "" },
  thematicArea: "monitoring-regulation",
  cycle: "",
  linkageScores: { sdgScore: 3, isoScore: 3, sciScore: 3, linkageType: "concurrence" },
  projectPhase: generateProjectPhase(),
},

{
  id: "edu-057",
  department: "शिक्षा विभाग",
  sector: "सामाजिक विकास",
  subSector: "शिक्षा",
  mainProgram: "पाठ्यक्रम र पाठ्यसामग्री वितरण कार्यक्रम",
  programName: "काठमाडौँको मौलिक सभ्यता समेटिएको संक्षिप्त पाठ्यक्रम तयार गरी कलेजहरुमा अतिरिक्त कक्षा संचालन",
  budget: 500,
  budgetCode: "4.1",
  sdg: { direct: "4.1", indirect: "NO" },
  iso37120: { direct: "EDU-6 (Access to free or affordable education materials and services)", indirect: "NO" },
  sci2025: { direct: "pillar no=3 componentno=3.9 I-061", indirect: "" },
  thematicArea: "literacy-basic",
  cycle: "",
  linkageScores: { sdgScore: 3, isoScore: 3, sciScore: 2, linkageType: "research" },
  projectPhase: generateProjectPhase(),
},

{
  id: "edu-058",
  department: "शिक्षा विभाग",
  sector: "सामाजिक विकास",
  subSector: "शिक्षा",
  mainProgram: "विविध",
  programName: "विद्यालयस्तरमा नेपाल स्काउट कार्यक्रम सञ्चालन",
  budget: 500,
  budgetCode: "4.1",
  sdg: { direct: "4.1", indirect: "NO" },
  iso37120: { direct: "6.EDU-(Number of teachers / education staff per 1,000 students)", indirect: "NO" },
  sci2025: { direct: "pillar no=2 componentno=2.5 I-026", indirect: "" },
  thematicArea: "teacher-training",
  cycle: "",
  linkageScores: { sdgScore: 3, isoScore: 3, sciScore: 2, linkageType: "declaration" },
  projectPhase: generateProjectPhase(),
},

{
  id: "edu-059",
  department: "शिक्षा विभाग",
  sector: "सामाजिक विकास",
  subSector: "शिक्षा",
  mainProgram: "विविध",
  programName: "नेवा: स्यनामी नेपाल मण्डल शैक्षिक तालिम सञ्चालन अनुदान",
  budget: 500,
  budgetCode: "4.1",
  sdg: { direct: "4.1", indirect: "NO" },
  iso37120: { direct: "NO", indirect: "" },
  sci2025: { direct: "pillar no=1 componentno=1.2 I-006", indirect: "" },
  thematicArea: "teacher-training",
  cycle: "",
  linkageScores: { sdgScore: 3, isoScore: 0, sciScore: 2, linkageType: "discussion" },
  projectPhase: generateProjectPhase(),
},

{
  id: "edu-060",
  department: "शिक्षा विभाग",
  sector: "सामाजिक विकास",
  subSector: "शिक्षा",
  mainProgram: "विविध",
  programName: "नेवा: देय दबू शैक्षिक कार्यक्रम सञ्चालन अनुदान",
  budget: 1000,
  budgetCode: "4.1",
  sdg: { direct: "4.1", indirect: "NO" },
  iso37120: { direct: "NO", indirect: "" },
  sci2025: { direct: "pillar no=1 componentno=1.2 I-007", indirect: "" },
  thematicArea: "teacher-training",
  cycle: "",
  linkageScores: { sdgScore: 3, isoScore: 0, sciScore: 2, linkageType: "discussion" },
  projectPhase: generateProjectPhase(),
},
{
  id: "edu-061",
  department: "शिक्षा विभाग",
  sector: "सामाजिक विकास",
  subSector: "शिक्षा",
  mainProgram: "विविध",
  programName: "निर्मल बाल बिकास केन्द्रलाइ बिद्यालय व्यवस्थापन अनुदान",
  budget: 1000,
  budgetCode: "4.1.1",
  sdg: { direct: "4.1.1", indirect: "NO" },
  iso37120: { direct: "NO", indirect: "" },
  sci2025: { direct: "pillar no=3 componentno=3.9 I-062", indirect: "" },
  thematicArea: "school-infra",
  cycle: "",
  linkageScores: { sdgScore: 3, isoScore: 0, sciScore: 2, linkageType: "declaration" },
  projectPhase: generateProjectPhase(),
},

{
  id: "edu-062",
  department: "शिक्षा विभाग",
  sector: "सामाजिक विकास",
  subSector: "शिक्षा",
  mainProgram: "विविध",
  programName: "सुस्त मनस्थिति तथा पारिवारिक सरसल्लाह केन्द्र लाइ बिद्यालय व्यवस्थापन अनुदान",
  budget: 1500,
  budgetCode: "4.1",
  sdg: { direct: "4.1", indirect: "NO" },
  iso37120: { direct: "6.EDU-(Number of teachers / education staff per 1,000 students)", indirect: "NO" },
  sci2025: { direct: "pillar no=2 componentno=2.5 I-026", indirect: "" },
  thematicArea: "teacher-training",
  cycle: "",
  linkageScores: { sdgScore: 3, isoScore: 3, sciScore: 2, linkageType: "declaration" },
  projectPhase: generateProjectPhase(),
},

{
  id: "edu-063",
  department: "शिक्षा विभाग",
  sector: "सामाजिक विकास",
  subSector: "शिक्षा",
  mainProgram: "विविध",
  programName: "बैङ्कटेस गुरुकुल गौशाला लाइ व्यवस्थापन अनुदान",
  budget: 1500,
  budgetCode: "4.1",
  sdg: { direct: "4.1", indirect: "NO" },
  iso37120: { direct: "6.EDU-(Number of teachers / education staff per 1,000 students)", indirect: "NO" },
  sci2025: { direct: "pillar no=2 componentno=2.5 I-026", indirect: "" },
  thematicArea: "school-infra",
  cycle: "",
  linkageScores: { sdgScore: 3, isoScore: 3, sciScore: 2, linkageType: "declaration" },
  projectPhase: generateProjectPhase(),
},

{
  id: "edu-064",
  department: "शिक्षा विभाग",
  sector: "सामाजिक विकास",
  subSector: "शिक्षा",
  mainProgram: "विविध",
  programName: "धर्म कृति बिहार लाइ व्यवस्थापन अनुदान",
  budget: 1500,
  budgetCode: "11.4.1",
  sdg: { direct: "11.4.1", indirect: "NO" },
  iso37120: { direct: "6.EDU-(Number of teachers / education staff per 1,000 students)", indirect: "NO" },
  sci2025: { direct: "pillar no=2 componentno=2.5 I-026", indirect: "" },
  thematicArea: "literacy-basic",
  cycle: "",
  linkageScores: { sdgScore: 3, isoScore: 3, sciScore: 2, linkageType: "discussion" },
  projectPhase: generateProjectPhase(),
},

{
  id: "edu-065",
  department: "शिक्षा विभाग",
  sector: "सामाजिक विकास",
  subSector: "शिक्षा",
  mainProgram: "विविध",
  programName: "परियति शिक्षा लाइ व्यवस्थापन अनुदान",
  budget: 1500,
  budgetCode: "4.1",
  sdg: { direct: "4.1", indirect: "NO" },
  iso37120: { direct: "6.EDU-(Number of teachers / education staff per 1,000 students)", indirect: "NO" },
  sci2025: { direct: "pillar no=2 componentno=2.5 I-026", indirect: "" },
  thematicArea: "school-infra",
  cycle: "",
  linkageScores: { sdgScore: 3, isoScore: 3, sciScore: 2, linkageType: "concurrence" },
  projectPhase: generateProjectPhase(),
},

{
  id: "edu-066",
  department: "शिक्षा विभाग",
  sector: "सामाजिक विकास",
  subSector: "शिक्षा",
  mainProgram: "विविध",
  programName: "रत्न राज्य क्याम्पसलाई नेपाल भाषा अध्यापनको लागि अनुदान",
  budget: 2000,
  budgetCode: "4.1",
  sdg: { direct: "4.1", indirect: "NO" },
  iso37120: { direct: "6.EDU-(Number of teachers / education staff per 1,000 students)", indirect: "NO" },
  sci2025: { direct: "pillar no=2 componentno=2.5 I-026", indirect: "" },
  thematicArea: "literacy-basic",
  cycle: "",
  linkageScores: { sdgScore: 3, isoScore: 3, sciScore: 2, linkageType: "declaration" },
  projectPhase: generateProjectPhase(),
},

{
  id: "edu-067",
  department: "शिक्षा विभाग",
  sector: "सामाजिक विकास",
  subSector: "शिक्षा",
  mainProgram: "विविध",
  programName: "केन्द्रिय बहिरा बिद्यालयलाइ बिद्यालय व्यवस्थापन अनुदान",
  budget: 2500,
  budgetCode: "4.A",
  sdg: { direct: "4.A", indirect: "NO" },
  iso37120: { direct: "6.EDU-(Number of teachers / education staff per 1,000 students)", indirect: "NO" },
  sci2025: { direct: "pillar no=2 componentno=2.5 I-026", indirect: "" },
  thematicArea: "literacy-basic",
  cycle: "",
  linkageScores: { sdgScore: 3, isoScore: 3, sciScore: 2, linkageType: "research" },
  projectPhase: generateProjectPhase(),
},

{
  id: "edu-068",
  department: "शिक्षा विभाग",
  sector: "सामाजिक विकास",
  subSector: "शिक्षा",
  mainProgram: "विविध",
  programName: "सुत्केरी विदा बसेका शिक्षकहरुको कक्षा व्यवस्थापनका लागि अनुदान",
  budget: 4200,
  budgetCode: "4.C",
  sdg: { direct: "4.C", indirect: "NO" },
  iso37120: { direct: "6.EDU-(Number of teachers / education staff per 1,000 students)", indirect: "NO" },
  sci2025: { direct: "pillar no=2 componentno=2.5 I-026", indirect: "" },
  thematicArea: "teacher-training",
  cycle: "",
  linkageScores: { sdgScore: 3, isoScore: 3, sciScore: 2, linkageType: "concurrence" },
  projectPhase: generateProjectPhase(),
},

{
  id: "edu-069",
  department: "शिक्षा विभाग",
  sector: "सामाजिक विकास",
  subSector: "शिक्षा",
  mainProgram: "विविध",
  programName: "कार्य सम्पादन सूचकका आधारमा सामुदायिक सिकाइ केन्द्रका लागि अनुदान (प्रति सिकाइ केन्द्र ३ लाख का दरले शसर्त अनुदान )",
  budget: 7150,
  budgetCode: "4.C",
  sdg: { direct: "4.C", indirect: "NO" },
  iso37120: { direct: "6.EDU-(Number of teachers / education staff per 1,000 students)", indirect: "NO" },
  sci2025: { direct: "pillar no=2 componentno=2.5 I-026", indirect: "" },
  thematicArea: "literacy-basic",
  cycle: "",
  linkageScores: { sdgScore: 3, isoScore: 3, sciScore: 2, linkageType: "research" },
  projectPhase: generateProjectPhase(),
},

{
  id: "edu-070",
  department: "शिक्षा विभाग",
  sector: "सामाजिक विकास",
  subSector: "शिक्षा",
  mainProgram: "विविध",
  programName: "गणित विज्ञान ल्याब निर्माणका लागि विद्यालयलाई अनुदान (११ वटा)",
  budget: 7500,
  budgetCode: "4.A",
  sdg: { direct: "4.A", indirect: "NO" },
  iso37120: { direct: "6.EDU-(Number of teachers / education staff per 1,000 students)", indirect: "NO" },
  sci2025: { direct: "pillar no=2 componentno=2.5 I-026", indirect: "" },
  thematicArea: "school-infra",
  cycle: "",
  linkageScores: { sdgScore: 3, isoScore: 3, sciScore: 2, linkageType: "concurrence" },
  projectPhase: generateProjectPhase(),
},

{
  id: "edu-071",
  department: "शिक्षा विभाग",
  sector: "सामाजिक विकास",
  subSector: "शिक्षा",
  mainProgram: "प्राविधिक शिक्षा तथा व्यवसायिक तालिम कार्यक्रम",
  programName: "महानगरपालिकाको अनुमतिमा सञ्चालित प्राविधिकधार तर्फका विद्यालयहरुलाई सञ्चालन अनुदान पहिलो किस्ता (प्रति विद्यार्थी १५००० मध्ये ७५०० का दरले )",
  budget: 8400,
  budgetCode: "4.3",
  sdg: { direct: "4.3", indirect: "8.6" },
  iso37120: { direct: "6.EDU-(Number of teachers / education staff per 1,000 students)", indirect: "NO" },
  sci2025: { direct: "pillar no=2 componentno=2.5 I-026", indirect: "" },
  thematicArea: "literacy-basic",
  cycle: "",
  linkageScores: { sdgScore: 3, isoScore: 3, sciScore: 2, linkageType: "declaration" },
  projectPhase: generateProjectPhase(),
},

{
  id: "edu-072",
  department: "शिक्षा विभाग",
  sector: "सामाजिक विकास",
  subSector: "शिक्षा",
  mainProgram: "विविध",
  programName: "बिद्यालय नर्स कार्यक्रम संचालन का लागि आवस्यक सामग्री खरिद अनुदान (प्रति बिद्यालय १ लाख का दरले )",
  budget: 10000,
  budgetCode: "3.8.1",
  sdg: { direct: "3.8.1", indirect: "NO" },
  iso37120: { direct: "6.EDU-(Number of teachers / education staff per 1,000 students)", indirect: "NO" },
  sci2025: { direct: "pillar no=2 componentno=2.5 I-026", indirect: "" },
  thematicArea: "monitoring-regulation",
  cycle: "",
  linkageScores: { sdgScore: 3, isoScore: 3, sciScore: 2, linkageType: "declaration" },
  projectPhase: generateProjectPhase(),
},

{
  id: "edu-073",
  department: "शिक्षा विभाग",
  sector: "सामाजिक विकास",
  subSector: "शिक्षा",
  mainProgram: "विविध",
  programName: "बाल व्यवसायी माध्यमिक विद्यालयलाई समावेशी शिक्षा, बालमैत्री वातावरण, पूर्वाधार विकासका लागि अनुदान",
  budget: 13500,
  budgetCode: "4.6",
  sdg: { direct: "4.6", indirect: "NO" },
  iso37120: { direct: "6.EDU-(Number of teachers / education staff per 1,000 students)", indirect: "NO" },
  sci2025: { direct: "pillar no=2 componentno=2.5 I-061", indirect: "" },
  thematicArea: "literacy-basic",
  cycle: "",
  linkageScores: { sdgScore: 3, isoScore: 3, sciScore: 2, linkageType: "declaration" },
  projectPhase: generateProjectPhase(),
},

{
  id: "edu-074",
  department: "शिक्षा विभाग",
  sector: "सामाजिक विकास",
  subSector: "शिक्षा",
  mainProgram: "विविध",
  programName: "बिद्यालय नर्स कार्यक्रम अनुदान",
  budget: 40970,
  budgetCode: "3.8",
  sdg: { direct: "3.8", indirect: "8.5" },
  iso37120: { direct: "6.EDU-(Number of teachers / education staff per 1,000 students)", indirect: "NO" },
  sci2025: { direct: "pillar no=2 componentno=2.5 I-007", indirect: "" },
  thematicArea: "monitoring-regulation",
  cycle: "",
  linkageScores: { sdgScore: 3, isoScore: 3, sciScore: 2, linkageType: "declaration" },
  projectPhase: generateProjectPhase(),
},

{
  id: "edu-075",
  department: "शिक्षा विभाग",
  sector: "सामाजिक विकास",
  subSector: "शिक्षा",
  mainProgram: "प्राविधिक शिक्षा तथा व्यवसायिक तालिम कार्यक्रम",
  programName: "प्राविधिकधार तर्फका विद्यालयका प्रशिक्षक, सहायक प्रशिक्षक र शिक्षकको तलब भत्ता र कार्यक्रम अनुदान (८ विद्यालयमा सप्रशिक्षक १६ प्रशिक्षक १६ र ब प्रशिक्षक ३२ जनाकोलागि)",
  budget: 80000,
  budgetCode: "4.C",
  sdg: { direct: "4.C", indirect: "NO" },
  iso37120: { direct: "6.EDU-(Number of teachers / education staff per 1,000 students)", indirect: "NO" },
  sci2025: { direct: "pillar no=3 componentno=3.9 I-061", indirect: "" },
  thematicArea: "literacy-basic",
  cycle: "",
  linkageScores: { sdgScore: 3, isoScore: 3, sciScore: 2, linkageType: "declaration" },
  projectPhase: generateProjectPhase(),
},
{
  id: "edu-076",
  department: "शिक्षा विभाग",
  sector: "सामाजिक विकास",
  subSector: "शिक्षा",
  mainProgram: "विविध",
  programName: "निशुल्क शिक्षा कार्यान्वयन को लागि अध्ययन प्रतिबेदनको आधारमा बिद्यालय लाइ अनुदान",
  budget: 2000,
  budgetCode: "4.A",
  sdg: { direct: "4.A", indirect: "NO" },
  iso37120: { direct: "6.EDU-(Number of teachers / education staff per 1,000 students)", indirect: "NO" },
  sci2025: { direct: "pillar no=3 componentno=3.9 I-061", indirect: "" },
  thematicArea: "literacy-basic",
  cycle: "",
  linkageScores: { sdgScore: 3, isoScore: 3, sciScore: 2, linkageType: "discussion" },
  projectPhase: generateProjectPhase(),
},

{
  id: "edu-077",
  department: "शिक्षा विभाग",
  sector: "सामाजिक विकास",
  subSector: "शिक्षा",
  mainProgram: "विविध",
  programName: "भृकुटी मण्डप स्थित काठमाडौं उपत्यका सार्वजनिक पुस्तकालय सुदृढीकरण र पुस्तक खरीद अनुदान",
  budget: 5000,
  budgetCode: "",
  sdg: { direct: "NO", indirect: "NO" },
  iso37120: { direct: "6.EDU-(Number of teachers / education staff per 1,000 students)", indirect: "NO" },
  sci2025: { direct: "pillar no=2 componentno=2.5 I-026", indirect: "" },
  thematicArea: "monitoring-regulation",
  cycle: "",
  linkageScores: { sdgScore: 0, isoScore: 3, sciScore: 2, linkageType: "discussion" },
  projectPhase: generateProjectPhase(),
},

{
  id: "edu-078",
  department: "शिक्षा विभाग",
  sector: "सामाजिक विकास",
  subSector: "शिक्षा",
  mainProgram: "विविध",
  programName: "कक्षा ११ को छात्रवृत्ति परीक्षा संचालन, नतिजा प्रकाशन तथा व्यवस्थापन",
  budget: 1000,
  budgetCode: "4.6",
  sdg: { direct: "4.6", indirect: "4.1" },
  iso37120: { direct: "6.EDU-(Number of teachers / education staff per 1,000 students)", indirect: "NO" },
  sci2025: { direct: "pillar no=2 componentno=2.5 I-026", indirect: "" },
  thematicArea: "monitoring-regulation",
  cycle: "",
  linkageScores: { sdgScore: 3, isoScore: 3, sciScore: 2, linkageType: "concurrence" },
  projectPhase: generateProjectPhase(),
},

{
  id: "edu-079",
  department: "शिक्षा विभाग",
  sector: "सामाजिक विकास",
  subSector: "शिक्षा",
  mainProgram: "शैक्षिक पूर्वाधार निर्माण कार्यक्रम",
  programName: "छात्रवृत्ति लगायतको उत्तरपुस्तिका परीक्षण गर्ने OMR/OCR मेसिन स्यानर खरिद",
  budget: 5220,
  budgetCode: "",
  sdg: { direct: "4.A", indirect: "NO" },
  iso37120: { direct: "6.EDU-(Number of teachers / education staff per 1,000 students)", indirect: "NO" },
  sci2025: { direct: "pillar no=1 componentno=1.2 I-005", indirect: "" },
  thematicArea: "digital-education",
  cycle: "",
  linkageScores: { sdgScore: 3, isoScore: 3, sciScore: 2, linkageType: "concurrence" },
  projectPhase: generateProjectPhase(),
},

{
  id: "edu-080",
  department: "शिक्षा विभाग",
  sector: "सामाजिक विकास",
  subSector: "शिक्षा",
  mainProgram: "विविध",
  programName: "सामुदायिक विद्यालयका शिक्षक तथा विद्यार्थीको हाजिरी व्यवस्थापन गर्न हाजिरी उपकरण खरिदका लागि अनुदान",
  budget: 1000,
  budgetCode: "",
  sdg: { direct: "4.A", indirect: "NO" },
  iso37120: { direct: "6.EDU-(Number of teachers / education staff per 1,000 students)", indirect: "NO" },
  sci2025: { direct: "pillar no=1 componentno=1.2 I-006", indirect: "" },
  thematicArea: "digital-education",
  cycle: "",
  linkageScores: { sdgScore: 3, isoScore: 3, sciScore: 2, linkageType: "concurrence" },
  projectPhase: generateProjectPhase(),
},

{
  id: "edu-081",
  department: "शिक्षा विभाग",
  sector: "सामाजिक विकास",
  subSector: "शिक्षा",
  mainProgram: "विविध",
  programName: "Emotional Learning Corner स्थापना (कक्षा कोठामा भावनात्मक शिक्षा र व्यवहार व्यवस्थापन अभ्यास गरिने ठाउँ)",
  budget: 1500,
  budgetCode: "",
  sdg: { direct: "4.A", indirect: "NO" },
  iso37120: { direct: "6.EDU-(Number of teachers / education staff per 1,000 students)", indirect: "NO" },
  sci2025: { direct: "pillar no=3 componentno=3.9 I-062", indirect: "" },
  thematicArea: "teacher-training",
  cycle: "",
  linkageScores: { sdgScore: 3, isoScore: 3, sciScore: 2, linkageType: "discussion" },
  projectPhase: generateProjectPhase(),
},

{
  id: "edu-082",
  department: "शिक्षा विभाग",
  sector: "सामाजिक विकास",
  subSector: "शिक्षा",
  mainProgram: "विविध",
  programName: "सार्वजनिक पुस्तकालय र खुला अध्ययन केन्द्र स्थापना तथा संचालन",
  budget: 20000,
  budgetCode: "4.A",
  sdg: { direct: "4.A", indirect: "NO" },
  iso37120: { direct: "6.EDU-(Number of teachers / education staff per 1,000 students)", indirect: "NO" },
  sci2025: { direct: "pillar no=3 componentno=3.9 I-062", indirect: "" },
  thematicArea: "monitoring-regulation",
  cycle: "",
  linkageScores: { sdgScore: 3, isoScore: 3, sciScore: 2, linkageType: "concurrence" },
  projectPhase: generateProjectPhase(),
},

{
  id: "edu-083",
  department: "शिक्षा विभाग",
  sector: "सामाजिक विकास",
  subSector: "शिक्षा",
  mainProgram: "विविध",
  programName: "वडा नं २४ मा विद्यालय भवन निर्माण (CPC मार्फत गुरुयोजना बमोजिम)",
  budget: 30000,
  budgetCode: "4.A",
  sdg: { direct: "4.A", indirect: "NO" },
  iso37120: { direct: "6.EDU-(Number of teachers / education staff per 1,000 students)", indirect: "NO" },
  sci2025: { direct: "pillar no=3 componentno=3.9 I-061", indirect: "" },
  thematicArea: "school-infra",
  cycle: "",
  linkageScores: { sdgScore: 3, isoScore: 3, sciScore: 2, linkageType: "concurrence" },
  projectPhase: generateProjectPhase(),
},

{
  id: "edu-084",
  department: "शिक्षा विभाग",
  sector: "सामाजिक विकास",
  subSector: "शिक्षा",
  mainProgram: "अनौपचारिक शिक्षा कार्यक्रम",
  programName: "पुस्तक रहित शुक्रवार (Book Free Friday- कक्षा ४-८ सृजनात्मक सिकाइ) का लागि विद्यालयलाई अनुदान",
  budget: 15000,
  budgetCode: "4.6",
  sdg: { direct: "4.6", indirect: "NO" },
  iso37120: { direct: "6.EDU-(Number of teachers / education staff per 1,000 students)", indirect: "NO" },
  sci2025: { direct: "pillar no=1 componentno=1.2 I-005", indirect: "" },
  thematicArea: "literacy-basic",
  cycle: "",
  linkageScores: { sdgScore: 3, isoScore: 3, sciScore: 2, linkageType: "declaration" },
  projectPhase: generateProjectPhase(),
},

{
  id: "edu-085",
  department: "शिक्षा विभाग",
  sector: "सामाजिक विकास",
  subSector: "शिक्षा",
  mainProgram: "अनौपचारिक शिक्षा कार्यक्रम",
  programName: "पुस्तक रहित शुक्रबार (Book Free Friday- कक्षा ९ शिक्षामा सिप ) कार्यान्वयनका लागि विद्यालयलाई अनुदान",
  budget: 5000,
  budgetCode: "4.6",
  sdg: { direct: "4.6", indirect: "NO" },
  iso37120: { direct: "6.EDU-(Number of teachers / education staff per 1,000 students)", indirect: "NO" },
  sci2025: { direct: "pillar no=3 componentno=3.9 I-061", indirect: "" },
  thematicArea: "literacy-basic",
  cycle: "",
  linkageScores: { sdgScore: 3, isoScore: 3, sciScore: 2, linkageType: "declaration" },
  projectPhase: generateProjectPhase(),
},
{
  id: "edu-086",
  department: "शिक्षा विभाग",
  sector: "सामाजिक विकास",
  subSector: "शिक्षा",
  mainProgram: "अनौपचारिक शिक्षा कार्यक्रम",
  programName: "Book Free Friday अन्तर्गत संगीत विधाका कार्यक्रम सञ्चालन गर्न सांस्कृतिक संस्थान संग G to G",
  budget: 10000,
  budgetCode: "4.7",
  sdg: { direct: "4.7", indirect: "NO" },
  iso37120: { direct: "6.EDU-(Number of teachers / education staff per 1,000 students)", indirect: "NO" },
  sci2025: { direct: "pillar no=1 componentno=1.2 I-006", indirect: "" },
  thematicArea: "literacy-basic",
  cycle: "",
  linkageScores: { sdgScore: 3, isoScore: 3, sciScore: 2, linkageType: "concurrence" },
  projectPhase: generateProjectPhase(),
},

{
  id: "edu-087",
  department: "शिक्षा विभाग",
  sector: "सामाजिक विकास",
  subSector: "शिक्षा",
  mainProgram: "अनौपचारिक शिक्षा कार्यक्रम",
  programName: "Book Free Friday अन्तर्गत म्यूरल आर्ट, स्केचिङ र स्कल्चर कार्यक्रम सञ्चालन (नेपाल ललितकला प्रज्ञा प्रतिष्ठान संग G to G)",
  budget: 16000,
  budgetCode: "4.7",
  sdg: { direct: "4.7", indirect: "NO" },
  iso37120: { direct: "6.EDU-(Number of teachers / education staff per 1,000 students)", indirect: "NO" },
  sci2025: { direct: "pillar no=1 componentno=1.2 I-006", indirect: "" },
  thematicArea: "literacy-basic",
  cycle: "",
  linkageScores: { sdgScore: 3, isoScore: 3, sciScore: 2, linkageType: "concurrence" },
  projectPhase: generateProjectPhase(),
},

{
  id: "edu-088",
  department: "शिक्षा विभाग",
  sector: "सामाजिक विकास",
  subSector: "शिक्षा",
  mainProgram: "अनौपचारिक शिक्षा कार्यक्रम",
  programName: "विद्यार्थीको नतिजा सुधारका लागि कक्षा ८ र १० मा अतिरिक्त कक्षा सञ्चालन",
  budget: 90000,
  budgetCode: "4.6",
  sdg: { direct: "4.6", indirect: "NO" },
  iso37120: { direct: "6.EDU-(Number of teachers / education staff per 1,000 students)", indirect: "NO" },
  sci2025: { direct: "pillar no=1 componentno=1.2 I-006", indirect: "" },
  thematicArea: "teacher-training",
  cycle: "",
  linkageScores: { sdgScore: 3, isoScore: 3, sciScore: 2, linkageType: "research" },
  projectPhase: generateProjectPhase(),
},

{
  id: "edu-089",
  department: "शिक्षा विभाग",
  sector: "सामाजिक विकास",
  subSector: "शिक्षा",
  mainProgram: "शैक्षिक पूर्वाधार निर्माण कार्यक्रम",
  programName: "विद्यालय पूर्वाधार विकास कार्यक्रम",
  budget: 3000,
  budgetCode: "4.A",
  sdg: { direct: "4.A", indirect: "9.C" },
  iso37120: { direct: "6.EDU-(Number of teachers / education staff per 1,000 students)", indirect: "NO" },
  sci2025: { direct: "pillar no=1 componentno=1.2 I-006", indirect: "" },
  thematicArea: "school-infra",
  cycle: "",
  linkageScores: { sdgScore: 3, isoScore: 3, sciScore: 2, linkageType: "concurrence" },
  projectPhase: generateProjectPhase(),
},

{
  id: "edu-090",
  department: "शिक्षा विभाग",
  sector: "सामाजिक विकास",
  subSector: "शिक्षा",
  mainProgram: "विविध",
  programName: "दशै र तिहारको विचमा SEE सहायता शिविर सञ्चालन",
  budget: 60000,
  budgetCode: "4.1.2",
  sdg: { direct: "4.1.2", indirect: "NO" },
  iso37120: { direct: "6.EDU-(Number of teachers / education staff per 1,000 students)", indirect: "NO" },
  sci2025: { direct: "pillar no=1 componentno=1.2 I-006", indirect: "" },
  thematicArea: "monitoring-regulation",
  cycle: "",
  linkageScores: { sdgScore: 3, isoScore: 3, sciScore: 2, linkageType: "discussion" },
  projectPhase: generateProjectPhase(),
},

{
  id: "edu-091",
  department: "शिक्षा विभाग",
  sector: "सामाजिक विकास",
  subSector: "शिक्षा",
  mainProgram: "विविध",
  programName: "स्मार्ट बोर्ड खरिदको लागि सामुदायिक बिद्यालयहरुलाई अनुदान",
  budget: 70000,
  budgetCode: "",
  sdg: { direct: "4.A", indirect: "NO" },
  iso37120: { direct: "6.EDU-(Number of teachers / education staff per 1,000 students)", indirect: "NO" },
  sci2025: { direct: "pillar no=3 componentno=3.9 I-062", indirect: "" },
  thematicArea: "digital-education",
  cycle: "",
  linkageScores: { sdgScore: 3, isoScore: 3, sciScore: 2, linkageType: "concurrence" },
  projectPhase: generateProjectPhase(),
},

{
  id: "edu-092",
  department: "शिक्षा विभाग",
  sector: "सामाजिक विकास",
  subSector: "शिक्षा",
  mainProgram: "विविध",
  programName: "डेस्क वेन्च खरिदका लागि सामुदायिक विद्यालयलाई अनुदान",
  budget: 200,
  budgetCode: "",
  sdg: { direct: "4.A", indirect: "NO" },
  iso37120: { direct: "6.EDU-(Number of teachers / education staff per 1,000 students)", indirect: "NO" },
  sci2025: { direct: "pillar no=3 componentno=3.9 I-061", indirect: "" },
  thematicArea: "school-infra",
  cycle: "",
  linkageScores: { sdgScore: 3, isoScore: 3, sciScore: 2, linkageType: "concurrence" },
  projectPhase: generateProjectPhase(),
},

{
  id: "edu-093",
  department: "शिक्षा विभाग",
  sector: "सामाजिक विकास",
  subSector: "शिक्षा",
  mainProgram: "विविध",
  programName: "कार्यक्रमको नियमित बैठक तथा समिक्षा",
  budget: 200,
  budgetCode: "4.C",
  sdg: { direct: "4.C", indirect: "NO" },
  iso37120: { direct: "6.EDU-(Number of teachers / education staff per 1,000 students)", indirect: "NO" },
  sci2025: { direct: "pillar no=2 componentno=2.5 I-026", indirect: "" },
  thematicArea: "monitoring-regulation",
  cycle: "",
  linkageScores: { sdgScore: 3, isoScore: 3, sciScore: 2, linkageType: "discussion" },
  projectPhase: generateProjectPhase(),
},

{
  id: "edu-094",
  department: "शिक्षा विभाग",
  sector: "सामाजिक विकास",
  subSector: "शिक्षा",
  mainProgram: "विविध",
  programName: "कार्यक्रमको नियमित अनुगमन तथा प्रतिवेदन",
  budget: 3000,
  budgetCode: "4.C",
  sdg: { direct: "4.C", indirect: "NO" },
  iso37120: { direct: "6.EDU-(Number of teachers / education staff per 1,000 students)", indirect: "NO" },
  sci2025: { direct: "pillar no=2 componentno=2.5 I-026", indirect: "" },
  thematicArea: "monitoring-regulation",
  cycle: "",
  linkageScores: { sdgScore: 3, isoScore: 3, sciScore: 2, linkageType: "research" },
  projectPhase: generateProjectPhase(),
},

{
  id: "edu-095",
  department: "शिक्षा विभाग",
  sector: "सामाजिक विकास",
  subSector: "शिक्षा",
  mainProgram: "विविध",
  programName: "विद्यालयका Book Free Friday अन्तरगतका फोकल शिक्षकहरुको क्षमता विकास तालिम",
  budget: 5000,
  budgetCode: "4.C",
  sdg: { direct: "4.C", indirect: "NO" },
  iso37120: { direct: "6.EDU-(Number of teachers / education staff per 1,000 students)", indirect: "NO" },
  sci2025: { direct: "pillar no=1 componentno=1.2 I-007", indirect: "" },
  thematicArea: "teacher-training",
  cycle: "",
  linkageScores: { sdgScore: 3, isoScore: 3, sciScore: 2, linkageType: "concurrence" },
  projectPhase: generateProjectPhase(),
},

{
  id: "edu-096",
  department: "शिक्षा विभाग",
  sector: "सामाजिक विकास",
  subSector: "शिक्षा",
  mainProgram: "विविध",
  programName: "आवश्यकता र मागका आधारमा शिक्षकहरुको क्षमता विकास तालिम सञ्चालन",
  budget: 5000,
  budgetCode: "4.4",
  sdg: { direct: "4.4", indirect: "NO" },
  iso37120: { direct: "6.EDU-(Number of teachers / education staff per 1,000 students)", indirect: "NO" },
  sci2025: { direct: "pillar no=1 componentno=1.2 I-007", indirect: "" },
  thematicArea: "teacher-training",
  cycle: "",
  linkageScores: { sdgScore: 3, isoScore: 3, sciScore: 2, linkageType: "concurrence" },
  projectPhase: generateProjectPhase(),
},

{
  id: "edu-097",
  department: "शिक्षा विभाग",
  sector: "सामाजिक विकास",
  subSector: "शिक्षा",
  mainProgram: "अनौपचारिक शिक्षा कार्यक्रम",
  programName: "शिक्षामा सीप कार्यान्वयनको लागि नेपाल ललितकला प्रज्ञा प्रतिष्ठानसंग G to G सहकार्य",
  budget: 100000,
  budgetCode: "4.4",
  sdg: { direct: "4.4", indirect: "NO" },
  iso37120: { direct: "6.EDU-(Number of teachers / education staff per 1,000 students)", indirect: "NO" },
  sci2025: { direct: "pillar no=1 componentno=1.2 I-007", indirect: "" },
  thematicArea: " literacy-basic",
  cycle: "",
  linkageScores: { sdgScore: 3, isoScore: 3, sciScore: 2, linkageType: "concurrence" },
  projectPhase: generateProjectPhase(),
},

{
  id: "edu-098",
  department: "शिक्षा विभाग",
  sector: "सामाजिक विकास",
  subSector: "शिक्षा",
  mainProgram: "शैक्षिक पूर्वाधार निर्माण कार्यक्रम",
  programName: "सीप कार्यक्रम अन्तर्गत ल्याब निर्माणको लागि बिद्यालयलाई अनुदान",
  budget: 99200,
  budgetCode: "4.A",
  sdg: { direct: "4.A", indirect: "NO" },
  iso37120: { direct: "6.EDU-(Number of teachers / education staff per 1,000 students)", indirect: "NO" },
  sci2025: { direct: "pillar no=1 componentno=1.2 I-007", indirect: "" },
  thematicArea: "school-infra",
  cycle: "",
  linkageScores: { sdgScore: 3, isoScore: 3, sciScore: 2, linkageType: "concurrence" },
  projectPhase: generateProjectPhase(),
},

{
  id: "edu-099",
  department: "शिक्षा विभाग",
  sector: "सामाजिक विकास",
  subSector: "शिक्षा",
  mainProgram: "शैक्षिक पूर्वाधार निर्माण कार्यक्रम",
  programName: "डिजिटल शिक्षण सिकाइ सूचना प्रविधिमैत्री विद्यालय निर्माण",
  budget: 1399,
  budgetCode: "4.A",
  sdg: { direct: "4.A", indirect: "NO" },
  iso37120: { direct: "6.EDU-(Number of teachers / education staff per 1,000 students)", indirect: "NO" },
  sci2025: { direct: "pillar no=1 componentno=1.2 I-006", indirect: "" },
  thematicArea: " digital-education",
  cycle: "",
  linkageScores: { sdgScore: 3, isoScore: 3, sciScore: 2, linkageType: "concurrence" },
  projectPhase: generateProjectPhase(),
},

{
  id: "edu-100",
  department: "शिक्षा विभाग",
  sector: "सामाजिक विकास",
  subSector: "शिक्षा",
  mainProgram: "अनौपचारिक शिक्षा कार्यक्रम",
  programName: "पुस्तक रहित शुक्रवार - सिर्जनशील शिक्षा र बाल सञ्जाल गठन तथा सशक्तिकरण कार्यक्रम",
  budget: 4175,
  budgetCode: "4.A",
  sdg: { direct: "4.A", indirect: "NO" },
  iso37120: { direct: "6.EDU-(Number of teachers / education staff per 1,000 students)", indirect: "NO" },
  sci2025: { direct: "pillar no=1 componentno=1.5 I-013", indirect: "" },
  thematicArea: "literacy-basic",
  cycle: "",
  linkageScores: { sdgScore: 3, isoScore: 3, sciScore: 2, linkageType: "declaration" },
  projectPhase: generateProjectPhase(),
},
{
  id: "edu-101",
  department: "शिक्षा विभाग",
  sector: "सामाजिक विकास",
  subSector: "शिक्षा",
  mainProgram: "अनौपचारिक शिक्षा कार्यक्रम",
  programName: "पुस्तक रहित शुक्रवार - सिर्जनशील शिक्षा (Book Free Friday) तथा बाल सञ्जाल गठन र सशक्तिकरण कार्यक्रम",
  budget: 9500,
  budgetCode: "4.7.1,5.5",
  sdg: { direct: "4.7.1,5.5", indirect: "NO" },
  iso37120: { direct: "6.EDU-(Number of teachers / education staff per 1,000 students)", indirect: "NO" },
  sci2025: { direct: "pillar no=2 componentno=2.5 I-026", indirect: "" },
  thematicArea: "literacy-basic",
  cycle: "",
  linkageScores: { sdgScore: 3, isoScore: 3, sciScore: 2, linkageType: "declaration" },
  projectPhase: generateProjectPhase(),
},
{
  id: "102",
  department: "शिक्षा विभाग",
  sector: "सामाजिक विकास",
  subSector: "शिक्षा",
  mainProgram: "विविध",
  programName: "विद्यार्थीको नतिजा सुधार कार्यक्रमका लागि अतिरिक्त पारिश्रमिक (बिदा वा कार्यालय समय बाहेक)",
  budget: 791,
  budgetCode: "4.C",
  sdg: { direct: "4.C", indirect: "NO" },
  iso37120: { direct: "6.EDU-(Number of teachers / education staff per 1,000 students)", indirect: "NO" },
  sci2025: { direct: "pillar no=2 componentno=2.5 I-026", indirect: "" },
  thematicArea: "teacher-training",
  cycle: "",
  linkageScores: { sdgScore: 3, isoScore: 3, sciScore: 2, linkageType: "declaration" },
  projectPhase: generateProjectPhase(),
},
{
  id: "103",
  department: "शिक्षा विभाग",
  sector: "सामाजिक विकास",
  subSector: "शिक्षा",
  mainProgram: "विविध",
  programName: "SEE सहायता शिविरका लागि शिक्षकलाई अतिरिक्त पारिश्रमिक (दशैं–तिहार बीच तथा जाडो बिदा)",
  budget: 1980,
  budgetCode: "4.C",
  sdg: { direct: "4.C", indirect: "NO" },
  iso37120: { direct: "6.EDU-(Number of teachers / education staff per 1,000 students)", indirect: "NO" },
  sci2025: { direct: "pillar no=2 componentno=2.5 I-026", indirect: "" },
  thematicArea: "teacher-training",
  cycle: "",
  linkageScores: { sdgScore: 3, isoScore: 3, sciScore: 2, linkageType: "declaration" },
  projectPhase: generateProjectPhase(),
},
{
  id: "104",
  department: "शिक्षा विभाग",
  sector: "सामाजिक विकास",
  subSector: "शिक्षा",
  mainProgram: "विविध",
  programName: "SEE सहायता शिविरका लागि विद्यार्थी, शिक्षक तथा सहयोगीका लागि खाजा व्यवस्थापन",
  budget: 2500,
  budgetCode: "4.C",
  sdg: { direct: "4.C", indirect: "NO" },
  iso37120: { direct: "6.EDU-(Number of teachers / education staff per 1,000 students)", indirect: "NO" },
  sci2025: { direct: "pillar no=2 componentno=2.5 I-026", indirect: "" },
  thematicArea: "teacher-training",
  cycle: "",
  linkageScores: { sdgScore: 3, isoScore: 3, sciScore: 2, linkageType: "declaration" },
  projectPhase: generateProjectPhase(),
},
{
  id: "105",
  department: "शिक्षा विभाग",
  sector: "सामाजिक विकास",
  subSector: "शिक्षा",
  mainProgram: "विविध",
  programName: "पुस्तक रहित शुक्रवार (Book Free Friday) अन्तर्गत SEE सहायता शिविर सञ्चालन अनुदान",
  budget: 2000,
  budgetCode: "4.1",
  sdg: { direct: "4.1", indirect: "NO" },
  iso37120: { direct: "6.EDU-(Number of teachers / education staff per 1,000 students)", indirect: "NO" },
  sci2025: { direct: "pillar no=3 componentno=3.9 I-061", indirect: "" },
  thematicArea: "literacy-basic",
  cycle: "",
  linkageScores: { sdgScore: 3, isoScore: 3, sciScore: 2, linkageType: "declaration" },
  projectPhase: generateProjectPhase(),
},
{
  id: "106",
  department: "शिक्षा विभाग",
  sector: "सामाजिक विकास",
  subSector: "शिक्षा",
  mainProgram: "विविध",
  programName: "विद्यार्थी नतिजा सुधार कार्यक्रमका लागि विज्ञ व्यवस्थापन",
  budget: 276000,
  budgetCode: "4.1.1,4.1.2,8.6",
  sdg: { direct: "4.1.1,4.1.2,8.6", indirect: "NO" },
  iso37120: { direct: "6.EDU-(Number of teachers / education staff per 1,000 students)", indirect: "NO" },
  sci2025: { direct: "pillar no=3 componentno=3.9 I-061", indirect: "" },
  thematicArea: "teacher-training",
  cycle: "",
  linkageScores: { sdgScore: 4, isoScore: 3, sciScore: 3, linkageType: "concurrence" },
  projectPhase: generateProjectPhase(),
},
{
  id: "107",
  department: "शिक्षा विभाग",
  sector: "सामाजिक विकास",
  subSector: "शिक्षा",
  mainProgram: "शैक्षिक पूर्वाधार निर्माण कार्यक्रम",
  programName: "विद्यालय पूर्वाधार विकास कार्यक्रम",
  budget: 16000,
  budgetCode: "4.A,9.C",
  sdg: { direct: "4.A,9.C", indirect: "NO" },
  iso37120: { direct: "6.EDU-(Education policy and planning)", indirect: "NO" },
  sci2025: { direct: "pillar no=1 componentno=1.2 I-006", indirect: "" },
  thematicArea: "school-infra",
  cycle: "",
  linkageScores: { sdgScore: 4, isoScore: 4, sciScore: 3, linkageType: "concurrence" },
  projectPhase: generateProjectPhase(),
},
{
  id: "108",
  department: "शिक्षा विभाग",
  sector: "सामाजिक विकास",
  subSector: "शिक्षा",
  mainProgram: "शैक्षिक पूर्वाधार निर्माण कार्यक्रम",
  programName: "विद्यालय निर्माणका लागि गुरुयोजना तयारी",
  budget: 35000,
  budgetCode: "4.A",
  sdg: { direct: "4.A", indirect: "NO" },
  iso37120: { direct: "6.EDU-(Education policy and planning)", indirect: "NO" },
  sci2025: { direct: "pillar no=3 componentno=3.9 I-061", indirect: "" },
  thematicArea: "school-infra",
  cycle: "",
  linkageScores: { sdgScore: 4, isoScore: 4, sciScore: 3, linkageType: "research" },
  projectPhase: generateProjectPhase(),
},
{
  id: "109",
  department: "शिक्षा विभाग",
  sector: "सामाजिक विकास",
  subSector: "शिक्षा",
  mainProgram: "विविध",
  programName: "सुन्दर विद्यालय गुरुयोजना कार्यान्वयन (फर्निचर, पूर्वाधार, हरियाली, फोहर व्यवस्थापन)",
  budget: 500,
  budgetCode: "4.A",
  sdg: { direct: "4.A", indirect: "NO" },
  iso37120: { direct: "6.EDU-(Education policy and planning)", indirect: "NO" },
  sci2025: { direct: "pillar no=3 componentno=3.9 I-061", indirect: "" },
  thematicArea: "school-infra",
  cycle: "",
  linkageScores: { sdgScore: 3, isoScore: 3, sciScore: 2, linkageType: "declaration" },
  projectPhase: generateProjectPhase(),
},
{
  id: "110",
  department: "शिक्षा विभाग",
  sector: "सामाजिक विकास",
  subSector: "शिक्षा",
  mainProgram: "विविध",
  programName: "अभिमुखिकरण कार्यक्रम सञ्चालन (विद्यार्थी, शिक्षक, प्रअ, विव्यस, अभिभावक)",
  budget: 4900,
  budgetCode: "4.A",
  sdg: { direct: "4.A", indirect: "NO" },
  iso37120: { direct: "6.EDU-(Education policy and planning)", indirect: "NO" },
  sci2025: { direct: "pillar no=2 componentno=2.5 I-026", indirect: "" },
  thematicArea: "teacher-training",
  cycle: "",
  linkageScores: { sdgScore: 3, isoScore: 3, sciScore: 2, linkageType: "declaration" },
  projectPhase: generateProjectPhase(),
},
{
  id: "111",
  department: "शिक्षा विभाग",
  sector: "सामाजिक विकास",
  subSector: "शिक्षा",
  mainProgram: "विविध",
  programName: "कक्षा सजावट तथा विद्यार्थीमार्फत विद्यालय सौन्दर्यिकरणका लागि सामग्री खरिद अनुदान",
  budget: 8500,
  budgetCode: "4.A",
  sdg: { direct: "4.A", indirect: "NO" },
  iso37120: { direct: "6.EDU(Education policy and planning)", indirect: "NO" },
  sci2025: { direct: "pillar no=1 componentno=1.2 I-006", indirect: "" },
  thematicArea: "school-infra",
  cycle: "",
  linkageScores: { sdgScore: 3, isoScore: 3, sciScore: 2, linkageType: "concurrence" },
  projectPhase: generateProjectPhase(),
},
{
  id: "112",
  department: "शिक्षा विभाग",
  sector: "सामाजिक विकास",
  subSector: "शिक्षा",
  mainProgram: "विविध",
  programName: "विद्यालय हाता सौन्दर्यकरणका लागि विद्यालयलाई अनुदान",
  budget: 200,
  budgetCode: "4.A",
  sdg: { direct: "4.A", indirect: "NO" },
  iso37120: { direct: "6.EDU(Education policy and planning)", indirect: "NO" },
  sci2025: { direct: "pillar no=1 componentno=1.2 I-006", indirect: "" },
  thematicArea: "school-infra",
  cycle: "",
  linkageScores: { sdgScore: 2, isoScore: 3, sciScore: 2, linkageType: "declaration" },
  projectPhase: generateProjectPhase(),
},
{
  id: "113",
  department: "शिक्षा विभाग",
  sector: "सामाजिक विकास",
  subSector: "शिक्षा",
  mainProgram: "विविध",
  programName: "कार्यक्रमको नियमित बैठक तथा समिक्षा",
  budget: 700,
  budgetCode: "4.C",
  sdg: { direct: "4.C", indirect: "NO" },
  iso37120: { direct: "6.EDU(Education policy and planning)", indirect: "NO" },
  sci2025: { direct: "pillar no=4 componentno=4.3 I-083", indirect: "" },
  thematicArea: "monitoring-regulation",
  cycle: "",
  linkageScores: { sdgScore: 2, isoScore: 3, sciScore: 3, linkageType: "discussion" },
  projectPhase: generateProjectPhase(),
},
{
  id: "114",
  department: "शिक्षा विभाग",
  sector: "सामाजिक विकास",
  subSector: "शिक्षा",
  mainProgram: "विविध",
  programName: "विविध खर्च",
  budget: 200,
  budgetCode: "4.C",
  sdg: { direct: "4.C", indirect: "NO" },
  iso37120: { direct: "6.EDU(Education policy and planning)", indirect: "NO" },
  sci2025: { direct: "pillar no=1 componentno=1.2 I-006", indirect: "" },
  thematicArea: "monitoring-regulation",
  cycle: "",
  linkageScores: { sdgScore: 1, isoScore: 2, sciScore: 2, linkageType: "declaration" },
  projectPhase: generateProjectPhase(),
},
{
  id: "115",
  department: "शिक्षा विभाग",
  sector: "सामाजिक विकास",
  subSector: "शिक्षा",
  mainProgram: "विविध",
  programName: "कार्यक्रमको नियमित अनुगमन तथा प्रतिवेदन",
  budget: 35000,
  budgetCode: "4.C",
  sdg: { direct: "4.C", indirect: "NO" },
  iso37120: { direct: "6.EDU(Education policy and planning)", indirect: "NO" },
  sci2025: { direct: "pillar no=1 componentno=1.2 I-006", indirect: "" },
  thematicArea: "monitoring-regulation",
  cycle: "",
  linkageScores: { sdgScore: 3, isoScore: 4, sciScore: 3, linkageType: "concurrence" },
  projectPhase: generateProjectPhase(),
},
{
  id: "116",
  department: "शिक्षा विभाग",
  sector: "सामाजिक विकास",
  subSector: "शिक्षा",
  mainProgram: "अनौपचारिक शिक्षा कार्यक्रम",
  programName: "कार्ययोजनाको आधारमा रचनात्मक विद्यालय कार्यक्रम सञ्चालनका लागि अनुदान",
  budget: 13000,
  budgetCode: "4.C",
  sdg: { direct: "4.C", indirect: "NO" },
  iso37120: { direct: "6.EDU(Education policy and planning)", indirect: "NO" },
  sci2025: { direct: "pillar no=1 componentno=1.2 I-006", indirect: "" },
  thematicArea: "teacher-training",
  cycle: "",
  linkageScores: { sdgScore: 3, isoScore: 3, sciScore: 2, linkageType: "discussion" },
  projectPhase: generateProjectPhase(),
},
{
  id: "117",
  department: "शिक्षा विभाग",
  sector: "सामाजिक विकास",
  subSector: "शिक्षा",
  mainProgram: "अनौपचारिक शिक्षा कार्यक्रम",
  programName: "महानगरपालिका स्तरीय विद्यार्थी खेलकुद प्रतियोगिता सञ्चालन",
  budget: 500,
  budgetCode: "4.5",
  sdg: { direct: "4.5", indirect: "NO" },
  iso37120: { direct: "6.EDU(Education policy and planning)", indirect: "NO" },
  sci2025: { direct: "pillar no=1 componentno=1.2 I-006", indirect: "" },
  thematicArea: "teacher-training",
  cycle: "",
  linkageScores: { sdgScore: 2, isoScore: 3, sciScore: 2, linkageType: "concurrence" },
  projectPhase: generateProjectPhase(),
},
{
  id: "118",
  department: "शिक्षा विभाग",
  sector: "सामाजिक विकास",
  subSector: "शिक्षा",
  mainProgram: "अनौपचारिक शिक्षा कार्यक्रम",
  programName: "बैठक, समिक्षा तथा जनशक्ति परिचालन",
  budget: 2500,
  budgetCode: "4.C",
  sdg: { direct: "4.C", indirect: "NO" },
  iso37120: { direct: "6.EDU(Education policy and planning)", indirect: "NO" },
  sci2025: { direct: "pillar no=1 componentno=1.2 I-006", indirect: "" },
  thematicArea: "monitoring-regulation",
  cycle: "",
  linkageScores: { sdgScore: 2, isoScore: 3, sciScore: 2, linkageType: "discussion" },
  projectPhase: generateProjectPhase(),
},
{
  id: "119",
  department: "शिक्षा विभाग",
  sector: "सामाजिक विकास",
  subSector: "शिक्षा",
  mainProgram: "अनौपचारिक शिक्षा कार्यक्रम",
  programName: "विद्यालय उद्यमशीलता क्लब स्थापना तथा सञ्चालन (Pilot – ५ विद्यालय)",
  budget: 1300,
  budgetCode: "4.4",
  sdg: { direct: "4.4", indirect: "NO" },
  iso37120: { direct: "6.EDU(Education policy and planning)", indirect: "NO" },
  sci2025: { direct: "pillar no=1 componentno=1.2 I-006", indirect: "" },
  thematicArea: "teacher-training",
  cycle: "",
  linkageScores: { sdgScore: 3, isoScore: 3, sciScore: 2, linkageType: "research" },
  projectPhase: generateProjectPhase(),
},
{
  id: "120",
  department: "शिक्षा विभाग",
  sector: "सामाजिक विकास",
  subSector: "शिक्षा",
  mainProgram: "अनौपचारिक शिक्षा कार्यक्रम",
  programName: "खेलकुद प्रशिक्षण तथा प्रतियोगिताका लागि राष्ट्रिय तथा अन्तर्राष्ट्रिय खेलकुद क्लबहरूसँग सहकार्य",
  budget: 200,
  budgetCode: "3.4",
  sdg: { direct: "3.4", indirect: "NO" },
  iso37120: { direct: "6.EDU(Education policy and planning)", indirect: "NO" },
  sci2025: { direct: "pillar no=1 componentno=1.2 I-006", indirect: "" },
  thematicArea: "teacher-training",
  cycle: "",
  linkageScores: { sdgScore: 2, isoScore: 3, sciScore: 2, linkageType: "concurrence" },
  projectPhase: generateProjectPhase(),
},

{
  id: "121",
  department: "शिक्षा विभाग",
  sector: "सामाजिक विकास",
  subSector: "शिक्षा",
  mainProgram: "अनौपचारिक शिक्षा कार्यक्रम",
  programName: "कार्यक्रम अनुगमन तथा प्रतिवेदन",
  budget: 8900,
  budgetCode: "4.C",
  sdg: { direct: "4.C", indirect: "NO" },
  iso37120: { direct: "6.EDU(Education policy and planning)", indirect: "NO" },
  sci2025: { direct: "pillar no=1 componentno=1.1 I-003", indirect: "" },
  thematicArea: "monitoring-regulation",
  cycle: "",
  linkageScores: { sdgScore: 3, isoScore: 4, sciScore: 3, linkageType: "discussion" },
  projectPhase: generateProjectPhase(),
},
{
  id: "122",
  department: "शिक्षा विभाग",
  sector: "सामाजिक विकास",
  subSector: "शिक्षा",
  mainProgram: "विविध",
  programName: "कक्षा ८ परीक्षा सञ्चालन तथा नतिजा व्यवस्थापन (प्रश्न निर्माण, परीक्षण, सफ्टवेयर, अनुगमन)",
  budget: 4789,
  budgetCode: "4.1",
  sdg: { direct: "4.1", indirect: "NO" },
  iso37120: { direct: "6.EDU(Education policy and planning)", indirect: "NO" },
  sci2025: { direct: "pillar no=2 componentno=2.5 I-026", indirect: "" },
  thematicArea: "teacher-training",
  cycle: "",
  linkageScores: { sdgScore: 4, isoScore: 4, sciScore: 3, linkageType: "research" },
  projectPhase: generateProjectPhase(),
},
{
  id: "123",
  department: "शिक्षा विभाग",
  sector: "सामाजिक विकास",
  subSector: "शिक्षा",
  mainProgram: "विविध",
  programName: "काठमाडौं एकेडेमिक फेस्ट सञ्चालन",
  budget: 3000,
  budgetCode: "",
  sdg: { direct: "", indirect: "NO" },
  iso37120: { direct: "6.EDU(Education policy and planning)", indirect: "NO" },
  sci2025: { direct: "pillar no=1 componentno=1.2 I-007", indirect: "" },
  thematicArea: "literacy-basic",
  cycle: "",
  linkageScores: { sdgScore: 2, isoScore: 3, sciScore: 2, linkageType: "discussion" },
  projectPhase: generateProjectPhase(),
},
{
  id: "124",
  department: "शिक्षा विभाग",
  sector: "सामाजिक विकास",
  subSector: "शिक्षा",
  mainProgram: "विविध",
  programName: "कक्षा ४–१० (कक्षा ८ बाहेक) त्रैमासिक तथा वार्षिक परीक्षाका प्रश्नपत्र विकास, छपाई र वितरण",
  budget: 3274,
  budgetCode: "4.1",
  sdg: { direct: "4.1", indirect: "NO" },
  iso37120: { direct: "6.EDU(Education policy and planning)", indirect: "NO" },
  sci2025: { direct: "pillar no=1 componentno=1.2 I-007", indirect: "" },
  thematicArea: "teacher-training",
  cycle: "",
  linkageScores: { sdgScore: 4, isoScore: 4, sciScore: 3, linkageType: "research" },
  projectPhase: generateProjectPhase(),
},
{
  id: "125",
  department: "शिक्षा विभाग",
  sector: "सामाजिक विकास",
  subSector: "शिक्षा",
  mainProgram: "विविध",
  programName: "कक्षा ११ छात्रवृत्ति परीक्षा सञ्चालन तथा नतिजा व्यवस्थापन",
  budget: 2000,
  budgetCode: "4.1",
  sdg: { direct: "4.1", indirect: "NO" },
  iso37120: { direct: "6.EDU(Education policy and planning)", indirect: "NO" },
  sci2025: { direct: "pillar no=3 componentno=3.9 I-062", indirect: "" },
  thematicArea: "teacher-training",
  cycle: "",
  linkageScores: { sdgScore: 4, isoScore: 4, sciScore: 3, linkageType: "concurrence" },
  projectPhase: generateProjectPhase(),
},
{
  id: "126",
  department: "शिक्षा विभाग",
  sector: "सामाजिक विकास",
  subSector: "शिक्षा",
  mainProgram: "विविध",
  programName: "काठमाडौं महानगरपालिका खोखो संघसँग सहकार्यमा विद्यालयस्तरीय खोखो प्रतियोगिता",
  budget: 3000,
  budgetCode: "3.4",
  sdg: { direct: "3.4", indirect: "NO" },
  iso37120: { direct: "6.EDU(Education policy and planning)", indirect: "NO" },
  sci2025: { direct: "pillar no=2 componentno=2.5 I-026", indirect: "" },
  thematicArea: "literacy-basic",
  cycle: "",
  linkageScores: { sdgScore: 3, isoScore: 3, sciScore: 2, linkageType: "concurrence" },
  projectPhase: generateProjectPhase(),
},
{
  id: "127",
  department: "शिक्षा विभाग",
  sector: "सामाजिक विकास",
  subSector: "शिक्षा",
  mainProgram: "विविध",
  programName: "कक्षा ९ र १० का छात्राका लागि PCOS सम्बन्धी सचेतना कार्यक्रम",
  budget: 3000,
  budgetCode: "3.7,4.6",
  sdg: { direct: "3.7,4.6", indirect: "NO" },
  iso37120: { direct: "6.EDU(Education policy and planning)", indirect: "NO" },
  sci2025: { direct: "pillar no=2 componentno=2.5 I-026", indirect: "" },
  thematicArea: "teacher-training",
  cycle: "",
  linkageScores: { sdgScore: 4, isoScore: 3, sciScore: 3, linkageType: "research" },
  projectPhase: generateProjectPhase(),
},
{
  id: "128",
  department: "शिक्षा विभाग",
  sector: "सामाजिक विकास",
  subSector: "शिक्षा",
  mainProgram: "विविध",
  programName: "राष्ट्रिय तथा अन्तर्राष्ट्रिय शैक्षिक सम्मेलन",
  budget: 2000,
  budgetCode: "",
  sdg: { direct: "", indirect: "NO" },
  iso37120: { direct: "6.EDU(Education policy and planning)", indirect: "NO" },
  sci2025: { direct: "pillar no=2 componentno=2.5 I-026", indirect: "" },
  thematicArea: "digital-education",
  cycle: "",
  linkageScores: { sdgScore: 2, isoScore: 3, sciScore: 2, linkageType: "discussion" },
  projectPhase: generateProjectPhase(),
},
{
  id: "129",
  department: "शिक्षा विभाग",
  sector: "सामाजिक विकास",
  subSector: "शिक्षा",
  mainProgram: "विविध",
  programName: "मौलिक सभ्यताका विषय समेटिएको संक्षिप्त पाठ्यक्रम तयारी तथा कक्षा सञ्चालन",
  budget: 1000,
  budgetCode: "4.7",
  sdg: { direct: "4.7", indirect: "NO" },
  iso37120: { direct: "6.EDU(Education policy and planning)", indirect: "NO" },
  sci2025: { direct: "pillar no=2 componentno=2.5 I-026", indirect: "" },
  thematicArea: "literacy-basic",
  cycle: "",
  linkageScores: { sdgScore: 3, isoScore: 3, sciScore: 2, linkageType: "research" },
  projectPhase: generateProjectPhase(),
},
{
  id: "130",
  department: "शिक्षा विभाग",
  sector: "सामाजिक विकास",
  subSector: "शिक्षा",
  mainProgram: "विविध",
  programName: "विद्यालय स्तरमा नेपाल भाषा तालिम प्रशिक्षण",
  budget: 500,
  budgetCode: "11.4",
  sdg: { direct: "11.4", indirect: "NO" },
  iso37120: { direct: "6.EDU(Education policy and planning)", indirect: "NO" },
  sci2025: { direct: "pillar no=2 componentno=2.5 I-026", indirect: "" },
  thematicArea: "teacher-training",
  cycle: "",
  linkageScores: { sdgScore: 3, isoScore: 3, sciScore: 2, linkageType: "concurrence" },
  projectPhase: generateProjectPhase(),
},
{
  id: "131",
  department: "शिक्षा विभाग",
  sector: "सामाजिक विकास",
  subSector: "शिक्षा",
  mainProgram: "विविध",
  programName: "डिजिटल शिक्षण सिकाइ सूचना प्रविधिमैत्री विद्यालय निर्माण (क्रमागत)",
  budget: 56500,
  budgetCode: "4.C",
  sdg: { direct: "4.C", indirect: "NO" },
  iso37120: { direct: "6.EDU(Education policy and planning)", indirect: "NO" },
  sci2025: { direct: "pillar no=2 componentno=2.5 I-026", indirect: "" },
  thematicArea: "digital-education",
  cycle: "",
  linkageScores: { sdgScore: 4, isoScore: 4, sciScore: 3, linkageType: "concurrence" },
  projectPhase: generateProjectPhase(),
},
{
  id: "132",
  department: "शिक्षा विभाग",
  sector: "सामाजिक विकास",
  subSector: "शिक्षा",
  mainProgram: "विविध",
  programName: "शैक्षिक सुधारका लागि आकस्मिक तथा भैपरी आउने खर्च",
  budget: 20000,
  budgetCode: "4.A",
  sdg: { direct: "4.A", indirect: "NO" },
  iso37120: { direct: "6.EDU(Education policy and planning)", indirect: "NO" },
  sci2025: { direct: "pillar no=2 componentno=2.5 I-026", indirect: "" },
  thematicArea: "school-infra",
  cycle: "",
  linkageScores: { sdgScore: 3, isoScore: 3, sciScore: 2, linkageType: "declaration" },
  projectPhase: generateProjectPhase(),
},
{
  id: "133",
  department: "शिक्षा विभाग",
  sector: "सामाजिक विकास",
  subSector: "शिक्षा",
  mainProgram: "विविध",
  programName: "Education Transformation Summit भुक्तानी बाँकी",
  budget: 500,
  budgetCode: "",
  sdg: { direct: "", indirect: "NO" },
  iso37120: { direct: "6.EDU(Education policy and planning)", indirect: "NO" },
  sci2025: { direct: "pillar no=2 componentno=2.5 I-026", indirect: "" },
  thematicArea: "monitoring-regulation",
  cycle: "",
  linkageScores: { sdgScore: 1, isoScore: 2, sciScore: 2, linkageType: "discussion" },
  projectPhase: generateProjectPhase(),
},
{
  id: "134",
  department: "शिक्षा विभाग",
  sector: "सामाजिक विकास",
  subSector: "शिक्षा",
  mainProgram: "विविध",
  programName: "काठमाडौं विश्वविद्यालय स्कूल अफ एजुकेसनलाई ६ क्रियाकलापको भुक्तानी बाँकी",
  budget: 5500,
  budgetCode: "",
  sdg: { direct: "", indirect: "NO" },
  iso37120: { direct: "6.EDU(Education policy and planning)", indirect: "NO" },
  sci2025: { direct: "pillar no=2 componentno=2.5 I-026", indirect: "" },
  thematicArea: "monitoring-regulation",
  cycle: "",
  linkageScores: { sdgScore: 2, isoScore: 3, sciScore: 2, linkageType: "concurrence" },
  projectPhase: generateProjectPhase(),
},
{
  id: "135",
  department: "शिक्षा विभाग",
  sector: "सामाजिक विकास",
  subSector: "शिक्षा",
  mainProgram: "विविध",
  programName: "स्नातक तहमा नेपाल भाषा अध्यापनका लागि रत्नराज्य क्याम्पसलाई अनुदान",
  budget: 1500,
  budgetCode: "4.6",
  sdg: { direct: "4.6", indirect: "NO" },
  iso37120: { direct: "6.EDU(Education policy and planning)", indirect: "NO" },
  sci2025: { direct: "pillar no=2 componentno=2.5 I-026", indirect: "" },
  thematicArea: "teacher-training",
  cycle: "",
  linkageScores: { sdgScore: 3, isoScore: 3, sciScore: 2, linkageType: "research" },
  projectPhase: generateProjectPhase(),
},


]
// Example education indicators
export const keyIndicators = [
  {
    id: "sdg-4-1",
    standard: "SDG",
    code: "4.1",
    name: "Literacy Rate",
    nameNp: "साक्षरता दर",
    description: "Percentage of children completing primary education",
    relatedPrograms: 15,
  },
  {
    id: "sdg-4-c",
    standard: "SDG",
    code: "4.c",
    name: "Teacher Development",
    nameNp: "शिक्षक विकास",
    description: "Increase number of trained teachers in primary and secondary schools",
    relatedPrograms: 10,
  },
  {
    id: "iso-13-1",
    standard: "ISO 37120",
    code: "13.1",
    name: "School Enrollment",
    nameNp: "विद्यालय नामांकन",
    description: "Percentage of children enrolled in school",
    relatedPrograms: 12,
  },
  {
    id: "sci-4-5",
    standard: "SCI 2025",
    code: "Pillar 4.5",
    name: "Digital Education Systems",
    nameNp: "डिजिटल शिक्षा प्रणाली",
    description: "Smart classrooms and e-learning adoption",
    relatedPrograms: 8,
  },
]
