// KMC Health Program Data with mappings to SDG, ISO 37120, and SCI 2025

export interface KMCProgram {
  id: string
  department: string
  sector: string
  subSector: string
  mainProgram: string
  programName: string
  budget: number
  budgetCode: string
  sdg: {
    direct: string
    indirect: string
  }
  iso37120: {
    direct: string
    indirect: string
  }
  sci2025: {
    direct: string
    indirect: string
  }
  thematicArea: string
  cycle: string
  // Linkage scores (0-5 Likert scale)
  linkageScores: {
    sdgScore: number
    isoScore: number
    sciScore: number
    linkageType: "research" | "discussion" | "concurrence" | "declaration"
  }
  // Evaluation regime (0-100%)
  projectPhase: {
    phase: "inception" | "approval" | "tender" | "award" | "completion"
    progress: number
  }
}

export const thematicAreas = [
  {
    id: "health-treatment",
    name: "Health Treatment Services ",
    nameNp: "स्वास्थ्य उपचार सेवाहरू",
    description: "Direct health care delivery including curative and preventive services",
    color: "#0891B2",
    icon: "Heart",
    standards: {
      sdg: ["SDG 3.8", "SDG 3.4", "SDG 3.c"],
      iso: ["ISO 37120:12.1", "ISO 37120:12.2", "ISO 37120:12.3"],
      sci: ["Pillar 1 - Health & Wellbeing"],
    },
  },
  {
    id: "capacity-development",
    name: "Capacity Development",
    nameNp: "क्षमता विकास",
    description: "Training, skill development and institutional strengthening",
    color: "#059669",
    icon: "GraduationCap",
    standards: {
      sdg: ["SDG 3.c.1", "SDG 4.7"],
      iso: ["ISO 37120:12.5", "ISO 37120:12.6"],
      sci: ["Pillar 4 - Human Capital Development"],
    },
  },
  {
    id: "digital-health",
    name: "Digital Health Connect",
    nameNp: "डिजिटल स्वास्थ्य",
    description: "E-health, HMIS, telemedicine and digital health records",
    color: "#7C3AED",
    icon: "Laptop",
    standards: {
      sdg: ["SDG 3.d", "SDG 9.c"],
      iso: ["ISO 37120:7.5"],
      sci: ["Pillar 4 - Digital Infrastructure"],
    },
  },
  {
    id: "physical-infrastructure",
    name: "Physical Infrastructure",
    nameNp: "भौतिक पूर्वाधार",
    description: "Health facility construction, equipment and physical assets",
    color: "#DC2626",
    icon: "Building2",
    standards: {
      sdg: ["SDG 3.c", "SDG 9.1"],
      iso: ["ISO 37120:12.2"],
      sci: ["Pillar 3 - Infrastructure"],
    },
  },
  {
    id: "monitoring-evaluation",
    name: "Monitoring & Regulation",
    nameNp: "अनुगमन तथा नियमन",
    description: "Food safety, quality control and health monitoring",
    color: "#EA580C",
    icon: "ClipboardCheck",
    standards: {
      sdg: ["SDG 3.9", "SDG 2.1"],
      iso: ["ISO 37120:11"],
      sci: ["Pillar 2 - Smart Governance"],
    },
  },
  {
    id: "community-health",
    name: "Community Health",
    nameNp: "सामुदायिक स्वास्थ्य",
    description: "FCHV programs, community outreach and volunteer mobilization",
    color: "#0D9488",
    icon: "Users",
    standards: {
      sdg: ["SDG 3.c.1", "SDG 5.6"],
      iso: ["ISO 37120:12.4"],
      sci: ["Pillar 1 - Community Engagement"],
    },
  },
  {
    id: "emergency-services",
    name: "Emergency Services",
    nameNp: "आकस्मिक सेवाहरू",
    description: "Ambulance services, emergency response and disaster health",
    color: "#B91C1C",
    icon: "Siren",
    standards: {
      sdg: ["SDG 3.d.1", "SDG 11.5"],
      iso: ["ISO 37120:12.8"],
      sci: ["Pillar 1 - Emergency Response"],
    },
  },
  {
    id: "environmental-health",
    name: "Environmental Health",
    nameNp: "वातावरणीय स्वास्थ्य",
    description: "Air quality, waste management and healthy lifestyle programs",
    color: "#16A34A",
    icon: "Leaf",
    standards: {
      sdg: ["SDG 3.9", "SDG 11.6", "SDG 13.3"],
      iso: ["ISO 37120:8", "ISO 37120:16"],
      sci: ["Pillar 3 - Environment & Climate"],
    },
  },
]

export const linkageTypes = [
  {
    value: "declaration",
    label: "Declaration",
    score: 1,
    description: "Official policy declaration without verification",
  },
  { value: "discussion", label: "Discussion", score: 2, description: "Discussed in meetings/workshops" },
  { value: "concurrence", label: "Concurrence", score: 3, description: "Agreed upon by multiple stakeholders" },
  { value: "research", label: "Research", score: 4, description: "Backed by research and evidence" },
]

export const projectPhases = [
  { value: "inception", label: "Inception", rangeStart: 0, rangeEnd: 20 },
  { value: "approval", label: "Approval", rangeStart: 21, rangeEnd: 40 },
  { value: "tender", label: "Tender", rangeStart: 41, rangeEnd: 60 },
  { value: "award", label: "Award", rangeStart: 61, rangeEnd: 80 },
  { value: "completion", label: "Completion", rangeStart: 81, rangeEnd: 100 },
]

// Helper function to determine linkage score based on mapping data
function calculateLinkageScore(direct: string, indirect: string): number {
  if (direct && direct !== "NO" && direct !== "No" && direct !== "") {
    return 4 // Direct linkage = high score
  }
  if (indirect && indirect !== "NO" && indirect !== "No" && indirect !== "") {
    return 2 // Indirect linkage = medium score
  }
  return 0 // No linkage
}

// Map thematic area from CSV
function mapThematicArea(thematic: string): string {
  const mapping: Record<string, string> = {
    "Health Treatement Services": "health-treatment",
    "Health Treatment Services": "health-treatment",
    "Capacity Development": "capacity-development",
    "Digital Health Connect": "digital-health",
    "Digital  Health Services": "digital-health",
    "Phycial Infrastructure": "physical-infrastructure",
    "Physical Infrastructure": "physical-infrastructure",
    "Physical Infrastruture": "physical-infrastructure",
    Monitoring: "monitoring-evaluation",
    "Health Treatement Service": "health-treatment",
  }
  return mapping[thematic] || "health-treatment"
}

// Generate random project phase for demo (in real system, this would come from database)
function generateProjectPhase(): {
  phase: "inception" | "approval" | "tender" | "award" | "completion"
  progress: number
} {
  const phases: ("inception" | "approval" | "tender" | "award" | "completion")[] = [
    "inception",
    "approval",
    "tender",
    "award",
    "completion",
  ]
  const weights = [0.15, 0.2, 0.25, 0.25, 0.15]

  let random = Math.random()
  let phaseIndex = 0
  for (let i = 0; i < weights.length; i++) {
    random -= weights[i]
    if (random <= 0) {
      phaseIndex = i
      break
    }
  }

  const phase = phases[phaseIndex]
  const phaseRanges: Record<string, [number, number]> = {
    inception: [5, 20],
    approval: [25, 40],
    tender: [45, 60],
    award: [65, 80],
    completion: [85, 100],
  }

  const [min, max] = phaseRanges[phase]
  const progress = Math.floor(Math.random() * (max - min + 1)) + min

  return { phase, progress }
}

// KMC Program Data parsed from CSV
export const kmcPrograms: KMCProgram[] = [
  {
    id: "1",
    department: "स्वास्थ्य विभाग",
    sector: "सामाजिक विकास",
    subSector: "स्वास्थ्य",
    mainProgram: "सामुदायिक स्वास्थ्य सेवा",
    programName: "स्वास्थ्य प्रवर्द्धन केन्द्रको मासिक, अर्धवार्षिक र वार्षिक समिक्षा",
    budget: 500,
    budgetCode: "22522",
    sdg: { direct: "3.8(3.8.2)", indirect: "" },
    iso37120: { direct: "No", indirect: "No" },
    sci2025: { direct: "NO", indirect: "" },
    thematicArea: "health-treatment",
    cycle: "",
    linkageScores: { sdgScore: 4, isoScore: 0, sciScore: 0, linkageType: "declaration" },
    projectPhase: generateProjectPhase(),
  },
  {
    id: "2",
    department: "स्वास्थ्य विभाग",
    sector: "सामाजिक विकास",
    subSector: "स्वास्थ्य",
    mainProgram: "खोप कार्यक्रम",
    programName: "राष्ट्रियस्तरको भिटामिन ए कार्यक्रम सञ्चालन तथा महिला स्वास्थ्य स्वयं सेविका थप प्रोत्साहन सहित परिचालन",
    budget: 4000,
    budgetCode: "21135",
    sdg: { direct: "3.8(3.8.1)", indirect: "" },
    iso37120: { direct: "", indirect: "No" },
    sci2025: { direct: "NO", indirect: "" },
    thematicArea: "health-treatment",
    cycle: "",
    linkageScores: { sdgScore: 5, isoScore: 0, sciScore: 0, linkageType: "research" },
    projectPhase: generateProjectPhase(),
  },
  {
    id: "3",
    department: "स्वास्थ्य विभाग",
    sector: "सामाजिक विकास",
    subSector: "स्वास्थ्य",
    mainProgram: "सामुदायिक स्वास्थ्य सेवा",
    programName: "सामुदायिक महिला स्वास्थ्य स्वयंसेविका समिति सञ्चालन खर्च",
    budget: 300,
    budgetCode: "21139",
    sdg: { direct: "3.c(3.c.1)", indirect: "" },
    iso37120: { direct: "", indirect: "No" },
    sci2025: { direct: "NO", indirect: "" },
    thematicArea: "community-health",
    cycle: "",
    linkageScores: { sdgScore: 4, isoScore: 0, sciScore: 0, linkageType: "concurrence" },
    projectPhase: generateProjectPhase(),
  },
  {
    id: "4",
    department: "स्वास्थ्य विभाग",
    sector: "सामाजिक विकास",
    subSector: "स्वास्थ्य",
    mainProgram: "सामुदायिक स्वास्थ्य सेवा",
    programName: " शहरी स्वास्थ्य प्रवर्द्धन केन्द्रमा आउने सम्पूर्ण सेवाग्राहीहरुको डिजिटल हेल्थ प्रोफाइल तयार गर्ने",
    budget: 3200,
    budgetCode: "21139",
    sdg: { direct: "3.8(3.8.1)", indirect: "" },
    iso37120: { direct: "No", indirect: "" },
    sci2025: { direct: "No", indirect: "" },
    thematicArea: "digital-health",
    cycle: "",
    linkageScores: { sdgScore: 4, isoScore: 5, sciScore: 5, linkageType: "research" },
    projectPhase: generateProjectPhase(),
  },
  {
    id: "5", //id
    department: "स्वास्थ्य विभाग",
    sector: "सामाजिक विकास",
    subSector: "स्वास्थ्य",
    mainProgram: "महिला स्वास्थ्य स्वयंसेविका",
    programName: "महिला स्वास्थ्य स्वयंसेविका चाडपर्व सुविधा",
    budget: 8200,
    budgetCode: "21139",
    sdg: { direct: "No", indirect: "" },
    iso37120: { direct: "No", indirect: "" },
    sci2025: {
      direct: "No",
      indirect: "",
    },
    thematicArea: "capacity-development",
    cycle: "",
    linkageScores: { sdgScore: 5, isoScore: 5, sciScore: 5, linkageType: "research" },
    projectPhase: generateProjectPhase(),
  },
  {
    id: "6",
    department: "स्वास्थ्य विभाग",
    sector: "सामाजिक विकास",
    subSector: "स्वास्थ्य",
    mainProgram: "वित्तीय व्यवस्थापन",
    programName: "स्वास्थ्य विभाग अन्तर्गत कार्यरत कर्मचारीको लागी जोखिम भत्ता",
    budget: 25000,
    budgetCode: "21139",
    sdg: { direct: "3(3.c.1)", indirect: "" },
    iso37120: { direct: "No", indirect: "" },
    sci2025: { direct: "No", indirect: "" },
    thematicArea: "capacity-development",
    cycle: "",
    linkageScores: { sdgScore: 4, isoScore: 5, sciScore: 5, linkageType: "research" },
    projectPhase: generateProjectPhase(),
  },
  {
    id: "7",
    department: "स्वास्थ्य विभाग",
    sector: "सामाजिक विकास",
    subSector: "स्वास्थ्य",
    mainProgram: "महिला स्वास्थ्य स्वयंसेविका",
    programName: "महिला स्वास्थ्य स्वयंसेविका दिवस तथा अवकाश प्रोत्साहन कार्यक्रम",
    budget: 4000,
    budgetCode: "21219",
    sdg: { direct: "3(3.c.1)", indirect: "" },
    iso37120: { direct: "No", indirect: "" },
    sci2025: { direct: "No", indirect: "" },
    thematicArea: "health-treatment",
    cycle: "",
    linkageScores: { sdgScore: 5, isoScore: 4, sciScore: 5, linkageType: "research" },
    projectPhase: generateProjectPhase(),
  },
  {
    id: "8",
    department: "स्वास्थ्य विभाग",
    sector: "सामाजिक विकास",
    subSector: "स्वास्थ्य",
    mainProgram: "महिला स्वास्थ्य स्वयंसेविका",
    programName: "महिला स्वास्थ्य स्वयंसेविकाको लागि संचार खर्च प्रति महिला स्वयं सेविका २५०० को दरले",
    budget: 1200,
    budgetCode: "22112",
    sdg: { direct: "3(3.c.1)", indirect: "" },
    iso37120: { direct: "No", indirect: "" },
    sci2025: { direct: "No", indirect: "" },
    thematicArea: "health-treatment",
    cycle: "",
    linkageScores: { sdgScore: 5, isoScore: 0, sciScore: 4, linkageType: "research" },
    projectPhase: generateProjectPhase(),
  },
  {
    id: "9",
    department: "स्वास्थ्य विभाग",
    sector: "सामाजिक विकास",
    subSector: "स्वास्थ्य",
    mainProgram: "सामुदायिक स्वास्थ्य सेवा",
    programName: "स्वास्थ्यजन्य औजार उपकरण मर्मत",
    budget: 500,
    budgetCode: "22221",
    sdg: { direct: "3(3.d.1)", indirect: "" },
    iso37120: { direct: "No", indirect: "" },
    sci2025: { direct: "No", indirect: "" },
    thematicArea: "health-treatment",
    cycle: "",
    linkageScores: { sdgScore: 5, isoScore: 0, sciScore: 4, linkageType: "research" },
    projectPhase: generateProjectPhase(),
  },
  {
    id: "10",
    department: "स्वास्थ्य विभाग",
    sector: "सामाजिक विकास",
    subSector: "स्वास्थ्य",
    mainProgram: "सामुदायिक स्वास्थ्य सेवा",
    programName: "स्वास्थ्य बीमा सम्बन्धी बीमा सामाग्रीहरु छपाई",
    budget: 500,
    budgetCode: "22315",
    sdg: { direct: "3.c(3.c.1)", indirect: "" },
    iso37120: { direct: "No", indirect: "" },
    sci2025: { direct: "No", indirect: "" },
    thematicArea: "health-treatment",
    cycle: "",
    linkageScores: { sdgScore: 5, isoScore: 0, sciScore: 4, linkageType: "research" },
    projectPhase: generateProjectPhase(),
  },
  {
    id: "11",
    department: "स्वास्थ्य विभाग",
    sector: "सामाजिक विकास",
    subSector: "स्वास्थ्य",
    mainProgram: "शहरी स्वास्थ्य सेवा",
    programName: "स्वास्थ्यसँग सम्बन्धित सामाग्री छपाई",
    budget: 2000,
    budgetCode: "22315",
    sdg: { direct: "3.c(3.c.1)", indirect: "" },
    iso37120: { direct: "No", indirect: "" },
    sci2025: { direct: "Pillar No. 2 / Component No.2.6 / Indicator: I-021, Good health and well-being", indirect: "" },
    thematicArea: "emergency-services",
    cycle: "",
    linkageScores: { sdgScore: 5, isoScore: 0, sciScore: 4, linkageType: "concurrence" },
    projectPhase: generateProjectPhase(),
  },
  {
    id: "12",
    department: "स्वास्थ्य विभाग",
    sector: "सामाजिक विकास",
    subSector: "स्वास्थ्य",
    mainProgram: "शहरी स्वास्थ्य सेवा",
    programName: "सहरी स्वास्थ्य प्रवर्द्धन केन्द्रहरुको सेवा प्रवर्द्धनका लागि लघु बृतचित्र निर्माण ",
    budget: 3000,
    budgetCode: "22411",
    sdg: { direct: "3.c(3.c.1)", indirect: "" },
    iso37120: { direct: "No", indirect: "" },
    sci2025: { direct: "Pillar No. 1/ Component No.1.2 / Indicator: I-011, Maternal and Child health", indirect: "" },
    thematicArea: "health-treatment",
    cycle: "",
    linkageScores: { sdgScore: 5, isoScore: 3, sciScore: 4, linkageType: "research" },
    projectPhase: generateProjectPhase(),
  },
  {
    id: "13",
    department: "स्वास्थ्य विभाग",
    sector: "सामाजिक विकास",
    subSector: "स्वास्थ्य",
    mainProgram: "सामुदायिक स्वास्थ्य सेवा",
    programName: "महानगर स्वास्थ्य प्रवर्द्धनको लागि स्वास्थ्य सम्बन्धी अनुसन्धान",
    budget: 500,
    budgetCode: "22411",
    sdg: { direct: "3.b(3.b.2)", indirect: "" },
    iso37120: { direct: "No", indirect: "" },
    sci2025: { direct: "Pillar No. 1/ Component No.1.2 / Indicator: I-012, Non-communicable disease", indirect: "" },
    thematicArea: "physical-infrastructure",
    cycle: "",
    linkageScores: { sdgScore: 4, isoScore: 0, sciScore: 3, linkageType: "declaration" },
    projectPhase: generateProjectPhase(),
  },
  {
    id: "14",
    department: "स्वास्थ्य विभाग",
    sector: "सामाजिक विकास",
    subSector: "स्वास्थ्य",
    mainProgram: "सामुदायिक स्वास्थ्य सेवा",
    programName: "डिजिटल कार्ड मार्फत स्वास्थ्य प्रवर्द्धन केन्द्रमा आउने सम्पूर्ण सेवाग्राहीहरुको डिजिटल हेल्थ प्रोफाइल तयार गर्ने",
    budget: 1000,
    budgetCode: "22411",
    sdg: { direct: "3.c(3.c.1)", indirect: "" },
    iso37120: { direct: "No", indirect: "12.3,12.5,12.6" },
    sci2025: { direct: "Pillar No. 4/ Component No.4.5 / Indicator: I-071, EMR adption", indirect: "" },
    thematicArea: "digital-health",
    cycle: "",
    linkageScores: { sdgScore: 4, isoScore: 0, sciScore: 3, linkageType: "declaration" },
    projectPhase: generateProjectPhase(),
  },
  {
    id: "15",
    department: "स्वास्थ्य विभाग (क्रमागत)",
    sector: "सामाजिक विकास",
    subSector: "स्वास्थ्य",
    mainProgram: "सामुदायिक स्वास्थ्य सेवा",
    programName:
      "महानगर भित्र संचालित सरकारी,गैरसरकारी,सामुदायिक तथा निजी स्वास्थ्य संस्थाहरुको प्रोफाइल तयारी तथा स्रोत  नक्शांकन",
    budget: 2000,
    budgetCode: "22411",
    sdg: { direct: "3.d(3.d.1)", indirect: "" },
    iso37120: { direct: "No", indirect: "No" },
    sci2025: { direct: "Pillar No. 2/ Component No.2.6 / Indicator: I-022, Digtal health record", indirect: "" },
    thematicArea: "digital-health",
    cycle: "",
    linkageScores: { sdgScore: 4, isoScore: 4, sciScore: 0, linkageType: "concurrence" },
    projectPhase: generateProjectPhase(),
  },
  {
    id: "16",
    department: "स्वास्थ्य विभाग (क्रमागत)",
    sector: "सामाजिक विकास",
    subSector: "स्वास्थ्य",
    mainProgram: "शहरी स्वास्थ्य सेवा",
    programName: "सफ्टवयर बार्षिक मर्मत तथा नविकरण शुल्क ",
    budget: 1000,
    budgetCode: "22412",
    sdg: { direct: "3.d(3.d.1)", indirect: "" },
    iso37120: { direct: "12.2", indirect: "" },
    sci2025: { direct: "Pillar No. 4/ Component No.4.45 / Indicator: I-073, HMIS usage", indirect: "" },
    thematicArea: "physical-infrastructure",
    cycle: "",
    linkageScores: { sdgScore: 4, isoScore: 4, sciScore: 0, linkageType: "concurrence" },
    projectPhase: generateProjectPhase(),
  },
  {
    id: "17",
    department: "स्वास्थ्य विभाग",
    sector: "सामाजिक विकास",
    subSector: "स्वास्थ्य",
    mainProgram: "सामुदायिक स्वास्थ्य सेवा",
    programName: " शहरी स्वास्थ्य प्रवर्द्धन केन्द्रहरुमा अतिरिक्त समयमा तोकिएको स्वास्थ्य सेवा संचालन बापत सेवा खर्च",
    budget: 15000,
    budgetCode: "22413",
    sdg: { direct: "3.8(3.8.1)", indirect: "" },
    iso37120: { direct: "No", indirect: "No" },
    sci2025: { direct: "Pillar No. 1/ Component No.1.2 / Indicator: I-011, Maternal and Child health", indirect: "" },
    thematicArea: "monitoring-evaluation",
    cycle: "",
    linkageScores: { sdgScore: 4, isoScore: 0, sciScore: 3, linkageType: "discussion" },
    projectPhase: generateProjectPhase(),
  },
  {
    id: "18",
    department: "स्वास्थ्य विभाग",
    sector: "सामाजिक विकास",
    subSector: "स्वास्थ्य",
    mainProgram: "क्षमता अभिबृध्दि",
    programName: "सहरी स्वास्थ्य प्रवर्द्धन केन्द्रहरुमा कार्यरत सरसफाईकर्मीहरुलाई स्वास्थ्यजन्य फोहोरमैला व्यवस्थापन सम्बन्धी अभिमुखीकरण",
    budget: 400,
    budgetCode: "22511",
    sdg: { direct: "3.8(3.8.1)", indirect: "" },
    iso37120: { direct: "", indirect: "No" },
    sci2025: { direct: "Pillar No. 1/ Component No.1.2 / Indicator: I-011, Maternal and Child health", indirect: "" },
    thematicArea: "monitoring-evaluation",
    cycle: "",
    linkageScores: { sdgScore: 0, isoScore: 0, sciScore: 3, linkageType: "discussion" },
    projectPhase: generateProjectPhase(),
  },
  {
    id: "19",
    department: "स्वास्थ्य विभाग",
    sector: "सामाजिक विकास",
    subSector: "स्वास्थ्य",
    mainProgram: "सामुदायिक स्वास्थ्य सेवा",
    programName: 'स्वास्थ्यकर्मीहरुलाई PEN (Package of Essential Non-communicable Diseases) सम्बन्धी तालिम',
    budget: 500,
    budgetCode: "22511",
    sdg: { direct: "3.4(3.4.1)", indirect: "" },
    iso37120: { direct: "", indirect: "12.3,12.5,12.6" },
    sci2025: { direct: "Pillar No. 1/ Component No.1.2 / Indicator: I-012, Non-communicable disease and traning", indirect: "" },
    thematicArea: "monitoring-evaluation",
    cycle: "",
    linkageScores: { sdgScore: 0, isoScore: 0, sciScore: 3, linkageType: "discussion" },
    projectPhase: generateProjectPhase(),
  },
  {
    id: "20",
    department: "स्वास्थ्य विभाग",
    sector: "सामाजिक विकास",
    subSector: "स्वास्थ्य",
    mainProgram: "स्वास्थ्य तालिम",
    programName: "स्वास्थ्य बीमा सम्बन्धी विभिन्न तालिम तथा अभिमूखिकरण बीमा दर्ता सहयोगी समेत",
    budget: 400,
    budgetCode: "22511",
    sdg: { direct: "3.8(3.8.2)", indirect: "No" },
    iso37120: { direct: "No", indirect: "12.3,12.5,12.6" },
    sci2025: { direct: "Pillar No.2 / Component No.2.6/ Indicator: I-021, Insurance coverage", indirect: "No" },
    thematicArea: "environmental-health",
    cycle: "",
    linkageScores: { sdgScore: 2, isoScore: 0, sciScore: 4, linkageType: "research" },
    projectPhase: generateProjectPhase(),
  },
  {
    id: "21",
    department: "स्वास्थ्य विभाग",
    sector: "सामाजिक विकास",
    subSector: "स्वास्थ्य",
    mainProgram: "सामुदायिक स्वास्थ्य सेवा",
    programName: "स्वास्थ्यका सफ्टवयर सम्बन्धी कर्मचारीहरुलाई तालीम",
    budget: 400,
    budgetCode: "22511",
    sdg: { direct: "3(3.c.1)", indirect: "No" },
    iso37120: { direct: "No", indirect: "12.2" },
    sci2025: { direct: "Pillar No. 4/ Component No.4.5 / Indicator: I-073, HMIS usage", indirect: "No" },
    thematicArea: "environmental-health",
    cycle: "",
    linkageScores: { sdgScore: 2, isoScore: 0, sciScore: 4, linkageType: "concurrence" },
    projectPhase: generateProjectPhase(),
  },
  {
    id: "22",
    department: "स्वास्थ्य विभाग",
    sector: "सामाजिक विकास",
    subSector: "स्वास्थ्य",
    mainProgram: "सामुदायिक स्वास्थ्य सेवा",
    programName: "स्वास्थ्यकर्मीहरुलाई HMIS सम्बन्धी स्थलगत अनुशिक्षण तथा क्षमता विकास कार्यक्रम",
    budget: 400,
    budgetCode: "22511",
    sdg: { direct: "3.c(3.c.1)", indirect: "No" },
    iso37120: { direct: "No", indirect: "12.3,12.5,12.6" },
    sci2025: { direct: "Pillar No. 4/ Component No.4.5 / Indicator: I-073, HMIS usage ", indirect: "No" },
    thematicArea: "community-health",
    cycle: "",
    linkageScores: { sdgScore: 4, isoScore: 5, sciScore: 5, linkageType: "research" },
    projectPhase: generateProjectPhase(),
  },
  {
    id: "23",
    department: "स्वास्थ्य विभाग",
    sector: "सामाजिक विकास",
    subSector: "स्वास्थ्य",
    mainProgram: "क्षमता अभिबृध्दि",
    programName: "मेडिकल अधिकृतहरुका लागि Advanced Cardiac Life Support(ACLS) तालिम संचालन",
    budget: 1500,
    budgetCode: "22511",
    sdg: { direct: "3(3.c.1)", indirect: "No" },
    iso37120: { direct: "No", indirect: "12.3,12.5,12.6" },
    sci2025: { direct: "Pillar No. 1/ Component No.1.2 / Indicator: I-012, NCD prevention",indirect: "No" },
    thematicArea: "health-treatment",
    cycle: "",
    linkageScores: { sdgScore: 5, isoScore: 0, sciScore: 4, linkageType: "concurrence" },
    projectPhase: generateProjectPhase(),
  },
  {
    id: "24",
    department: "स्वास्थ्य विभाग",
    sector: "सामाजिक विकास",
    subSector: "स्वास्थ्य",
    mainProgram: "क्षमता अभिबृध्दि",
    programName: "Basic Life Support Package सम्बन्धी तालिम",
    budget: 1000,
    budgetCode: "22511",
    sdg: { direct: "3.c(3.c.1)", indirect: "No" },
    iso37120: { direct: "No", indirect: "12.3,12.5,12.6" },
    sci2025: { direct: "Pillar No. 1/ Component No.1.2 / Indicator: I-011, MCH services", indirect: "No" },
    thematicArea: "digital-health",
    cycle: "",
    linkageScores: { sdgScore: 4, isoScore: 3, sciScore: 0, linkageType: "discussion" },
    projectPhase: generateProjectPhase(),
  },
  {
    id: "25",
    department: "स्वास्थ्य विभाग",
    sector: "सामाजिक विकास",
    subSector: "स्वास्थ्य",
    mainProgram: "महिला स्वास्थ्य स्वयंसेविका",
    programName: "महिला स्वास्थ्य स्वयंसेविका क्षमता विकास कार्यक्रम तथा तालीम ",
    budget: 1000,
    budgetCode: "22511",
    sdg: { direct: "3.c(3.c.1)", indirect: "No" },
    iso37120: { direct: "No", indirect: "12.3,12.5,12.6" },
    sci2025: { direct: "Pillar No. 1/ Component No.1.2 / Indicator: I-011, Maternal and Child health", indirect: "No" },
    thematicArea: "health-treatment",
    cycle: "",
    linkageScores: { sdgScore: 4, isoScore: 0, sciScore: 3, linkageType: "concurrence" },
    projectPhase: generateProjectPhase(),
  },
  {
    id: "26",
    department: "स्वास्थ्य विभाग",
    sector: "सामाजिक विकास",
    subSector: "स्वास्थ्य",
    mainProgram: "सामुदायिक स्वास्थ्य सेवा",
    programName: "फिजियोथेरापिस्टहरुको क्षमता विकास तथा सीप अभिवृद्धि कार्यक्रम",
    budget: 500,
    budgetCode: "22512",
    sdg: { direct: "3.c(3.c.1)", indirect: "No" },
    iso37120: { direct: "No", indirect: "12.3,12.5,12.6" },
    sci2025: { direct: "Pillar No. 1/ Component No.1.2 / Indicator: I-012, NCD prevention", indirect: "No" },
    thematicArea: "capacity-development",
    cycle: "",
    linkageScores: { sdgScore: 4, isoScore: 0, sciScore: 3, linkageType: "discussion" },
    projectPhase: generateProjectPhase(),
  },
  {
    id: "27",
    department: "स्वास्थ्य विभाग",
    sector: "सामाजिक विकास",
    subSector: "स्वास्थ्य",
    mainProgram: "सामुदायिक स्वास्थ्य सेवा",
    programName: "प्रयोगशालाकर्मीहरुको लागि क्षमता विकास तथा गुणस्तर नियन्त्रण सम्बन्धी अभिमुखिकरण तालीम",
    budget: 500,
    budgetCode: "22512",
    sdg: { direct: "3.c(3.c.1)", indirect: "No" },
    iso37120: { direct: "No", indirect: "12.3,12.5,12.6" },
    sci2025: { direct: "Pillar No. 3/ Component No.3.4 / Indicator: I-045, Medical equipment avability", indirect: "No" },
    thematicArea: "health-treatment",
    cycle: "",
    linkageScores: { sdgScore: 4, isoScore: 0, sciScore: 3, linkageType: "concurrence" },
    projectPhase: generateProjectPhase(),
  },
  {
    id: "28",
    department: "स्वास्थ्य विभाग",
    sector: "सामाजिक विकास",
    subSector: "स्वास्थ्य",
    mainProgram: "सामुदायिक स्वास्थ्य सेवा",
    programName: "सामुदायिक विद्यालयहरुमा शहरी स्वास्थ्य प्रवर्द्धन केन्द्र मार्फत किशोरीहरुमा रक्तअल्पता स्क्रिनिंङ",
    budget: 1000,
    budgetCode: "22512",
    sdg: { direct: "No", indirect: "No" },
    iso37120: { direct: "No", indirect: "12.4,12.7" },
    sci2025: { direct: "Pillar No. 1/ Component No.1.2 / Indicator: I-009, Adolescent health", indirect: "No" },
    thematicArea: "health-treatment",
    cycle: "",
    linkageScores: { sdgScore: 4, isoScore: 0, sciScore: 4, linkageType: "concurrence" },
    projectPhase: generateProjectPhase(),
  },
  {
    id: "29",
    department: "स्वास्थ्य विभाग",
    sector: "सामाजिक विकास",
    subSector: "स्वास्थ्य",
    mainProgram: "सामुदायिक स्वास्थ्य सेवा",
    programName: "सामुदायिक विद्यालयहरुमा शहरी स्वास्थ्य प्रवर्द्धन केन्द्र मार्फत दाँत तथा मुख स्वास्थ्य सेवा प्रदान गर्ने तथा सचेतना कार्यक्रम",
    budget: 1000,
    budgetCode: "22512",
    sdg: { direct: "3.8(3.8.1)", indirect: "No" },
    iso37120: { direct: "No", indirect: "12.3,12.5,12.6" },
    sci2025: { direct: "Pillar No. 1/ Component No.1.2 / Indicator: I-012, NCD, Oral health", indirect: "No" },
    thematicArea: "health-treatment",
    cycle: "",
    linkageScores: { sdgScore: 4, isoScore: 0, sciScore: 4, linkageType: "concurrence" },
    projectPhase: generateProjectPhase(),
  },
  {
    id: "30",
    department: "स्वास्थ्य विभाग",
    sector: "सामाजिक विकास",
    subSector: "स्वास्थ्य",
    mainProgram: "सामुदायिक स्वास्थ्य सेवा",
    programName: "बिद्यालय नर्सहरुको लागी क्षमता विकास र समिक्षा कार्यक्रम",
    budget: 500,
    budgetCode: "22522",
    sdg: { direct: "3.8(3.8.1)", indirect: "No" },
    iso37120: { direct: "No", indirect: "12.5" },
    sci2025: { direct: "Pillar No. 1/ Component No.1.2 / Indicator: I-011, MCH services", indirect: "No" },
    thematicArea: "health-treatment",
    cycle: "",
    linkageScores: { sdgScore: 4, isoScore: 0, sciScore: 4, linkageType: "concurrence" },
    projectPhase: generateProjectPhase(),
  },
  {
    id: "31",
    department: "स्वास्थ्य विभाग",
    sector: "सामाजिक विकास",
    subSector: "स्वास्थ्य",
    mainProgram: "सामुदायिक स्वास्थ्य सेवा",
    programName: "स्तन क्यान्सर प्रभावितका लागि कृतिम स्तन प्रोस्थेसिस तथा इमप्लान्ट उत्पादन कार्यक्रम",
    budget: 500,
    budgetCode: "22522",
    sdg: { direct: "3.8(3.8.1)", indirect: "No" },
    iso37120: { direct: "No", indirect: "12.2" },
    sci2025: { direct: "Pillar No. 1/ Component No.1.2 / Indicator: I-012, Non-communicable disease", indirect: "No" },
    thematicArea: "health-treatment",
    cycle: "",
    linkageScores: { sdgScore: 4, isoScore: 0, sciScore: 4, linkageType: "concurrence" },
    projectPhase: generateProjectPhase(),
  },
  {
    id: "32",
    department: "स्वास्थ्य विभाग",
    sector: "सामाजिक विकास",
    subSector: "स्वास्थ्य",
    mainProgram: "सामुदायिक स्वास्थ्य सेवा",
    programName: "संघीय तथा प्रदेश स्वास्थ्य मन्त्रालयसँगको सहकार्यमा स्वास्थ्य कार्यक्रमहरु संचालन ",
    budget: 500,
    budgetCode: "22522",
    sdg: { direct: "No", indirect: "No" },
    iso37120: { direct: "No", indirect: "No" },
    sci2025: { direct: "Pillar No. 2/ Component No.2.6 / Indicator: I-024, Essentials health services", indirect: "No" },
    thematicArea: "health-treatment",
    cycle: "",
    linkageScores: { sdgScore: 4, isoScore: 0, sciScore: 4, linkageType: "concurrence" },
    projectPhase: generateProjectPhase(),
  },
  {
    id: "33",
    department: "स्वास्थ्य विभाग",
    sector: "सामाजिक विकास",
    subSector: "स्वास्थ्य",
    mainProgram: "सामुदायिक स्वास्थ्य सेवा",
    programName: "जेष्ठ नागरिकहरु तथा स्तनपायी आमाहरुको लागि आयुर्वेद औषधि वितरण कार्यक्रम",
    budget: 500,
    budgetCode: "22522",
    sdg: { direct: "3.8(3.8.1)", indirect: "No" },
    iso37120: { direct: "No", indirect: "No" },
    sci2025: { direct: "Pillar No. 1/ Component No.1.2 / Indicator: I-011, MCH and Elderly health", indirect: "No" },
    thematicArea: "health-treatment",
    cycle: "",
    linkageScores: { sdgScore: 4, isoScore: 0, sciScore: 4, linkageType: "concurrence" },
    projectPhase: generateProjectPhase(),
  },
  {
    id: "34",
    department: "स्वास्थ्य विभाग",
    sector: "सामाजिक विकास",
    subSector: "स्वास्थ्य",
    mainProgram: "सामुदायिक स्वास्थ्य सेवा",
    programName: "जनस्वास्थ्य जोखिम न्यूनीकरणकालागि स्वास्थ्य सहर कार्यक्रम",
    budget: 500,
    budgetCode: "22522",
    sdg: { direct: "10", indirect: "No" },
    iso37120: { direct: "No", indirect: "12.4, 12.1" },
    sci2025: { direct: "Pillar No. 1/ Component No.1.2 / Indicator: I-012, NCD and Public health", indirect: "No" },
    thematicArea: "health-treatment",
    cycle: "",
    linkageScores: { sdgScore: 4, isoScore: 0, sciScore: 4, linkageType: "concurrence" },
    projectPhase: generateProjectPhase(),
  },

  {
    id: "35",
    department: "स्वास्थ्य विभाग",
    sector: "सामाजिक विकास",
    subSector: "स्वास्थ्य",
    mainProgram: "सामुदायिक स्वास्थ्य सेवा",
    programName: "प्रयोगशालाकर्मी तथा रेडियोग्राफरहरुलाई ल्याब तथा एक्स-रे सम्बन्धी सामाग्रीहरुको मर्मतसम्भार सम्बन्धी क्षमता विकास एवम् प्रयोगकर्ता तालिम",
    budget: 600,
    budgetCode: "22522",
    sdg: { direct: "No", indirect: "8" },
    iso37120: { direct: "No", indirect: "No" },
    sci2025: { direct: "Pillar No. 3/ Component No.3.4 / Indicator: I-045, Medical devices", indirect: "No" },
    thematicArea: "health-treatment",
    cycle: "",
    linkageScores: { sdgScore: 4, isoScore: 0, sciScore: 4, linkageType: "concurrence" },
    projectPhase: generateProjectPhase(),
  },
  {
    id: "36",
    department: "स्वास्थ्य विभाग",
    sector: "सामाजिक विकास",
    subSector: "स्वास्थ्य",
    mainProgram: "महिला स्वास्थ्य स्वयंसेविका",
    programName: "सामुदायिक महिला स्वास्थ्य स्वयंसेविका कार्यक्रमको वार्षिक समीक्षा खर्च",
    budget: 800,
    budgetCode: "22522",
    sdg: { direct: "3.c(3.c.1)", indirect: "No" },
    iso37120: { direct: "No", indirect: "No" },
    sci2025: { direct: "Pillar No. 1/ Component No.1.2 / Indicator: I-011, MCH services", indirect: "No" },
    thematicArea: "health-treatment",
    cycle: "",
    linkageScores: { sdgScore: 4, isoScore: 0, sciScore: 4, linkageType: "concurrence" },
    projectPhase: generateProjectPhase(),
  },
  {
    id: "37",
    department: "स्वास्थ्य विभाग",
    sector: "सामाजिक विकास",
    subSector: "स्वास्थ्य",
    mainProgram: "जेरियाट्रिक सेवा",
    programName: "जेरीयाट्रिक नर्सिंग केयर सम्बन्धी अभिमुखीकरण",
    budget: 500,
    budgetCode: "22522",
    sdg: { direct: "3.c(3.c.1)", indirect: "No" },
    iso37120: { direct: "No", indirect: "12.5" },
    sci2025: { direct: "Pillar No. 1/ Component No.1.2 / Indicator: I-011, Elderly care", indirect: "No" },
    thematicArea: "health-treatment",
    cycle: "",
    linkageScores: { sdgScore: 4, isoScore: 0, sciScore: 4, linkageType: "concurrence" },
     projectPhase: generateProjectPhase()
    },
  
{
    id: "38",
    department: "स्वास्थ्य विभाग",
    sector: "सामाजिक विकास",
    subSector: "स्वास्थ्य",
    mainProgram: "स्वास्थ्य तालिम",
    programName: "महिला स्वास्थ्य स्वयंसेविका अध्ययन अवलोकन कार्यक्रम",
    budget: 1000,
    budgetCode: "22522",
    sdg: { direct: "3.c(3.c.1)", indirect: "No" },
    iso37120: { direct: "No", indirect: "No" },
    sci2025: { direct: "Pillar No. 1/ Component No.1.2 / Indicator: I-011, Community health", indirect: "No" },
    thematicArea: "health-treatment",
    cycle: "",
    linkageScores: { sdgScore: 4, isoScore: 0, sciScore: 4, linkageType: "concurrence" },
    projectPhase: generateProjectPhase(), 
},
{id: "39",
  department: "स्वास्थ्य विभाग",
  sector: "सामाजिक विकास",
  subSector: "स्वास्थ्य",
  mainProgram: "सामुदायिक स्वास्थ्य सेवा",
  programName: "आयुर्वेद तथा अकुपञ्चर शिविर सञ्चालन",
  budget: 800,
  budgetCode: "22522",
  sdg: { direct: "3.8(3.8.1)", indirect: "No" },
  iso37120: { direct: "No", indirect: "12.1" },
  sci2025: { direct: "Pillar No. 1/ Component No.1.2 / Indicator: I-012, NCD and Traditional health", indirect: "No" },
  thematicArea: "health-treatment",
  cycle: "",
  linkageScores: { sdgScore: 4, isoScore: 0, sciScore: 4, linkageType: "concurrence" },
  projectPhase: generateProjectPhase(),// Key Indicators combining ISO, SDG, and SCI
},
{id: "40",
  department: "स्वास्थ्य विभाग",
  sector: "सामाजिक विकास",
  subSector: "स्वास्थ्य",
  mainProgram: "सामुदायिक स्वास्थ्य सेवा",
  programName: "परिवार नियोजन,प्रजनन स्वास्थ्य तथा किशोरकिशोरी सम्बन्धी स्वास्थ्यकर्मीहरलाई क्षमता अभिबृद्धि तथा अभिमुखीकरण कार्यक्रम",
  budget: 400,
  budgetCode: "22522",
  sdg: { direct: "3.7(3.7.1)", indirect: "No" },
  iso37120: { direct: "No", indirect: "12.4" },
  sci2025: { direct: "Pillar No. 1/ Component No.1.2 / Indicator: I-011, Sexual and Reproductive health", indirect: "No" },
  thematicArea: "health-treatment",
  cycle: "",
  linkageScores: { sdgScore: 4, isoScore: 0, sciScore: 4, linkageType: "concurrence" },
  projectPhase: generateProjectPhase(),// Key Indicators combining ISO, SDG, and SCI
},
{id: "41",
  department: "स्वास्थ्य विभाग",
  sector: "सामाजिक विकास",
  subSector: "स्वास्थ्य",
  mainProgram: "सामुदायिक स्वास्थ्य सेवा",
  programName: "Anti-Microbial Resistance Prevention का लागि Prescription Audit लगायत अन्य चेतनामुलक कार्यक्रम",
  budget: 400,
  budgetCode: "22522",
  sdg: { direct: "3.3(3.3.4)", indirect: "No" },
  iso37120: { direct: "No", indirect: "12.1" },
  sci2025: { direct: "Pillar No. 1/ Component No.1.2 / Indicator: I-012, Non-communicable disease", indirect: "No" },
  thematicArea: "health-treatment",
  cycle: "",
  linkageScores: { sdgScore: 4, isoScore: 0, sciScore: 4, linkageType: "concurrence" },
  projectPhase: generateProjectPhase(),// Key Indicators combining ISO, SDG, and SCI
},
{id: "42",
  department: "स्वास्थ्य विभाग",
  sector: "सामाजिक विकास",
  subSector: "स्वास्थ्य",
  mainProgram: "सामुदायिक स्वास्थ्य सेवा",
  programName: "सामुदायिक विद्यालयहरुमा Little Doctors कार्यक्रम संचालन  ",
  budget: 1000,
  budgetCode: "22522",
  sdg: { direct: "3.8(3.8.1)", indirect: "No" },
  iso37120: { direct: "No", indirect: "6" },
  sci2025: { direct: "Pillar No. 1/ Component No.1.2 / Indicator: I-009, Adolescent", indirect: "No" },
  thematicArea: "health-treatment",
  cycle: "",
  linkageScores: { sdgScore: 4, isoScore: 0, sciScore: 4, linkageType: "concurrence" },
  projectPhase: generateProjectPhase(),// Key Indicators combining ISO, SDG, and SCI
},
{id: "43",
  department: "स्वास्थ्य विभाग",
  sector: "सामाजिक विकास",
  subSector: "स्वास्थ्य",
  mainProgram: "सामुदायिक स्वास्थ्य सेवा",
  programName: "सामुदायिक विद्यालयहरुमा स्वास्थ्य सम्बन्धी कार्यक्रमहरु (Blood Group Indentification/Substance abuse, Teenage pregnancy Awareness/Menstrual Hygiene Management) ",
  budget: 1500,
  budgetCode: "22522",
  sdg: { direct: "3.7(3.7.1)", indirect: "No" },
  iso37120: { direct: "No", indirect: "6" },
  sci2025: { direct: "Pillar No. 1/ Component No.1.2 / Indicator: I-009, Adolescent", indirect: "No" },
  thematicArea: "health-treatment",
  cycle: "",
  linkageScores: { sdgScore: 4, isoScore: 0, sciScore: 4, linkageType: "concurrence" },
  projectPhase: generateProjectPhase(),// Key Indicators combining ISO, SDG, and SCI
},
{id: "44",
  department: "स्वास्थ्य विभाग",
  sector: "सामाजिक विकास",
  subSector: "स्वास्थ्य",
  mainProgram: "सामुदायिक स्वास्थ्य सेवा",
  programName: "शारीरिक अपाङ्गता भएका व्यक्तिहरुका लागि स्वास्थ्य कार्यक्रम",
  budget: 1500,
  budgetCode: "22522",
  sdg: { direct: "3.8(3.8.1)", indirect: "No" },
  iso37120: { direct: "No", indirect: "12.1" },
  sci2025: { direct: "Pillar No. 2/ Component No.2.2 / Indicator: I-019, Disability ", indirect: "No" },
  thematicArea: "health-treatment",
  cycle: "",
  linkageScores: { sdgScore: 4, isoScore: 0, sciScore: 4, linkageType: "concurrence" },
  projectPhase: generateProjectPhase(),// Key Indicators combining ISO, SDG, and SCI
},
{id: "45",
  department: "स्वास्थ्य विभाग",
  sector: "सामाजिक विकास",
  subSector: "स्वास्थ्य",
  mainProgram: "सामुदायिक स्वास्थ्य सेवा",
  programName: "सहरी स्वास्थ्य प्रवर्द्धनकेन्द्रहरुमा सामाजिक परीक्षण कार्यक्रम",
  budget: 500,
  budgetCode: "22522",
  sdg: { direct: "3.d(3.d.1)", indirect: "No" },
  iso37120: { direct: "No", indirect: "No" },
  sci2025: { direct: "Pillar No. 1/ Component No.1.2 / Indicator: I-011, Screening", indirect: "No" },
  thematicArea: "health-treatment",
  cycle: "",
  linkageScores: { sdgScore: 4, isoScore: 0, sciScore: 4, linkageType: "concurrence" },
  projectPhase: generateProjectPhase(),// Key Indicators combining ISO, SDG, and SCI
},
{id: "46",
  department: "स्वास्थ्य विभाग",
  sector: "सामाजिक विकास",
  subSector: "स्वास्थ्य",
  mainProgram: "सामुदायिक स्वास्थ्य सेवा",
  programName: "खोप सुदृढिकरण तथा पुर्ण खोप कार्यक्रम",
  budget: 2000,
  budgetCode: "22522",
  sdg: { direct: "3.8(3.8.1)", indirect: "No" },
  iso37120: { direct: "12.4", indirect: "No" },
  sci2025: { direct: "Pillar No. 1/ Component No.1.2 / Indicator: I-010, Immunijation", indirect: "No" },
  thematicArea: "health-treatment",
  cycle: "",
  linkageScores: { sdgScore: 4, isoScore: 0, sciScore: 4, linkageType: "concurrence" },
  projectPhase: generateProjectPhase(),// Key Indicators combining ISO, SDG, and SCI
},
{id: "47",
  department: "स्वास्थ्य विभाग",
  sector: "सामाजिक विकास",
  subSector: "स्वास्थ्य",
  mainProgram: "सामुदायिक स्वास्थ्य सेवा",
  programName: "स्वास्थ्य सम्बन्धी विभिन्न शिविर सञ्चालन, स्क्रिनिङ, तथा स्वास्थ्य परीक्षण कार्यक्रम",
  budget: 2500,
  budgetCode: "22522",
  sdg: { direct: "3.8(3.8.1)", indirect: "No" },
  iso37120: { direct: "No", indirect: "12.4" },
  sci2025: { direct: "Pillar No. 1/ Component No.1.2 / Indicator: I-011, MCH and Gernal", indirect: "No" },
  thematicArea: "health-treatment",
  cycle: "",
  linkageScores: { sdgScore: 4, isoScore: 0, sciScore: 4, linkageType: "concurrence" },
  projectPhase: generateProjectPhase(),// Key Indicators combining ISO, SDG, and SCI
},
{id: "48",
  department: "स्वास्थ्य विभाग",
  sector: "सामाजिक विकास",
  subSector: "स्वास्थ्य",
  mainProgram: "सामुदायिक स्वास्थ्य सेवा",
  programName: "बौद्धिक अपाङ्गता एवम् अटिजम भएका व्यक्तिहरुका लागि स्वास्थ्य कार्यक्रम",
  budget: 2500,
  budgetCode: "22522",
  sdg: { direct: "3.8(3.8.1)", indirect: "No" },
  iso37120: { direct: "No", indirect: "12.1,12.4" },
  sci2025: { direct: "Pillar No. 1/ Component No.1.2 / Indicator: I-011, Disabaility", indirect: "No" },
  thematicArea: "health-treatment",
  cycle: "",
  linkageScores: { sdgScore: 4, isoScore: 0, sciScore: 4, linkageType: "concurrence" },
  projectPhase: generateProjectPhase(),// Key Indicators combining ISO, SDG, and SCI
},
{id: "49",
  department: "स्वास्थ्य विभाग",
  sector: "सामाजिक विकास",
  subSector: "स्वास्थ्य",
  mainProgram: "सामुदायिक स्वास्थ्य सेवा",
  programName: "सामुदायिक विद्यालयहरुमा आँखा स्क्रिनिंङ तथा प्रारम्भिक उपचार कार्यक्रम",
  budget: 3000,
  budgetCode: "22522",
  sdg: { direct: "3.8(3.8.1)", indirect: "No" },
  iso37120: { direct: "No", indirect: "6" },
  sci2025: { direct: "Pillar No. 1/ Component No.1.2 / Indicator: I-012, Eye health", indirect: "No" },
  thematicArea: "health-treatment",
  cycle: "",
  linkageScores: { sdgScore: 4, isoScore: 0, sciScore: 4, linkageType: "concurrence" },
  projectPhase: generateProjectPhase(),// Key Indicators combining ISO, SDG, and SCI
},
{id: "50",
  department: "स्वास्थ्य विभाग",
  sector: "सामाजिक विकास",
  subSector: "स्वास्थ्य",
  mainProgram: "सामुदायिक स्वास्थ्य सेवा",
  programName: "७० वर्ष माथिका ज्येष्ठ नागरिकहरुलाई घरमै आधारभूत स्वास्थ्य सेवा कार्यक्रम",
  budget: 3000,
  budgetCode: "22522",
  sdg: { direct: "3.8(3.8.1)", indirect: "No" },
  iso37120: { direct: "No", indirect: "12.1" },
  sci2025: { direct: "Pillar No. 1/ Component No.1.2 / Indicator: I-011, Elderly health", indirect: "No" },
  thematicArea: "health-treatment",
  cycle: "",
  linkageScores: { sdgScore: 4, isoScore: 0, sciScore: 4, linkageType: "concurrence" },
  projectPhase: generateProjectPhase(),// Key Indicators combining ISO, SDG, and SCI
},
{id: "51",
  department: "स्वास्थ्य विभाग",
  sector: "सामाजिक विकास",
  subSector: "स्वास्थ्य",
  mainProgram: "महामारी रोग नियन्त्रण",
  programName: "महामारी रोग रोकथाम, नियन्त्रण तथा व्यवस्थापन",
  budget: 5000,
  budgetCode: "22522",
  sdg: { direct: "3.d(3.d.1)", indirect: "No" },
  iso37120: { direct: "No", indirect: "12.8" },
  sci2025: { direct: "Pillar No. 1/ Component No.1.2 / Indicator: I-010, Vaccination", indirect: "No" },
  thematicArea: "health-treatment",
  cycle: "",
  linkageScores: { sdgScore: 4, isoScore: 0, sciScore: 4, linkageType: "concurrence" },
  projectPhase: generateProjectPhase(),// Key Indicators combining ISO, SDG, and SCI
},
{id: "52",
  department: "स्वास्थ्य विभाग",
  sector: "सामाजिक विकास",
  subSector: "स्वास्थ्य",
  mainProgram: "शहरी स्वास्थ्य सेवा",
  programName: "जनप्रतिनिधि र कर्मचारी स्वास्थ्य विमाको प्रिमियम भुक्तानि",
  budget: 5000,
  budgetCode: "22522",
  sdg: { direct: "3.8(3.8.2)", indirect: "No" },
  iso37120: { direct: "No", indirect: "11" },
  sci2025: { direct: "NO", indirect: "Smart Governance" },
  thematicArea: "health-treatment",
  cycle: "",
  linkageScores: { sdgScore: 4, isoScore: 0, sciScore: 4, linkageType: "concurrence" },
  projectPhase: generateProjectPhase(),// Key Indicators combining ISO, SDG, and SCI
},
{id: "53",
  department: "स्वास्थ्य विभाग",
  sector: "सामाजिक विकास",
  subSector: "स्वास्थ्य",
  mainProgram: "सामुदायिक स्वास्थ्य सेवा",
  programName: "स्वास्थ्य बीमा कार्यक्रम लागु भएका स्वास्थ्य संस्थाहरुमा आवश्यकता अनुसार विशेषज्ञ सेवा विस्तार ",
  budget: 10000,
  budgetCode: "22522",
  sdg: { direct: "3.8(3.8.1)", indirect: "No" },
  iso37120: { direct: "No", indirect: "12.3" },
  sci2025: { direct: "Pillar No. 1/ Component No.1.1 / Indicator: I-004, Health Insurance", indirect: "No" },
  thematicArea: "health-treatment",
  cycle: "",
  linkageScores: { sdgScore: 4, isoScore: 0, sciScore: 4, linkageType: "concurrence" },
  projectPhase: generateProjectPhase(),// Key Indicators combining ISO, SDG, and SCI
},
{id: "54",
  department: "स्वास्थ्य विभाग",
  sector: "सामाजिक विकास",
  subSector: "स्वास्थ्य",
  mainProgram: "अनुगमन तथा मूल्याङ्कन",
  programName: "स्वास्थ्य विभागबाट हुने अनुगमन, नियमन र विज्ञका लागी पारिश्रमिक कार्यक्रम",
  budget: 1000,
  budgetCode: "22611",
  sdg: { direct: "3.d(3.d.1)", indirect: "No" },
  iso37120: { direct: "No", indirect: "12.3" },
  sci2025: { direct: "Pillar No. 1/ Component No.1.1 / Indicator: I-004, Health Insurance", indirect: "No" },
  thematicArea: "health-treatment",
  cycle: "",
  linkageScores: { sdgScore: 4, isoScore: 0, sciScore: 4, linkageType: "concurrence" },
  projectPhase: generateProjectPhase(),// Key Indicators combining ISO, SDG, and SCI
},
{id: "55",
  department: "स्वास्थ्य विभाग",
  sector: "सामाजिक विकास",
  subSector: "स्वास्थ्य",
  mainProgram: "सामुदायिक स्वास्थ्य सेवा",
  programName: "का.म.पा.का स्वास्थ्य बीमा दर्ता सहयोगीहरुका लागि सामाग्री सहयोग",
  budget: 500,
  budgetCode: "22711",
  sdg: { direct: "3.8(3.8.2)", indirect: "No" },
  iso37120: { direct: "No", indirect: "11" },
  sci2025: { direct: "No", indirect: "Smart Governance" },
  thematicArea: "health-treatment",
  cycle: "",
  linkageScores: { sdgScore: 4, isoScore: 0, sciScore: 4, linkageType: "concurrence" },
  projectPhase: generateProjectPhase(),// Key Indicators combining ISO, SDG, and SCI
},
{id: "56",
  department: "स्वास्थ्य विभाग",
  sector: "सामाजिक विकास",
  subSector: "स्वास्थ्य",
  mainProgram: "महिला स्वास्थ्य स्वयंसेविका",
  programName: "महिला सामुदायिक स्वास्थ्य स्वयंसेविका मासिक वैठक खाजा खर्च",
  budget: 1900,
  budgetCode: "22711",
  sdg: { direct: "3.c(3.c.1)", indirect: "No" },
  iso37120: { direct: "No", indirect: "11" },
  sci2025: { direct: "Pillar No. 1/ Component No.1.1/ Indicator: I-001, Maternal and Child health", indirect: "No" },
  thematicArea: "health-treatment",
  cycle: "",
  linkageScores: { sdgScore: 4, isoScore: 0, sciScore: 4, linkageType: "concurrence" },
  projectPhase: generateProjectPhase(),// Key Indicators combining ISO, SDG, and SCI
  
},
{id: "57",
  department: "स्वास्थ्य विभाग",
  sector: "सामाजिक विकास",
  subSector: "स्वास्थ्य",
  mainProgram: "क्यान्सर सेवा",
  programName: "प्रोष्टेट तथा अन्य क्यान्सर सम्बन्धी स्क्रिनिङ एवम् प्रारम्भिक उपचार",
  budget: 10000,
  budgetCode: "25312",
  sdg: { direct: "3.4(3.4.1)", indirect: "No" },
  iso37120: { direct: "No", indirect: "12.3,12.1" },
  sci2025: { direct: "Pillar No. 1/ Component No.1.1/ Indicator: I-003, Non-communicable disease", indirect: "No" },
  thematicArea: "health-treatment",
  cycle: "",
  linkageScores: { sdgScore: 4, isoScore: 0, sciScore: 4, linkageType: "concurrence" },
  projectPhase: generateProjectPhase(),// Key Indicators combining ISO, SDG, and SCI
},
{id: "58",
  department: "स्वास्थ्य विभाग",
  sector: "सामाजिक विकास",
  subSector: "स्वास्थ्य",
  mainProgram: "क्यान्सर सेवा",
  programName: "स्तन, पाठेघर, सर्भिकल क्यान्सरको स्क्रिनिङ तथा प्रारम्भिक उपचारमा सरकारी अस्पतालसँगको सहकार्य",
  budget: 20000,
  budgetCode: "25312",
  sdg: { direct: "3.4(3.4.1)", indirect: "No" },
  iso37120: { direct: "No", indirect: "12.1" },
  sci2025: { direct: "Pillar No. 1/ Component No.1.1/ Indicator: I-003, Non-communicable disease", indirect: "No" },
  thematicArea: "health-treatment",
  cycle: "",
  linkageScores: { sdgScore: 4, isoScore: 0, sciScore: 4, linkageType: "concurrence" },
  projectPhase: generateProjectPhase(),// Key Indicators combining ISO, SDG, and SCI
},
{id: "59",
  department: "स्वास्थ्य विभाग",
  sector: "सामाजिक विकास",
  subSector: "स्वास्थ्य",
  mainProgram: "सामुदायिक स्वास्थ्य सेवा",
  programName: "सरकारी वा सामुदायिक स्वास्थ्य संस्थासँगको सहकार्यमा मृगौला रोग पीडित महानगरवासीहरुलाई डायलायसिस सेवा",
  budget: 25000,
  budgetCode: "25312",
  sdg: { direct: "3.8(3.8.1)", indirect: "No" },
  iso37120: { direct: "No", indirect: "12.2" },
  sci2025: { direct: ":No", indirect: "Health and Well-being" },
  thematicArea: "health-treatment",
  cycle: "",
  linkageScores: { sdgScore: 4, isoScore: 0, sciScore: 4, linkageType: "concurrence" },
  projectPhase: generateProjectPhase(),// Key Indicators combining ISO, SDG, and SCI
},
{id: "60",
  department: "स्वास्थ्य विभाग",
  sector: "सामाजिक विकास",
  subSector: "स्वास्थ्य",
  mainProgram: "विपन्न नागरिक उपचार",
  programName: "महानगरबाट प्रदान गरिने नि:शुल्क एम्बुलेन्स सेवा सञ्चालन (प्रति महिना २४ लाखका दरले)",
  budget: 28800,
  budgetCode: "25312",
  sdg: { direct: "3.8(3.8.1)", indirect: "No" },
  iso37120: { direct: "No", indirect: "12.1, 12.3" },
  sci2025: { direct: "No", indirect: "Governance,Emergency response" },
  thematicArea: "health-treatment",
  cycle: "",
  linkageScores: { sdgScore: 4, isoScore: 0, sciScore: 4, linkageType: "concurrence" },
  projectPhase: generateProjectPhase(),// Key Indicators combining ISO, SDG, and SCI
 
},
{id: "61",
  department: "स्वास्थ्य विभाग",
  sector: "सामाजिक विकास",
  subSector: "स्वास्थ्य",
  mainProgram: "सामुदायिक स्वास्थ्य सेवा",
  programName: "प्रोटोकल अनुसार ८ पटक गर्भ जाँच गर्ने गर्भवतीहरुको स्वास्थ्य बीमाको प्रिमियम भुक्तानी",
  budget: 1000,
  budgetCode: "25315",
  sdg: { direct: "3.8(3.8.2)", indirect: "No" },
  iso37120: { direct: "No", indirect: "12.1, 12.4" },
  sci2025: { direct: "No", indirect: "Health insurance" },
  thematicArea: "health-treatment",
  cycle: "",
  linkageScores: { sdgScore: 4, isoScore: 0, sciScore: 4, linkageType: "concurrence" },
  projectPhase: generateProjectPhase(),// Key Indicators combining ISO, SDG, and SCI
},
{id: "62",
  department: "स्वास्थ्य विभाग",
  sector: "सामाजिक विकास",
  subSector: "स्वास्थ्य",
  mainProgram: "रक्त सञ्चार सेवा",
  programName: "रक्तदातामा आधारित अनुदान कार्यक्रम (प्रति रक्तदाता रु.३००)",
  budget: 2000,
  budgetCode: "25315",
  sdg: { direct: "3.8(3.8.1)", indirect: "No" },
  iso37120: { direct: "No", indirect: "No" },
  sci2025: { direct: "No", indirect: "Emergency Service" },
  thematicArea: "health-treatment",
  cycle: "",
  linkageScores: { sdgScore: 4, isoScore: 0, sciScore: 4, linkageType: "concurrence" },
  projectPhase: generateProjectPhase(),// Key Indicators combining ISO, SDG, and SCI
},
{id: "63",
  department: "स्वास्थ्य विभाग",
  sector: "सामाजिक विकास",
  subSector: "स्वास्थ्य",
  mainProgram: "रक्त सञ्चार सेवा",
  programName: "महानगरवासीहरुलाइ निःशुल्क रगत तथा रक्त तत्वको लागि नेपाल रेडक्रस सोसाईटीलाई अनुदान",
  budget: 2000,
  budgetCode: "25315",
  sdg: { direct: "3.8(3.8.1)", indirect: "No" },
  iso37120: { direct: "No", indirect: "No" },
  sci2025: { direct: "No", indirect: "Emergency Service" },
  thematicArea: "health-treatment",
  cycle: "",
  linkageScores: { sdgScore: 4, isoScore: 0, sciScore: 4, linkageType: "concurrence" },
  projectPhase: generateProjectPhase(),// Key Indicators combining ISO, SDG, and SCI 
},
{id: "64",
  department: "स्वास्थ्य विभाग",
  sector: "सामाजिक विकास",
  subSector: "स्वास्थ्य",
  mainProgram: "विपन्न नागरिक उपचार",
  programName: "अति विपन्न वर्गलाई स्वास्थ्य उपचारमा सहयोग",
  budget: 2000,
  budgetCode: "25315",
  sdg: { direct: "3.8(3.8.2)", indirect: "No" },
  iso37120: { direct: "No", indirect: "12" },
  sci2025: { direct: "No", indirect: "No" },
  thematicArea: "health-treatment",
  cycle: "",
  linkageScores: { sdgScore: 4, isoScore: 0, sciScore: 4, linkageType: "concurrence" },
  projectPhase: generateProjectPhase(),// Key Indicators combining ISO, SDG, and SCI
},
{id: "65",
  department: "स्वास्थ्य विभाग",
  sector: "सामाजिक विकास",
  subSector: "स्वास्थ्य",
  mainProgram: "विपन्न नागरिक उपचार",
  programName: "विपन्न वर्गलाई नेपाल सरकारले दिने सहयोग सोधभर्ना कार्यक्रम",
  budget: 30000,
  budgetCode: "27111",
  sdg: { direct: "3.8(3.8.2)", indirect: "No" },
  iso37120: { direct: "No", indirect: "11" },
  sci2025: { direct: "No", indirect: "Health and Well-being" },
  thematicArea: "health-treatment",
  cycle: "",
  linkageScores: { sdgScore: 4, isoScore: 0, sciScore: 4, linkageType: "concurrence" },
  projectPhase: generateProjectPhase(),// Key Indicators combining ISO, SDG, and SCI
},
{id: "66",
  department: "स्वास्थ्य विभाग",
  sector: "सामाजिक विकास",
  subSector: "स्वास्थ्य",
  mainProgram: "सामुदायिक स्वास्थ्य सेवा",
  programName: "औषधि एवम् अन्य सामाग्री ढुवानी तथा प्याकेजिंग",
  budget: 500,
  budgetCode: "27213",
  sdg: { direct: "3.8(3.8.1)", indirect: "No" },
  iso37120: { direct: "No", indirect: "No" },
  sci2025: { direct: "No", indirect: "Emergency Service" },
  thematicArea: "health-treatment",
  cycle: "",
  linkageScores: { sdgScore: 4, isoScore: 0, sciScore: 4, linkageType: "concurrence" },
  projectPhase: generateProjectPhase(),// Key Indicators combining ISO, SDG, and SCI 
},
{id: "67",
  department: "स्वास्थ्य विभाग",
  sector: "सामाजिक विकास",
  subSector: "स्वास्थ्य",
  mainProgram: "सामुदायिक स्वास्थ्य सेवा",
  programName: "संक्रमण रोकथामका लागी सामाग्री खरिद",
  budget: 1000,
  budgetCode: "27213",
  sdg: { direct: "3.d(3.d.1)", indirect: "No" },
  iso37120: { direct: "No", indirect: "12" },
  sci2025: { direct: "No", indirect: "Communicable Disease" },
  thematicArea: "health-treatment",
  cycle: "",
  linkageScores: { sdgScore: 4, isoScore: 0, sciScore: 4, linkageType: "concurrence" },
  projectPhase: generateProjectPhase(),// Key Indicators combining ISO, SDG, and SCI 
},
{id: "68",
  department: "स्वास्थ्य विभाग",
  sector: "सामाजिक विकास",
  subSector: "स्वास्थ्य",
  mainProgram: "आयुर्वेद सेवा",
  programName: "आयुर्वेद चिकित्साको लागि औषधी तथा अन्य सामान खरिद",
  budget: 2500,
  budgetCode: "27213",
  sdg: { direct: "3.8(3.8.1)", indirect: "No" },
  iso37120: { direct: "No", indirect: "12" },
  sci2025: { direct: "No", indirect: "Health and Well-being" },
  thematicArea: "health-treatment",
  cycle: "",
  linkageScores: { sdgScore: 4, isoScore: 0, sciScore: 4, linkageType: "concurrence" },
  projectPhase: generateProjectPhase(),// Key Indicators combining ISO, SDG, and SCI   
},
{id: "69",
  department: "स्वास्थ्य विभाग",
  sector: "सामाजिक विकास",
  subSector: "स्वास्थ्य",
  mainProgram: "सामुदायिक स्वास्थ्य सेवा",
  programName: "जेष्ठ नागरिकहरुको लागि निमोनिया भ्याक्सिन कार्यक्रम",
  budget: 20000,
  budgetCode: "27213",
  sdg: { direct: "3.b(3.b.1)", indirect: "No" },
  iso37120: { direct: "12(12.1, 12.4", indirect: "No" },
  sci2025: { direct: "No", indirect: "Elderly health" },
  thematicArea: "health-treatment",
  cycle: "",
  linkageScores: { sdgScore: 4, isoScore: 0, sciScore: 4, linkageType: "concurrence" },
  projectPhase: generateProjectPhase(),// Key Indicators combining ISO, SDG, and SCI  
},
{id: "70",
  department: "स्वास्थ्य विभाग",
  sector: "सामाजिक विकास",
  subSector: "स्वास्थ्य",
  mainProgram: "शहरी स्वास्थ्य सेवा",
  programName: "सहरी स्वास्थ्य प्रवर्द्धन केन्द्रहरुको घर भाडा",
  budget: 10000,
  budgetCode: "28142",
  sdg: { direct: "3.8(3.8.1)", indirect: "No" },
  iso37120: { direct: "No", indirect: "No" },
  sci2025: { direct: "No", indirect: "Health Infrastructure" },
  thematicArea: "health-treatment",
  cycle: "",
  linkageScores: { sdgScore: 4, isoScore: 0, sciScore: 4, linkageType: "concurrence" },
  projectPhase: generateProjectPhase(),// Key Indicators combining ISO, SDG, and SCI 
},
{id: "71",
  department: "स्वास्थ्य विभाग",
  sector: "सामाजिक विकास",
  subSector: "स्वास्थ्य",
  mainProgram: "औषधि व्यवस्थापन तथा नियमन",
  programName: "खोप तथा खोप सामाग्री ढुवानी (प्रति सेसन रु.५०० को दरले)",
  budget: 1000,
  budgetCode: "28143",
  sdg: { direct: "3.b(3.b.1)", indirect: "No" },
  iso37120: { direct: "No", indirect: "12.4" },
  sci2025: { direct: "No", indirect: "Health Infrastructure" },
  thematicArea: "health-treatment",
  cycle: "",
  linkageScores: { sdgScore: 4, isoScore: 0, sciScore: 4, linkageType: "concurrence" },
  projectPhase: generateProjectPhase(),// Key Indicators combining ISO, SDG, and SCI 
},
{id: "72",
  department: "स्वास्थ्य विभाग",
  sector: "सामाजिक विकास",
  subSector: "स्वास्थ्य",
  mainProgram: "शहरी स्वास्थ्य सेवा",
  programName: "सहरी स्वास्थ्य प्रवर्द्धन केन्द्रहरुमा रहेका ल्यावकक्षमा AC ब्यवस्थापन",
  budget: 3500,
  budgetCode: "31122",
  sdg: { direct: "3.8(3.8.1)", indirect: "No" },
  iso37120: { direct: "No", indirect: "12.2" },
  sci2025: { direct: "No", indirect: "Communicable Disease" },
  thematicArea: "health-treatment",
  cycle: "",
  linkageScores: { sdgScore: 4, isoScore: 0, sciScore: 4, linkageType: "concurrence" },
  projectPhase: generateProjectPhase(),// Key Indicators combining ISO, SDG, and SCI 
},
{id: "73",
  department: "स्वास्थ्य विभाग",
  sector: "सामाजिक विकास",
  subSector: "स्वास्थ्य",
  mainProgram: "शहरी स्वास्थ्य सेवा",
  programName: "सहरी स्वास्थ्य प्रवर्द्धन केन्द्रहरुमा पावर ब्याकअप खरिद",
  budget: 10000,
  budgetCode: "31122",
  sdg: { direct: "3.8(3.8.1)", indirect: "No" },
  iso37120: { direct: "No", indirect: "12.2" },
  sci2025: { direct: "No", indirect: "Communicable Disease" },
  thematicArea: "health-treatment",
  cycle: "",
  linkageScores: { sdgScore: 4, isoScore: 0, sciScore: 4, linkageType: "concurrence" },
  projectPhase: generateProjectPhase(),// Key Indicators combining ISO, SDG, and SCI 
},
{id: "74",
  department: "स्वास्थ्य विभाग",
  sector: "सामाजिक विकास",
  subSector: "स्वास्थ्य",
  mainProgram: "शहरी स्वास्थ्य सेवा",
  programName: "ल्यापटप ३५ थान, डेस्कटप ७० थान र प्रिन्टर ७० थान खरिद",
  budget: 15000,
  budgetCode: "31122",
  sdg: { direct: "3.8(3.8.1)", indirect: "No" }, 
  iso37120: { direct: "No", indirect: "12.2" },
  sci2025: { direct: "No", indirect: "Digital Inclusion" },
  thematicArea: "health-treatment",
  cycle: "",
  linkageScores: { sdgScore: 4, isoScore: 0, sciScore: 4, linkageType: "concurrence" },
  projectPhase: generateProjectPhase(),// Key Indicators combining ISO, SDG, and SCI 
},
{id: "75",
  department: "स्वास्थ्य विभाग",
  sector: "सामाजिक विकास",
  subSector: "स्वास्थ्य",
  mainProgram: "आयुर्वेद सेवा",
  programName: "आयुर्वेदिक तथा वैकल्पिक चिकित्सा केन्द्र स्थापना तथा सञ्चालन",
  budget: 2000,
  budgetCode: "31159",
  sdg: { direct: "3.8(3.8.1)", indirect: "No" },
  iso37120: { direct: "No", indirect: "No" },
  sci2025: { direct: "No", indirect: "Health Infrastructure" },
  thematicArea: "health-treatment",
  cycle: "",
  linkageScores: { sdgScore: 4, isoScore: 0, sciScore: 4, linkageType: "concurrence" },
  projectPhase: generateProjectPhase(),// Key Indicators combining ISO, SDG, and SCI 
},
{id: "76",
  department: "स्वास्थ्य विभाग",
  sector: "सामाजिक विकास",
  subSector: "स्वास्थ्य",
  mainProgram: "सामुदायिक स्वास्थ्य सेवा",
  programName: "राष्ट्रिय ट्रमा सेन्टरमा महानगरवासी र विपन्न तथा वेवारिसे विरामीहरुको लागी स्वास्थ्य सामग्री सहयोग",
  budget: 10000,
  budgetCode: "22319",
  sdg: { direct: "3.8(3.8.1)", indirect: "No" },
  iso37120: { direct: "No", indirect: "12.2" },
  sci2025: { direct: "No", indirect: "Health Infrastructure" },
  thematicArea: "health-treatment",
  cycle: "",
  linkageScores: { sdgScore: 4, isoScore: 0, sciScore: 4, linkageType: "concurrence" },
  projectPhase: generateProjectPhase(),// Key Indicators combining ISO, SDG, and SCI  
},
{id: "77",
  department: "स्वास्थ्य विभाग",
  sector: "सामाजिक विकास",
  subSector: "स्वास्थ्य",
  mainProgram: "सामुदायिक स्वास्थ्य सेवा",
  programName: "टिचिङ्ग अस्पताल तथा बीर अस्पतालमा हेल्पडेस्क सञ्चालनार्थ स्वास्थ्य सहायक पारिश्रमिक",
  budget: 3000,
  budgetCode: "22413",
  sdg: { direct: "3.8(3.8.1)", indirect: "No" },
  iso37120: { direct: "No", indirect: "11" },
  sci2025: { direct: "No", indirect: "Governance" },
  thematicArea: "health-treatment",
  cycle: "",
  linkageScores: { sdgScore: 4, isoScore: 0, sciScore: 4, linkageType: "concurrence" },
  projectPhase: generateProjectPhase(),// Key Indicators combining ISO, SDG, and SCI  
},
{id: "78",
  department: "स्वास्थ्य विभाग",
  sector: "सामाजिक विकास",
  subSector: "स्वास्थ्य",
  mainProgram: "सामुदायिक स्वास्थ्य सेवा",
  programName: "स्वास्थ्य प्रवर्धन केन्द्रका कार्यालय सहयोगी पारिश्रमिक",
  budget: 7500,
  budgetCode: "27213",
  sdg: { direct: "3.c(3.c.1)", indirect: "No" },
  iso37120: { direct: "No", indirect: "11" },
  sci2025: { direct: "No", indirect: "Health Infrastructure" },
  thematicArea: "health-treatment",
  cycle: "",
  linkageScores: { sdgScore: 4, isoScore: 0, sciScore: 4, linkageType: "concurrence" },
  projectPhase: generateProjectPhase(),// Key Indicators combining ISO, SDG, and SCI 
},
{id: "79",
  department: "स्वास्थ्य विभाग",
  sector: "सामाजिक विकास",
  subSector: "स्वास्थ्य",
  mainProgram: "सामुदायिक स्वास्थ्य सेवा",
  programName: "स्थानीयलाई प्राथमिक उपचार तालिम(ठुला वडा २ लाख, मझौला वडा १.५ लाख र साना वडा १ लाख का दरले )",
  budget: 5250,
  budgetCode: "22511",
  sdg: { direct: "3.d(3.d.1)", indirect: "No" },
  iso37120: { direct: "No", indirect: "12.1" },
  sci2025: { direct: "Pillar No. 1/ Component No.1.1 / Indicator: I-001, Average life expectancy", indirect: "No" },
  thematicArea: "health-treatment",
  cycle: "",
  linkageScores: { sdgScore: 4, isoScore: 0, sciScore: 4, linkageType: "concurrence" },
  projectPhase: generateProjectPhase(),// Key Indicators combining ISO, SDG, and SCI  
},
{id: "80",
  department: "स्वास्थ्य विभाग",
  sector: "सामाजिक विकास",
  subSector: "स्वास्थ्य",
  mainProgram: "सामुदायिक स्वास्थ्य सेवा",
  programName: "अनलाइन डाक्टर सेवा कार्यक्रम संचालन खर्च (Pilot Project)",
  budget: 500,
  budgetCode: "22522",
  sdg: { direct: "3.8(3.8.1)", indirect: "No" },
  iso37120: { direct: "12.3", indirect: "No" },
  sci2025: { direct: "No", indirect: "E-Service" },
  thematicArea: "health-treatment",
  cycle: "",
  linkageScores: { sdgScore: 4, isoScore: 0, sciScore: 4, linkageType: "concurrence" },
  projectPhase: generateProjectPhase(),// Key Indicators combining ISO, SDG, and SCI 
},
{id: "81",
  department: "स्वास्थ्य विभाग",
  sector: "सामाजिक विकास",
  subSector: "स्वास्थ्य",
  mainProgram: "सामुदायिक स्वास्थ्य सेवा",
  programName: "स्वास्थ्य प्रोफाइल निर्माण कार्यक्रम ( Free Health portal upgrade समेत )",
  budget: 2000,
  budgetCode: "22522",
  sdg: { direct: "3.8(3.8.1)", indirect: "No" },
  iso37120: { direct: "No", indirect: "No" },
  sci2025: { direct: "No", indirect: "No" },
  thematicArea: "health-treatment",
  cycle: "",
  linkageScores: { sdgScore: 4, isoScore: 0, sciScore: 4, linkageType: "concurrence" },
  projectPhase: generateProjectPhase(),// Key Indicators combining ISO, SDG, and SCI  
},
{id: "82",
  department: "स्वास्थ्य विभाग",
  sector: "सामाजिक विकास",
  subSector: "स्वास्थ्य",
  mainProgram: "सामुदायिक स्वास्थ्य सेवा",
  programName: "हेल्थ एट स्कुल नियमित स्वास्थ्य परिक्षण शिबिर संचालन (हरेक बिद्यालयमा मासिक शहरी स्वास्थ्य प्रबर्धन केन्द्रको सहकार्यमा)",
  budget: 5000,
  budgetCode: "22522",
  sdg: { direct: "3.8(3.8.1)", indirect: "No" },
  iso37120: { direct: "No", indirect: "6" },
  sci2025: { direct: "No", indirect: "Education" },
  thematicArea: "health-treatment",
  cycle: "",
  linkageScores: { sdgScore: 4, isoScore: 0, sciScore: 4, linkageType: "concurrence" },
  projectPhase: generateProjectPhase(),// Key Indicators combining ISO, SDG, and SCI 
},
{id: "83",
  department: "स्वास्थ्य विभाग",
  sector: "सामाजिक विकास",
  subSector: "स्वास्थ्य",
  mainProgram: "प्रयोगशाला सेवा",
  programName: "Dear Health Trust लाई ल्याव स्थापना सहयोग",
  budget: 5000,
  budgetCode: "25312",
  sdg: { direct: "3.c(3.c.1)", indirect: "No" },
  iso37120: { direct: "No", indirect: "6" },
  sci2025: { direct: "Pillar No. 3/ Component No.3.6 / Indicator: I-052, Sustainable Management", indirect: "No" },
  thematicArea: "health-treatment",
  cycle: "",
  linkageScores: { sdgScore: 4, isoScore: 0, sciScore: 4, linkageType: "concurrence" },
  projectPhase: generateProjectPhase(),// Key Indicators combining ISO, SDG, and SCI 
},
{id: "84",
  department: "स्वास्थ्य विभाग",
  sector: "सामाजिक विकास",
  subSector: "स्वास्थ्य",
  mainProgram: "सामुदायिक स्वास्थ्य सेवा",
  programName: "नेपाल औषधि लिमिटेडसँग औषधि उत्पादन साझेदारी अनुदान",
  budget: 10000,
  budgetCode: "25312",
  sdg: { direct: "3.b(3.b.1)", indirect: "No" },
  iso37120: { direct: "No", indirect: "11" },
  sci2025: { direct: "No", indirect: "Health and Well-being" },
  thematicArea: "health-treatment",
  cycle: "",
  linkageScores: { sdgScore: 4, isoScore: 0, sciScore: 4, linkageType: "concurrence" },
  projectPhase: generateProjectPhase(),// Key Indicators combining ISO, SDG, and SCI 
},
{id: "85",
  department: "स्वास्थ्य विभाग",
  sector: "सामाजिक विकास",
  subSector: "स्वास्थ्य",
  mainProgram: "सामुदायिक स्वास्थ्य सेवा",
  programName: "मनमोहन कार्डियोथोरासिक भास्कुलर एण्ड ट्रान्सप्लान्ट सेन्टरको सि.सि.यु सबलीकरणका लागि सहयोग",
  budget: 10000,
  budgetCode: "25312",
  sdg: { direct: "3.c(3.c.1)", indirect: "No" },
  iso37120: { direct: "12.2", indirect: "No" },
  sci2025: { direct: "No", indirect: "Health Infrastructure" },
  thematicArea: "health-treatment",
  cycle: "",
  linkageScores: { sdgScore: 4, isoScore: 0, sciScore: 4, linkageType: "concurrence" },
  projectPhase: generateProjectPhase(),// Key Indicators combining ISO, SDG, and SCI  
},
{id: "86",
  department: "स्वास्थ्य विभाग",
  sector: "सामाजिक विकास",
  subSector: "स्वास्थ्य",
  mainProgram: "सामुदायिक स्वास्थ्य सेवा",
  programName: "का.म.पा.का स्वास्थ्य प्रवर्द्धन केन्द्रहरुको फोहोरमैला व्यवस्थापनको लागि परोपकार प्रसूति तथा स्त्रीरोग अस्पतालमा प्लान्ट निर्माण अनुदान",
  budget: 20000,
  budgetCode: "25312",
  sdg: { direct: "No", indirect: "No" },
  iso37120: { direct: "No", indirect: "16.1" },
  sci2025: { direct: "No", indirect: "Environment" },
  thematicArea: "health-treatment",
  cycle: "",
  linkageScores: { sdgScore: 4, isoScore: 0, sciScore: 4, linkageType: "concurrence" },
  projectPhase: generateProjectPhase(),// Key Indicators combining ISO, SDG, and SCI 
},
{id: "87",
  department: "स्वास्थ्य विभाग",
  sector: "सामाजिक विकास",
  subSector: "स्वास्थ्य",
  mainProgram: "सामुदायिक स्वास्थ्य सेवा",
  programName: " नेपाल औषधि लिमिटेडसंगको सहकार्यमा औषधि उत्पादन तथा निशुल्क वितरण ",
  budget: 40000,
  budgetCode: "25312",
  sdg: { direct: "3.b(3.b.1)", indirect: "No" },
  iso37120: { direct: "12.1, 12.4", indirect: "No" },
  sci2025: { direct: "No", indirect: "Smart Govrnance" },
  thematicArea: "health-treatment",
  cycle: "",
  linkageScores: { sdgScore: 4, isoScore: 0, sciScore: 4, linkageType: "concurrence" },
  projectPhase: generateProjectPhase(),// Key Indicators combining ISO, SDG, and SCI  
},
{id: "88",
  department: "स्वास्थ्य विभाग",
  sector: "सामाजिक विकास",
  subSector: "स्वास्थ्य",
  mainProgram: "सामुदायिक स्वास्थ्य सेवा",
  programName: "वडा ६ को स्वास्थ्य प्रबर्धन केन्द्र लाइ २५ शैया आकस्मिक अस्पताल स्तरोन्नति",
  budget: 20000,
  budgetCode: "31112",
  sdg: { direct: "3.c(3.c.1)", indirect: "No" },
  iso37120: { direct: "12.2", indirect: "No" },
  sci2025: { direct: "No", indirect: "Health Infrastructure" },
  thematicArea: "health-treatment",
  cycle: "",
  linkageScores: { sdgScore: 4, isoScore: 0, sciScore: 4, linkageType: "concurrence" },
  projectPhase: generateProjectPhase(),// Key Indicators combining ISO, SDG, and SCI  
},
{id: "89",
  department: "स्वास्थ्य विभाग",
  sector: "सामाजिक विकास",
  subSector: "स्वास्थ्य",
  mainProgram: "विपन्न नागरिक उपचार",
  programName: "विभिन्न ३५ वटा गाउँपालिकाहरुलाई मागका आधारमा एम्बुलेन्स अनुदान सहयोग",
  budget: 81000,
  budgetCode: "25312",
  sdg: { direct: "3.8(3.8.1)", indirect: "No" },
  iso37120: { direct: "12.2", indirect: "No" },
  sci2025: { direct: "No", indirect: "Smart Governance" },
  thematicArea: "health-treatment",
  cycle: "",
  linkageScores: { sdgScore: 4, isoScore: 0, sciScore: 4, linkageType: "concurrence" },
  projectPhase: generateProjectPhase(),// Key Indicators combining ISO, SDG, and SCI 
},
{id: "90",
  department: "स्वास्थ्य विभाग",
  sector: "सामाजिक विकास",
  subSector: "स्वास्थ्य",
  mainProgram: "सामुदायिक स्वास्थ्य सेवा",
  programName: "जेष्ठ नागरिकहरुको लागि निमोनिया भ्याक्सिन कार्यक्रम",
  budget: 9900,
  budgetCode: "27213",
  sdg: { direct: "3.b(3.b.1)", indirect: "No" },
  iso37120: { direct: "12.4", indirect: "No" },
  sci2025: { direct: "No", indirect: "Smart Governance" },
  thematicArea: "health-treatment",
  cycle: "",
  linkageScores: { sdgScore: 4, isoScore: 0, sciScore: 4, linkageType: "concurrence" },
  projectPhase: generateProjectPhase(),// Key Indicators combining ISO, SDG, and SCI 
 },
{id: "91",
  department: "स्वास्थ्य विभाग",
  sector: "सामाजिक विकास",
  subSector: "स्वास्थ्य",
  mainProgram: "सामुदायिक स्वास्थ्य सेवा",
  programName: "सवारी साधन र एम्बुलेन्स खरिद",
  budget: 7000,
  budgetCode: "31121",
  sdg: { direct: "3.8(3.8.1)", indirect: "No" },
  iso37120: { direct: "12.3", indirect: "No" },
  sci2025: { direct: "Pillar No. 1/ Component No.1.1 / Indicator: I-001, Average life expectancy", indirect: "No" },
  thematicArea: "health-treatment",
  cycle: "",
  linkageScores: { sdgScore: 4, isoScore: 0, sciScore: 4, linkageType: "concurrence" },
  projectPhase: generateProjectPhase(),// Key Indicators combining ISO, SDG, and SCI 
},
{id: "92",
  department: "स्वास्थ्य विभाग",
  sector: "सामाजिक विकास",
  subSector: "स्वास्थ्य",
  mainProgram: "सामुदायिक स्वास्थ्य सेवा",
  programName: "त्रिभुवन विश्‍वविद्यालय शिक्षण अस्पताललाई HI Tech OPD र Electronics Health Information System निर्माण तथा सञ्चालन",
  budget: 20000,
  budgetCode: "31159",
  sdg: { direct: "3.c(3.c.1)", indirect: "No" },
  iso37120: { direct: "12.2", indirect: "No" },
  sci2025: { direct: "No", indirect: "Health Infrastructure" },
  thematicArea: "health-treatment",
  cycle: "",
  linkageScores: { sdgScore: 4, isoScore: 0, sciScore: 4, linkageType: "concurrence" },
  projectPhase: generateProjectPhase(),// Key Indicators combining ISO, SDG, and SCI  
},
{id: "93",
  department: "स्वास्थ्य विभाग",
  sector: "सामाजिक विकास",
  subSector: "स्वास्थ्य",
  mainProgram: "सार्वजनिक निर्माण सुधार",
  programName: "कान्ति बाल अस्पतालमा मोडुलर अपरेशन थिएटर निर्माण",
  budget: 55000,
  budgetCode: "31159",
  sdg: { direct: "3.c(3.c.1)", indirect: "No" },
  iso37120: { direct: "12.2", indirect: "No" },
  sci2025: { direct: "No", indirect: "Health Infrastructure" },
  thematicArea: "health-treatment",
  cycle: "",
  linkageScores: { sdgScore: 4, isoScore: 0, sciScore: 4, linkageType: "concurrence" },
  projectPhase: generateProjectPhase(),// Key Indicators combining ISO, SDG, and SCI   
},
{id: "94",
  department: "स्वास्थ्य विभाग",
  sector: "सामाजिक विकास",
  subSector: "स्वास्थ्य",
  mainProgram: "शहरी स्वास्थ्य सेवा",
  programName: " ल्याब रिएजेन्ट तथा एक्स रे फ्लिम खरिद",
  budget: 20000,
  budgetCode: "31122",
  sdg: { direct: "3.8(3.8.1)", indirect: "No" },
  iso37120: { direct: "12.3", indirect: "No" },
  sci2025: { direct: "Pillar No. 1/ Component No.1.1/ Indicator: I-003, Non-communicable disease", indirect: "No" },
  thematicArea: "health-treatment",
  cycle: "",
  linkageScores: { sdgScore: 4, isoScore: 0, sciScore: 4, linkageType: "concurrence" },
  projectPhase: generateProjectPhase(),// Key Indicators combining ISO, SDG, and SCI  
},
{id: "95",
  department: "स्वास्थ्य विभाग",
  sector: "सामाजिक विकास",
  subSector: "स्वास्थ्य",
  mainProgram: "शहरी स्वास्थ्य सेवा",
  programName: "सेन्ट्रल ल्याबको लागी उपकरण खरिद",
  budget: 10000,
  budgetCode: "31159",
  sdg: { direct: "3.c(3.c.1)", indirect: "No" },
  iso37120: { direct: "12.3, 12.2", indirect: "No" },
  sci2025: { direct: "No", indirect: "Smart Governance" },
  thematicArea: "health-treatment",
  cycle: "",
  linkageScores: { sdgScore: 4, isoScore: 0, sciScore: 4, linkageType: "concurrence" },
  projectPhase: generateProjectPhase(),// Key Indicators combining ISO, SDG, and SCI 
},
{id: "96",
  department: "स्वास्थ्य विभाग",
  sector: "सामाजिक विकास",
  subSector: "स्वास्थ्य",
  mainProgram: "शहरी स्वास्थ्य सेवा",
  programName: "पूर्वाधार निर्माण( फर्निचर, रङ्गरोगन, पार्टेसन, डेकोरेसन, विद्युत व्यवस्थापन लगायत) दुई स्थानमा रु.दश लाखको दरले ",
  budget: 2000,
  budgetCode: "31123",
  sdg: { direct: "3.c(3.c.1)", indirect: "No" },
  iso37120: { direct: "12.2", indirect: "No" },
  sci2025: { direct: "No", indirect: "Health Infrastructure" },
  thematicArea: "health-treatment",
  cycle: "",
  linkageScores: { sdgScore: 4, isoScore: 0, sciScore: 4, linkageType: "concurrence" },
  projectPhase: generateProjectPhase(),// Key Indicators combining ISO, SDG, and SCI  
},
{id: "97",
  department: "स्वास्थ्य विभाग",
  sector: "सामाजिक विकास",
  subSector: "स्वास्थ्य",
  mainProgram: "शहरी स्वास्थ्य सेवा",
  programName: "सफ्टवेयर",
  budget: 500,
  budgetCode: "31134",
  sdg: { direct: "3.c(3.c.1)", indirect: "No" },
  iso37120: { direct: "No", indirect: "7.5.1" },
  sci2025: { direct: "No", indirect: "ICT Infrastructure" },
  thematicArea: "health-treatment",
  cycle: "",
  linkageScores: { sdgScore: 4, isoScore: 0, sciScore: 4, linkageType: "concurrence" },
  projectPhase: generateProjectPhase(),// Key Indicators combining ISO, SDG, and SCI 
},
{id: "98",
  department: "स्वास्थ्य विभाग",
  sector: "सामाजिक विकास",
  subSector: "स्वास्थ्य",
  mainProgram: "शहरी स्वास्थ्य सेवा",
  programName: "जनशक्ति व्यवस्थापन (फार्मासिस्ट २ जना, फार्मेसी सहायक - ६ जना, कार्यालय सहयोगी- ४ जना)",
  budget: 6000,
  budgetCode: "22413",
  sdg: { direct: "3.c(3.c.1)", indirect: "No" },
  iso37120: { direct: "12.3, 12.5", indirect: "No" },
  sci2025: { direct: "No", indirect: "productivity and job creation" },
  thematicArea: "health-treatment",
  cycle: "",
  linkageScores: { sdgScore: 4, isoScore: 0, sciScore: 4, linkageType: "concurrence" },
  projectPhase: generateProjectPhase(),// Key Indicators combining ISO, SDG, and SCI 
},
{id: "99",
  department: "स्वास्थ्य विभाग",
  sector: "सामाजिक विकास",
  subSector: "स्वास्थ्य",
  mainProgram: "शहरी स्वास्थ्य सेवा",
  programName: "ICT सामाग्री खरिद दुई स्थान",
  budget: 1000,
  budgetCode: "31122",
  sdg: { direct: "3.c(3.c.1)", indirect: "No" },
  iso37120: { direct: "No", indirect: "7.5.1" },
  sci2025: { direct: "No", indirect: "ICT Infrastructure" },
  thematicArea: "health-treatment",
  cycle: "",
  linkageScores: { sdgScore: 4, isoScore: 0, sciScore: 4, linkageType: "concurrence" },
  projectPhase: generateProjectPhase(),// Key Indicators combining ISO, SDG, and SCI 
},

{id: "87",



  department: "स्वास्थ्य विभाग",
  sector: "सामाजिक विकास",
  subSector: "स्वास्थ्य",
  mainProgram: "शहरी स्वास्थ्य सेवा",
  programName: "सरसफाई तथा पानी ",
  budget: 100,
  budgetCode: "22711",
  sdg: { direct: "No", indirect: "No" },
  iso37120: { direct: "12.4", indirect: "No" },
  sci2025: { direct: "Pillar No. 1/ Component No.1.1/ Indicator: I-003, Non-communicable disease", indirect: "No" },
  thematicArea: "health-treatment",
  cycle: "",
  linkageScores: { sdgScore: 4, isoScore: 0, sciScore: 4, linkageType: "concurrence" },

  projectPhase: generateProjectPhase(),},// Key Indicators combining ISO, SDG, and SCI  
  
{id: "101",
  department: "स्वास्थ्य विभाग",
  sector: "सामाजिक विकास",
  subSector: "स्वास्थ्य",
  mainProgram: "शहरी स्वास्थ्य सेवा",
  programName: "रेफ्रिजेरेटर तथा एसी ",
  budget: 600,
  budgetCode: "31122",
  sdg: { direct: "3.c(3.c.1)", indirect: "No" },
  iso37120: { direct: "No", indirect: "7.5.1" },
  sci2025: { direct: "No", indirect: "Health Infrastructure" },
  thematicArea: "health-treatment",
  cycle: "",
  linkageScores: { sdgScore: 4, isoScore: 0, sciScore: 4, linkageType: "concurrence" },
  projectPhase: generateProjectPhase()}// Key Indicators combining ISO, SDG, and SCI 
 ,
{id: "102",
  department: "स्वास्थ्य विभाग",
  sector: "सामाजिक विकास",
  subSector: "स्वास्थ्य",
  mainProgram: "शहरी स्वास्थ्य सेवा",
  programName: "विज्ञ परामर्श सेवा तथा बैठक संचालन",
  budget: 150,
  budgetCode: "22413",
  sdg: { direct: "3.c(3.c.1)", indirect: "No" },
  iso37120: { direct: "12.3", indirect: "No" },
  sci2025: { direct: "No", indirect: "Health Infrastructure" },
  thematicArea: "health-treatment",
  cycle: "",
  linkageScores: { sdgScore: 4, isoScore: 0, sciScore: 4, linkageType: "concurrence" },
  projectPhase: generateProjectPhase()}// Key Indicators combining ISO, SDG, and SCI 
 ,
{id: "103",
  department: "स्वास्थ्य विभाग",
  sector: "सामाजिक विकास",
  subSector: "स्वास्थ्य",
  mainProgram: "शहरी स्वास्थ्य सेवा",
  programName: "औषधि तथा औषधिजन्य सामाग्री खरिद",
  budget: 29150,
  budgetCode: "27213",
  sdg: { direct: "3.b(3.b.3)", indirect: "No" },
  iso37120: { direct: "No", indirect: "No" },
  sci2025: { direct: "No", indirect: "Health Infrastructure" },
  thematicArea: "health-treatment",
  cycle: "",
  linkageScores: { sdgScore: 4, isoScore: 0, sciScore: 4, linkageType: "concurrence" },
  projectPhase: generateProjectPhase()}// Key Indicators combining ISO, SDG, and SCI  
 ,
{id: "104",
  department: "स्वास्थ्य विभाग",
  sector: "सामाजिक विकास",
  subSector: "स्वास्थ्य",
  mainProgram: "शहरी स्वास्थ्य सेवा",
  programName: "फार्मेसी संचालन खर्च",
  budget: 500,
  budgetCode: "22522",
  sdg: { direct: "3.8(3.8.1)", indirect: "No" },
  iso37120: { direct: "No", indirect: "9" },
  sci2025: { direct: "No", indirect: "No" },
  thematicArea: "health-treatment",
  cycle: "",
  linkageScores: { sdgScore: 4, isoScore: 0, sciScore: 4, linkageType: "concurrence" },
  projectPhase: generateProjectPhase()}// Key Indicators combining ISO, SDG, and SCI 
 ,
{id: "105",
  department: "स्वास्थ्य विभाग",
  sector: "सामाजिक विकास",
  subSector: "स्वास्थ्य",
  mainProgram: "पोषणयुक्त आहार निर्माण",
  programName: "अनुगनम सामग्री खरिद (Food testing material, chemicals & device)",
  budget: 1000,
  budgetCode: "22611",
  sdg: { direct: "3.9(3.9.3)", indirect: "No" },
  iso37120: { direct: "No", indirect: "11" },
  sci2025: { direct: "No", indirect: "Economic Infrastructure" },
  thematicArea: "health-treatment",
  cycle: "",
  linkageScores: { sdgScore: 4, isoScore: 0, sciScore: 4, linkageType: "concurrence" },
  projectPhase: generateProjectPhase()}// Key Indicators combining ISO, SDG, and SCI   export const keyIndicators = [
  ,
{id: "106",
  department: "स्वास्थ्य विभाग",
  sector: "सामाजिक विकास",
  subSector: "स्वास्थ्य",
  mainProgram: "पोषणयुक्त आहार निर्माण",
  programName: "खाद्य प्रविधि तथा गुण नियन्त्रण विभागको सहकार्यमा संयुक्त अनुगमन ",
  budget: 1500,
  budgetCode: "22611",
  sdg: { direct: "3.9(3.9.3)", indirect: "No" },
  iso37120: { direct: "No", indirect: "11" },
  sci2025: { direct: "No", indirect: "Smart Governance" },
  thematicArea: "health-treatment",
  cycle: "",
  linkageScores: { sdgScore: 4, isoScore: 0, sciScore: 4, linkageType: "concurrence" },
  projectPhase: generateProjectPhase()}// Key Indicators combining ISO, SDG, and SCI 
  ,
{id: "107",
  department: "स्वास्थ्य विभाग",
  sector: "सामाजिक विकास",
  subSector: "स्वास्थ्य",
  mainProgram: "पोषणयुक्त आहार निर्माण",
  programName: "नियमित कार्यतालिका बनाई गरिने बजार अनुगमन ",
  budget: 500,
  budgetCode: "22611",
  sdg: { direct: "No", indirect: "No" },
  iso37120: { direct: "No", indirect: "11" },
  sci2025: { direct: "No", indirect: "Smart Governance" },
  thematicArea: "health-treatment",
  cycle: "",
  linkageScores: { sdgScore: 4, isoScore: 0, sciScore: 4, linkageType: "concurrence" },
  projectPhase: generateProjectPhase()}// Key Indicators combining ISO, SDG, and SCI 
 ,
{id: "108",
  department: "स्वास्थ्य विभाग",
  sector: "सामाजिक विकास",
  subSector: "स्वास्थ्य",
  mainProgram: "पोषणयुक्त आहार निर्माण",
  programName: "महानगरको मापदण्ड पुरा गरेका, यस क्षेत्रमा अनुभव प्राप्त गरेका स्वतन्त्र खाद्य निरिक्षकहरुको सुचिकृत र प्रमाणिकरण",
  budget: 1000,
  budgetCode: "22711",
  sdg: { direct: "No", indirect: "No" },
  iso37120: { direct: "No", indirect: "11" },
  sci2025: { direct: "No", indirect: "Smart Governance" },
  thematicArea: "health-treatment",
  cycle: "",
  linkageScores: { sdgScore: 4, isoScore: 0, sciScore: 4, linkageType: "concurrence" },
  projectPhase: generateProjectPhase()}// Key Indicators combining ISO, SDG, and SCI 
 ,
{id: "109",
  department: "स्वास्थ्य विभाग",
  sector: "सामाजिक विकास",
  subSector: "स्वास्थ्य",
  mainProgram: "पोषणयुक्त आहार निर्माण",
  programName: "खाद्य स्वच्छता प्रवर्धन तथा प्रमाणिकरणका लागि Food Safety Boot Camp कार्यक्रम",
  budget: 2500,
  budgetCode: "22522",
  sdg: { direct: "No", indirect: "No" },
  iso37120: { direct: "No", indirect: "11" },
  sci2025: { direct: "No", indirect: "Smart Governance" },
  thematicArea: "health-treatment",
  cycle: "",
  linkageScores: { sdgScore: 4, isoScore: 0, sciScore: 4, linkageType: "concurrence" },
  projectPhase: generateProjectPhase()}// Key Indicators combining ISO, SDG, and SCI  
 ,
{id: "110",
  department: "स्वास्थ्य विभाग",
  sector: "सामाजिक विकास",
  subSector: "स्वास्थ्य",
  mainProgram: "पोषणयुक्त आहार निर्माण",
  programName: "कार्ययोजना बमोजिम “Safe Food Kathmandu” अभियान सञ्चालन",
  budget: 2000,
  budgetCode: "22522",
  sdg: { direct: "No", indirect: "No" },
  iso37120: { direct: "No", indirect: "11" },
  sci2025: { direct: "No", indirect: "Smart Governance" },
  thematicArea: "health-treatment",
  cycle: "",
  linkageScores: { sdgScore: 4, isoScore: 0, sciScore: 4, linkageType: "concurrence" },
  projectPhase: generateProjectPhase()}// Key Indicators combining ISO, SDG, and SCI 
 ,
{id: "111",
  department: "स्वास्थ्य विभाग",
  sector: "सामाजिक विकास",
  subSector: "स्वास्थ्य",
  mainProgram: "पोषणयुक्त आहार निर्माण",
  programName: "विभिन्न कार्यका लागि चेकलिस्ट, अध्ययन सामाग्री लगायतका आवश्यक छपाई सामग्री",
  budget: 200,
  budgetCode: "22135",
  sdg: { direct: "No", indirect: "No" },
  iso37120: { direct: "No", indirect: "11" },
  sci2025: { direct: "No", indirect: "Education Infrastructure" },
  thematicArea: "health-treatment",
  cycle: "",
  linkageScores: { sdgScore: 4, isoScore: 0, sciScore: 4, linkageType: "concurrence" },
  projectPhase: generateProjectPhase()}// Key Indicators combining ISO, SDG, and SCI  
  ,
{id: "112",
  department: "स्वास्थ्य विभाग",
  sector: "सामाजिक विकास",
  subSector: "स्वास्थ्य",
  mainProgram: "पोषणयुक्त आहार निर्माण",
  programName: "प्रयोगशाला उपकरण खरिद तथा संचालन",
  budget: 10000,
  budgetCode: "31122",
  sdg: { direct: "3.d(3.d.1)", indirect: "No" },
  iso37120: { direct: "No", indirect: "9" },
  sci2025: { direct: "No", indirect: "Health Infrastructure" },
  thematicArea: "health-treatment",
  cycle: "",
  linkageScores: { sdgScore: 4, isoScore: 0, sciScore: 4, linkageType: "concurrence" },
  projectPhase: generateProjectPhase()}// Key Indicators combining ISO, SDG, and SCI
  ,
{id: "113",
  department: "स्वास्थ्य विभाग",
  sector: "सामाजिक विकास",
  subSector: "स्वास्थ्य",
  mainProgram: "पोषणयुक्त आहार निर्माण",
  programName: "खाद्य स्वच्छता सम्वन्धि गोष्ठी/ कार्यशाला/ प्रेस मिट आवधिक",
  budget: 400,
  budgetCode: "22512",
  sdg: { direct: "3.9(3.9.3)", indirect: "No" },
  iso37120: { direct: "No", indirect: "11" },
  sci2025: { direct: "No", indirect: "Smart Governance" },
  thematicArea: "health-treatment",
  cycle: "",
  linkageScores: { sdgScore: 4, isoScore: 0, sciScore: 4, linkageType: "concurrence" },
  projectPhase: generateProjectPhase()}// Key Indicators combining ISO, SDG, and SCI
  ,
{id: "114",
  department: "स्वास्थ्य विभाग",
  sector: "सामाजिक विकास",
  subSector: "स्वास्थ्य",
  mainProgram: "पोषणयुक्त आहार निर्माण",
  programName: "नेपाल खाद्य वैज्ञानिक तथा प्राविधिज्ञ संघसंगको सहकार्यमा गरिने कार्यक्रम",
  budget: 500,
  budgetCode: "22522",
  sdg: { direct: "3.9(3.9.3)", indirect: "No" },
  iso37120: { direct: "No", indirect: "11" },
  sci2025: { direct: "No", indirect: "Smart Governance" },
  thematicArea: "health-treatment",
  cycle: "",
  linkageScores: { sdgScore: 4, isoScore: 0, sciScore: 4, linkageType: "concurrence" },
  projectPhase: generateProjectPhase()}// Key Indicators combining ISO, SDG, and SCI
 ,
{id: "115",
  department: "स्वास्थ्य विभाग",
  sector: "सामाजिक विकास",
  subSector: "स्वास्थ्य",
  mainProgram: "पोषणयुक्त आहार निर्माण",
  programName: "बिबिध",
  budget: 400,
  budgetCode: "22711",
  sdg: { direct: "No", indirect: "No" },
  iso37120: { direct: "No", indirect: "6" },
  sci2025: { direct: "Title Not Clear", indirect: "Title Not Clear" },
  thematicArea: "health-treatment",
  cycle: "",
  linkageScores: { sdgScore: 4, isoScore: 0, sciScore: 4, linkageType: "concurrence" },
  projectPhase: generateProjectPhase()}// Key Indicators combining ISO, SDG, and SCI
  ,
{id: "116",
  department: "स्वास्थ्य विभाग",
  sector: "सामाजिक विकास",
  subSector: "स्वास्थ्य",
  mainProgram: "स्वस्थ जीवनशैली सम्बन्धी कार्यक्रम",
  programName: "कार्ययोजनाको आधार मा आरोग्य जीवन परियोजना कार्यान्वयन",
  budget: 18000,
  budgetCode: "22522",
  sdg: { direct: "3.8(3.8.1)", indirect: "No" },
  iso37120: { direct: "No", indirect: "No" },
  sci2025: { direct: "No", indirect: "Smart Governance" },
  thematicArea: "health-treatment",
  cycle: "",
  linkageScores: { sdgScore: 4, isoScore: 0, sciScore: 4, linkageType: "concurrence" },
  projectPhase: generateProjectPhase()}// Key Indicators combining ISO, SDG, and SCI
  ,
{id: "117",
  department: "स्वास्थ्य विभाग",
  sector: "सामाजिक विकास",
  subSector: "स्वास्थ्य",
  mainProgram: "स्वस्थ जीवनशैली सम्बन्धी कार्यक्रम",
  programName: "खुला व्यायामशाला हरुको आकस्मिक मर्मत सम्भार",
  budget: 1000,
  budgetCode: "22231",
  sdg: { direct: "3.4(3.4.1)", indirect: "No" },
  iso37120: { direct: "No", indirect: "No" },
  sci2025: { direct: "No", indirect: "Health and Recretation" },
  thematicArea: "health-treatment",
  cycle: "",
  linkageScores: { sdgScore: 4, isoScore: 0, sciScore: 4, linkageType: "concurrence" },
  projectPhase: generateProjectPhase()}// Key Indicators combining ISO, SDG, and SCI
  ,
{id: "118",
  department: "स्वास्थ्य विभाग",
  sector: "सामाजिक विकास",
  subSector: "स्वास्थ्य",
  mainProgram: "स्वस्थ जीवनशैली सम्बन्धी कार्यक्रम",
  programName: "वायु गुणस्तर अनुगमन नेटवर्कका लागि बहुग्यास मोड्युलको खरिद, जडान तथा सञ्चालन",
  budget: 1000,
  budgetCode: "22522",
  sdg: { direct: "No", indirect: "11" },
  iso37120: { direct: "No", indirect: "8" },
  sci2025: { direct: "No", indirect: "Smart Governance" },
  thematicArea: "health-treatment",
  cycle: "",
  linkageScores: { sdgScore: 4, isoScore: 0, sciScore: 4, linkageType: "concurrence" },
  projectPhase: generateProjectPhase()}// Key Indicators combining ISO, SDG, and SCI
  ,
{id: "119",
  department: "स्वास्थ्य विभाग",
  sector: "सामाजिक विकास",
  subSector: "स्वास्थ्य",
  mainProgram: "स्वस्थ जीवनशैली सम्बन्धी कार्यक्रम",
  programName: "वायु गुणस्तर जनचेतना (Street Fest/Car free event) लागि हेल्दी सिटिज कार्यक्रम सहयोग",
  budget: 1500,
  budgetCode: "22522",
  sdg: { direct: "No", indirect: "11" },
  iso37120: { direct: "No", indirect: "8" },
  sci2025: { direct: "No", indirect: "Environment" },
  thematicArea: "health-treatment",
  cycle: "",
  linkageScores: { sdgScore: 4, isoScore: 0, sciScore: 4, linkageType: "concurrence" },
  projectPhase: generateProjectPhase()}// Key Indicators combining ISO, SDG, and SCI
 ,
{id: "120",
  department: "स्वास्थ्य विभाग",
  sector: "सामाजिक विकास",
  subSector: "स्वास्थ्य",
  mainProgram: "स्वस्थ जीवनशैली सम्बन्धी कार्यक्रम",
  programName: "प्रदूषणमा सीमापार स्रोत, स्रोत बर्गिकरण र वायुप्रणालीको योगदानसम्बन्धी अध्ययन तथा आवश्यक उपकरण खरिद",
  budget: 3000,
  budgetCode: "31132",
  sdg: { direct: "No", indirect: "11" },
  iso37120: { direct: "No", indirect: "8" },
  sci2025: { direct: "No", indirect: "Environment" },
  thematicArea: "health-treatment",
  cycle: "",
  linkageScores: { sdgScore: 4, isoScore: 0, sciScore: 4, linkageType: "concurrence" },
  projectPhase: generateProjectPhase()}// Key Indicators combining ISO, SDG, and SCI
 ,
{id: "121",
  department: "स्वास्थ्य विभाग",
  sector: "सामाजिक विकास",
  subSector: "स्वास्थ्य",
  mainProgram: "स्वस्थ जीवनशैली सम्बन्धी कार्यक्रम",
  programName: "वायू गुणस्तर ब्यबस्थापन इकाई स्थापनाका लागि आवाश्यक पुर्बाधार",
  budget: 1000,
  budgetCode: "31159",
  sdg: { direct: "No", indirect: "11" },
  iso37120: { direct: "No", indirect: "8" },
  sci2025: { direct: "No", indirect: "Smart Infrastructure" },
  thematicArea: "health-treatment",
  cycle: "",
  linkageScores: { sdgScore: 4, isoScore: 0, sciScore: 4, linkageType: "concurrence" },
  projectPhase: generateProjectPhase()}// Key Indicators combining ISO, SDG, and SCI
  ,
{id: "122",
  department: "स्वास्थ्य विभाग",
  sector: "सामाजिक विकास",
  subSector: "स्वास्थ्य",
  mainProgram: "स्वस्थ जीवनशैली सम्बन्धी कार्यक्रम",
  programName: "विभिन्न स्थान मा वर्षा, प्रदुषण मापन यन्त्र जडान (Piloting)",
  budget: 1000,
  budgetCode: "31159",
  sdg: { direct: "No", indirect: "11" },
  iso37120: { direct: "No", indirect: "8" },
  sci2025: { direct: "No", indirect: "Smart Infrastructure" },
  thematicArea: "health-treatment",
  cycle: "",
  linkageScores: { sdgScore: 4, isoScore: 0, sciScore: 4, linkageType: "concurrence" },
  projectPhase: generateProjectPhase()}// Key Indicators combining ISO, SDG, and SCI
  ,
{id: "123",
  department: "स्वास्थ्य विभाग",
  sector: "सामाजिक विकास",
  subSector: "स्वास्थ्य",
  mainProgram: "शहरी स्वास्थ्य सेवा",
  programName: "स्वास्थ्य विमा कार्यक्रमको लागि औषधि खरिद",
  budget: 30000,
  budgetCode: "27213",
  sdg: { direct: "3.8(3.8.1)", indirect: "No" },
  iso37120: { direct: "No", indirect: "11" },
  sci2025: { direct: "No", indirect: "Smart governance" },
  thematicArea: "health-treatment",
  cycle: "",
  linkageScores: { sdgScore: 4, isoScore: 0, sciScore: 4, linkageType: "concurrence" },
  projectPhase: generateProjectPhase()}// Key Indicators combining ISO, SDG, and SCI
  ,
{id: "124",
  department: "स्वास्थ्य विभाग",
  sector: "सामाजिक विकास",
  subSector: "स्वास्थ्य",
  mainProgram: "शहरी स्वास्थ्य सेवा",
  programName: "निःशुल्क वितरणको लागि औषधि खरिद",
  budget: 20000,
  budgetCode: "27213",
  sdg: { direct: "3.b(3.b.1)", indirect: "No" },
  iso37120: { direct: "No", indirect: "11" },
  sci2025: { direct: "No", indirect: "Smart Governance" },
  thematicArea: "health-treatment",
  cycle: "",
  linkageScores: { sdgScore: 4, isoScore: 0, sciScore: 4, linkageType: "concurrence" },
  projectPhase: generateProjectPhase()}// Key Indicators combining ISO, SDG, and SCI
  ,
{id: "125",
  department: "स्वास्थ्य विभाग",
  sector: "सामाजिक विकास",
  subSector: "स्वास्थ्य",
  mainProgram: "शहरी स्वास्थ्य सेवा",
  programName: "प्रयोगशाला सामाग्री खरिद",
  budget: 10000,
  budgetCode: "31122",
  sdg: { direct: "3.d(3.d.1)", indirect: "No" },
  iso37120: { direct: "No", indirect: "11" },
  sci2025: { direct: "No", indirect: "Health Infrastructure" },
  thematicArea: "health-treatment",
  cycle: "",
  linkageScores: { sdgScore: 4, isoScore: 0, sciScore: 4, linkageType: "concurrence" },
  projectPhase: generateProjectPhase()}// Key Indicators combining ISO, SDG, and SCI
  ,
{id: "126",
  department: "स्वास्थ्य विभाग",
  sector: "सामाजिक विकास",
  subSector: "स्वास्थ्य",
  mainProgram: "शहरी स्वास्थ्य सेवा",
  programName: "शहरी स्वास्थ्य प्रबर्दन केन्द्रहरुको पूर्वाधार विकास (वडाको माग बमोजिम भुक्तानी हुने)",
  budget: 10000,
  budgetCode: "31159",
  sdg: { direct: "3.8(3.8.1)", indirect: "No" },
  iso37120: { direct: "No", indirect: "11" },
  sci2025: { direct: "No", indirect: "Health Infrastructure" },
  thematicArea: "health-treatment",
  cycle: "",
  linkageScores: { sdgScore: 4, isoScore: 0, sciScore: 4, linkageType: "concurrence" },
  projectPhase: generateProjectPhase()}// Key Indicators combining ISO, SDG, and SCI
  ,
{id: "127",
  department: "स्वास्थ्य विभाग",
  sector: "सामाजिक विकास",
  subSector: "स्वास्थ्य",
  mainProgram: "शहरी स्वास्थ्य सेवा",
  programName: "शहरी स्वास्थ्य प्रबर्दन केन्द्रहरुको फर्निसिङ तथा कार्पेटिङ खरिद",
  budget: 10000,
  budgetCode: "31123",
  sdg: { direct: "3.8(3.8.1)", indirect: "No" },
  iso37120: { direct: "No", indirect: "19" },
  sci2025: { direct: "No", indirect: "Health Infrastructure" },
  thematicArea: "health-treatment",
  cycle: "",
  linkageScores: { sdgScore: 4, isoScore: 0, sciScore: 4, linkageType: "concurrence" },
  projectPhase: generateProjectPhase()}// Key Indicators combining ISO, SDG, and SCI
  ,
{id: "128",
  department: "स्वास्थ्य विभाग",
  sector: "सामाजिक विकास",
  subSector: "स्वास्थ्य",
  mainProgram: "शहरी स्वास्थ्य सेवा",
  programName: "स्वास्थ्य उपकरण खरिद",
  budget: 20000,
  budgetCode: "31122",
  sdg: { direct: "3.b(3.b.1)", indirect: "No" },
  iso37120: { direct: "No", indirect: "No" },
  sci2025: { direct: "No", indirect: "Health Infrastructure" },
  thematicArea: "health-treatment",
  cycle: "",
  linkageScores: { sdgScore: 4, isoScore: 0, sciScore: 4, linkageType: "concurrence" },
  projectPhase: generateProjectPhase()}// Key Indicators combining ISO, SDG, and SCI
  ,
{id: "129",
  department: "स्वास्थ्य विभाग",
  sector: "सामाजिक विकास",
  subSector: "स्वास्थ्य",
  mainProgram: "शहरी स्वास्थ्य सेवा",
  programName: "पोषण कर्नर/IEC कर्नर ,परामर्श सेवा कक्ष, स्तनपान कक्ष निर्माण",
  budget: 1000,
  budgetCode: "31159",
  sdg: { direct: "3.1", indirect: "No" },
  iso37120: { direct: "No", indirect: "No" },
  sci2025: { direct: "No", indirect: "Health Infrastructure" },
  thematicArea: "health-treatment",
  cycle: "",
  linkageScores: { sdgScore: 4, isoScore: 0, sciScore: 4, linkageType: "concurrence" },
  projectPhase: generateProjectPhase()}// Key Indicators combining ISO, SDG, and SCI
   ,
{id: "130",
  department: "स्वास्थ्य विभाग",
  sector: "सामाजिक विकास",
  subSector: "स्वास्थ्य",
  mainProgram: "शहरी स्वास्थ्य सेवा",
  programName: "स्वास्थ्यसँग सम्बन्धित सामाग्री छपाई",
  budget: 2000,
  budgetCode: "22315",
  sdg: { direct: "3.4", indirect: "No" },
  iso37120: { direct: "No", indirect: "6" },
  sci2025: { direct: "No", indirect: "Education Infrastructure" },
  thematicArea: "health-treatment",
  cycle: "",
  linkageScores: { sdgScore: 4, isoScore: 0, sciScore: 4, linkageType: "concurrence" },
  projectPhase: generateProjectPhase()}// Key Indicators combining ISO, SDG, and SCI
   ,
{id: "131",
  department: "स्वास्थ्य विभाग",
  sector: "सामाजिक विकास",
  subSector: "स्वास्थ्य",
  mainProgram: "शहरी स्वास्थ्य सेवा",
  programName: "स्वास्थ्य प्रबद्धन केन्द्रका कर्मचारीलाई प्रवर्द्धन केन्द्र संचालन अभिमुखिकरण कार्यक्रम",
  budget: 1000,
  budgetCode: "22522",
  sdg: { direct: "3.c(3.c.1)", indirect: "No" },
  iso37120: { direct: "No", indirect: "6" },
  sci2025: { direct: "No", indirect: "Education Infrastructure" },
  thematicArea: "health-treatment",
  cycle: "",
  linkageScores: { sdgScore: 4, isoScore: 0, sciScore: 4, linkageType: "concurrence" },
  projectPhase: generateProjectPhase()}// Key Indicators combining ISO, SDG, and SCI
  ,
{id: "132",
  department: "स्वास्थ्य विभाग",
  sector: "सामाजिक विकास",
  subSector: "स्वास्थ्य",
  mainProgram: "शहरी स्वास्थ्य सेवा",
  programName: "करार तथा श्रमबैकबाट लिएका जनशक्तिको तलब भत्ता",
  budget: 10000,
  budgetCode: "22413",
  sdg: { direct: "3.c(3.c.1)", indirect: "No" },
  iso37120: { direct: "No", indirect: "11" },
  sci2025: { direct: "No", indirect: "Smart Governance" },
  thematicArea: "health-treatment",
  cycle: "",
  linkageScores: { sdgScore: 4, isoScore: 0, sciScore: 4, linkageType: "concurrence" },
  projectPhase: generateProjectPhase()}// Key Indicators combining ISO, SDG, and SCI 
   ,
{id: "133",
  department: "स्वास्थ्य विभाग",
  sector: "सामाजिक विकास",
  subSector: "स्वास्थ्य",
  mainProgram: "शहरी स्वास्थ्य सेवा",
  programName: "सहरी स्वास्थ्य प्रवर्द्धन केन्द्र तथा का.म.पा. द्वारा संचालित स्वास्थ्य संस्थाहरुको स्वास्थ्यजन्य फोहोरमैला व्यवस्थापनका लागि निकासा",
  budget: 3500,
  budgetCode: "22414",
  sdg: { direct: "3.9", indirect: "No" },
  iso37120: { direct: "No", indirect: "16" },
  sci2025: { direct: "No", indirect: "Smart Governance" },
  thematicArea: "health-treatment",
  cycle: "",
  linkageScores: { sdgScore: 4, isoScore: 0, sciScore: 4, linkageType: "concurrence" },
  projectPhase: generateProjectPhase(),}// Key Indicators combining ISO, SDG, and SCI
  ,
{id: "134",
  department: "स्वास्थ्य विभाग",
  sector: "सामाजिक विकास",
  subSector: "स्वास्थ्य",
  mainProgram: "शहरी स्वास्थ्य सेवा",
  programName: "सहरी स्वास्थ्य प्रवर्द्धन केन्द्रहरका लागि आवशयक सफ्टवेयर खरिद",
  budget: 500,
  budgetCode: "31134",
  sdg: { direct: "3.8(3.8.1)", indirect: "No" },
  iso37120: { direct: "No", indirect: "11" },
  sci2025: { direct: "No", indirect: "ICT Infrastructure" },
  thematicArea: "health-treatment",
  cycle: "",
  linkageScores: { sdgScore: 4, isoScore: 0, sciScore: 4, linkageType: "concurrence" },
  projectPhase: generateProjectPhase(),},]// Key Indicators combining ISO, SDG, and SCI
   export const keyIndicators=[
    {
    id: "sdg-3-8",
    standard: "SDG",
    code: "3.8",
    name: "Universal Health Coverage",
    nameNp: "सार्वभौमिक स्वास्थ्य कभरेज",
    description:
      "Achieve universal health coverage, including financial risk protection, access to quality essential health-care services",
    relatedPrograms: 45,
  },
  {
    id: "sdg-3-4",
    standard: "SDG",
    code: "3.4",
    name: "NCD Prevention & Treatment",
    nameNp: "गैरसंचारी रोग रोकथाम",
    description: "Reduce premature mortality from non-communicable diseases through prevention and treatment",
    relatedPrograms: 12,
  },
  {
    id: "sdg-3-c",
    standard: "SDG",
    code: "3.c",
    name: "Health Workforce",
    nameNp: "स्वास्थ्य जनशक्ति",
    description: "Increase health financing and workforce development",
    relatedPrograms: 28,
  },
  {
    id: "iso-12-1",
    standard: "ISO 37120",
    code: "12.1",
    name: "Life Expectancy",
    nameNp: "जीवन प्रत्याशा",
    description: "Average life expectancy in the city",
    relatedPrograms: 8,
  },
  {
    id: "iso-12-2",
    standard: "ISO 37120",
    code: "12.2",
    name: "Hospital Beds",
    nameNp: "अस्पताल शैया",
    description: "Number of in-patient public hospital beds per 100,000 population",
    relatedPrograms: 6,
  },
  {
    id: "iso-12-3",
    standard: "ISO 37120",
    code: "12.3",
    name: "Physicians",
    nameNp: "चिकित्सक",
    description: "Number of physicians per 100,000 population",
    relatedPrograms: 15,
  },
  {
    id: "sci-1-1",
    standard: "SCI 2025",
    code: "Pillar 1.1",
    name: "Maternal & Child Health",
    nameNp: "मातृ तथा बाल स्वास्थ्य",
    description: "I-001: Average life expectancy, I-011: MCH services",
    relatedPrograms: 18,
  },
  {
    id: "sci-4-5",
    standard: "SCI 2025",
    code: "Pillar 4.5",
    name: "Digital Health Systems",
    nameNp: "डिजिटल स्वास्थ्य प्रणाली",
    description: "I-071: EMR adoption, I-073: HMIS usage",
    relatedPrograms: 8,
  },
]
